drop table gab_dxzp_xdxx;
create table gab_dxzp_xdxx  (
   ywsqbh             char(36)                        not null,
   jybm               char(6),
   xxlzms             char(2),
   csbwlsh            varchar(53),
   gaywsqbh           char(36)                        not null,
   fsjgbm             char(12)                        not null,
   sqjgdm             char(12)                        not null,
   mbjgdm             char(12)                        not null,
   cxztlb             char(2)                         not null,
   ywlx               varchar(4)                      not null,
   jjcd               char(2)                         not null,
   ajbh               varchar(30),
   ajlx               varchar(50)                     not null,
   ajsy               varchar(300)                    not null,
   ajsm               varchar(300),
   sqrq               char(8)                         not null,
   sqsj               char(6)                         not null,
   sqjgbm             char(12),
   sqjgmc             varchar(150)                    not null,
   jbrxm              varchar(40)                     not null,
   jbrzjlx            varchar(2)                      not null,
   jbrzjhm            varchar(30)                     not null,
   jbrdh              varchar(30),
   xcrxm              varchar(40)                     not null,
   xcrzjlx            varchar(2)                      not null,
   xcrzjhm            varchar(30)                     not null,
   ywrq               varchar(8),
   ywlsh              varchar(32),
   jbjg               varchar(16),
   jbgy               varchar(16),
   jbxm               varchar(100)                    not null,
   jbdh               varchar(30)                     not null,
   rwsl               integer                         not null,
   jgfkxdsj           integer,
   fkxdrq             char(8),
   fkxdsj             char(6),
   fkddrq             char(8),
   fkddsj             char(6),
   szclbz             char(1),
   clrq               char(8),
   clsj               char(6),
   zwrq               char(8)                         not null,
   systime            char(6)                         not null,
   zhqzlsh            varchar(16)                     not null,
   qqdzt              char(2)                         not null,
   ywydm              char(4),
   ywydxx             varchar(100),
   zxjg               char(1)                         not null,
   respcode           varchar(8),
   respmsg            varchar(100),
   zjrq               char(8),
   zjlsh              varchar(32),
   dzxh               varchar(36),
   sbpch              varchar(36),
   lxrq               char(8),
   lxpch              varchar(32),
   pcxh               integer,
   tjhxcs             integer,
   fkqzcs             integer,
   by11               varchar(30),
   by12               varchar(254),
   by13               varchar(254),
   constraint pkdxzp_xdxx primary key (ywsqbh)
);
