drop table gab_dxzp_lxdx cascade constraints;
drop table gab_dxzp_sbxx cascade constraints;
drop table gab_dxzp_xdxx cascade constraints;
drop table gab_dxzp_ztcx cascade constraints;
drop table gab_dxzp_jymx cascade constraints;
drop table gab_dxzp_qhcx cascade constraints;
drop table gab_dxzp_djxj cascade constraints;
drop table gab_dxzp_dtcx cascade constraints;
drop table gab_dxzp_ycsj cascade constraints;
drop table gab_dxzp_yckk cascade constraints;
drop table gab_dxzp_jjzf cascade constraints;
drop table gab_dxzp_sajb cascade constraints;
drop table gab_dxzp_sazh cascade constraints;
drop table gab_dxzp_zhsa cascade constraints;
drop table gab_dxzp_sfsa cascade constraints;
drop table gab_dxzp_zhxx_zhjyxx cascade constraints;
drop table gab_dxzp_zhjbxx_zhxx cascade constraints;
drop table gab_dxzp_jymx_zhjbxx cascade constraints;
drop table gab_dxzp_qhcx_sfqzxx cascade constraints;
drop table gab_dxzp_qhcx_zzhxx cascade constraints;
drop table gab_dxzp_qhcx_qlxx cascade constraints;
drop table gab_dxzp_dtcx_resp cascade constraints;
drop table gab_dxzp_dtjc_resp cascade constraints;
drop table gab_dxzp_ztcx_resp cascade constraints;
drop table gab_dxzp_kzhzh cascade constraints;
drop table gab_dxzp_bwpz cascade constraints;
drop table gab_dxzp_smjfj cascade constraints;
drop table gab_dxzp_hhmd cascade constraints;
drop table gab_dxzp_sbxx_jymx cascade constraints;
drop table gab_dxzp_sbxx_glzhxx cascade constraints;
drop table gab_dxzp_sbxx_zhxx cascade constraints;
drop table gab_dxzp_sbxx_plzt cascade constraints;
drop table gab_dxzp_hmhh cascade constraints;
drop table gab_dxzp_pcgy cascade constraints;
drop table gab_dxzp_jghh cascade constraints;
drop table gab_dxzp_gajgbm cascade constraints;
drop table gab_dxzp_lltj cascade constraints;

create table gab_dxzp_lltj  (
   csbwlsh              varchar2(53)                     not null,
   ywsqbh               varchar2(36),
   tgjgbm               varchar2(12),
   ywlx                 varchar2(4),
   ptywlx               varchar2(4),
   qssj                 char(14),
   jzsj                 char(14),
   tjsm                 varchar2(300),
   llzz                 integer,
   wfkllzz              integer,
   qttjz                integer,
   qttjsjsm             varchar2(150),
   bz                   varchar2(150),
   zwrq                 char(8)                         not null,
   systime              char(6)                         not null,
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_lltj primary key (csbwlsh)
);

create table gab_dxzp_gajgbm  (
   jgbm                 char(12)                        not null,
   jgmc                 varchar2(120),
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_gajgbm primary key (jgbm)
);

create table gab_dxzp_jghh  (
   jgh                  varchar2(16)                     not null,
   hh                   varchar2(14)                     not null,
   jgmc                 varchar2(100),
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_jghh primary key (jgh)
);

create table gab_dxzp_pcgy  (
   sbpch               varchar2(36)                     not null,
   scrq                 char(8)                         not null,
   sjgs                varchar2(10),
   sjtzm               varchar2(6),
   sbjg                varchar2(16),
   sbgy                varchar2(16),
   sbrq                 char(8),
   sbsj                 char(6),
   ysbjls               integer                         not null,
   wsbjls               integer,
   zwrq                 char(8)                         not null,
   systime              char(6)                         not null,
   by1                 varchar2(30),
   by2                 varchar2(254),
   by3                 varchar2(254),
   constraint pkdxzp_pcgy primary key (sbpch)
);

create table gab_dxzp_hmhh  (
   hh                 varchar2(14)                     not null,
   xh                 integer                         not null,
   hm                 varchar2(100)                    not null,
   hb                 char(1)                         not null,
   hbsm               varchar2(20)                     not null,
   jbjg               varchar2(16),
   jbgy               varchar2(16),
   lxdh               varchar2(20),
   by1                varchar2(30),
   by2                varchar2(254),
   by3                varchar2(254),
   constraint pk_gab_dxzp_hmhh primary key (hh)
);

create table gab_dxzp_sbxx_plzt  (
   sbpch                varchar2(36)                     not null,
   sbpcxh               integer                         not null,
   sbjydm               varchar2(6)                      not null,
   sbzt                 char(1)                         not null,
   respcode             varchar2(8),
   respmsg              varchar2(200),
   zwrq                 char(8)                         not null,
   systime              char(6)                         not null,
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_sbxx_plzt primary key (sbpch, sbpcxh)
);

create table gab_dxzp_sbxx_zhxx  (
   sbpch                varchar2(36)                     not null,
   sbpcxh               integer                         not null,
   zhxh                 varchar2(8)                      not null,
   jybm                 char(6),
   csbwlsh              varchar2(53),
   ywsqbh               varchar2(36),
   zh                   varchar2(30),
   kksj                 varchar2(14),
   kkdd                 varchar2(20),
   zwrq                 char(8)                         not null,
   systime              char(6)                         not null,
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_sbxx_zhxx primary key (sbpch, sbpcxh, zhxh)
);

create table gab_dxzp_sbxx_glzhxx  (
   sbpch                varchar2(36)                     not null,
   sbpcxh               integer                         not null,
   zhxh                 varchar2(8)                      not null,
   jybm                 char(6),
   csbwlsh              varchar2(53),
   ywsqbh               varchar2(36),
   zh                   varchar2(30),
   zhlx                 varchar2(30),
   zhzt                 varchar2(10),
   bz                   varchar2(3),
   chbz                 varchar2(10),
   zwrq                 char(8)                         not null,
   systime              char(6)                         not null,
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_sbxx_glzhxx primary key (sbpch, sbpcxh, zhxh)
);

create table gab_dxzp_sbxx_jymx  (
   sbpch                varchar2(36)                     not null,
   sbpcxh               integer                         not null,
   zhxh                 varchar2(8)                      not null,
   jyxh                 integer                         not null,
   jybm                 char(6),
   csbwlsh              varchar2(53),
   ywsqbh               varchar2(36),
   sjtzm                varchar2(4),
   zh                   varchar2(50),
   zhm                  varchar2(120),
   zjlx                 varchar2(2),
   zjhm                 varchar2(30),
   jylsh                varchar2(64),
   jysj                 varchar2(14),
   jylx                 varchar2(20),
   bz                   varchar2(3),
   jyje                 varchar2(20),
   zczhyhjg             varchar2(12),
   zczhyhmc             varchar2(136),
   zczhm                varchar2(60),
   zczh                 varchar2(30),
   ddzhyhjg             varchar2(12),
   ddzhyhmc             varchar2(136),
   ddzhm                varchar2(60),
   ddzh                 varchar2(30),
   ip                   varchar2(30),
   mac                  varchar2(20),
   sbid                 varchar2(20),
   jydd                 varchar2(150),
   beiz                 varchar2(150),
   zfbz                 char(1),
   zwrq                 char(8)                         not null,
   systime              char(6)                         not null,
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_sbxx_jymx primary key (sbpch, sbpcxh, zhxh, jyxh)
);

create table gab_dxzp_hhmd  (
   mdlx                 char(1),
   mdjz                 varchar2(64)                     not null,
   mdly                 char(1),
   ajlx                 varchar2(4),
   xm                   varchar2(100),
   mdjb                 char(1)                         not null,
   gxrq                 char(8)                         not null,
   gxsj                 char(6)                         not null,
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_hhmd primary key (mdjz)
);

create table gab_dxzp_bwpz  (
   jylxbm               char(6)                         not null,
   jylxmc               varchar2(100),
   jydm                 char(6),
   jymc                 varchar2(100),
   xxlzms               char(1),
   ldhzdbz              char(1),
   fkqzdbz              char(1),
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_bwpz primary key (jylxbm)
);

create table gab_dxzp_lxdx  (
   lxrq                 varchar2(8)                      not null,
   lxpch                varchar2(32)                     not null,
   lxsj                 varchar2(6),
   respcode             varchar2(6),
   respmsg              varchar2(200),
   lxbs                 integer,
   lxwj                 varchar2(254),
   by1                  varchar2(32),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_lxdx primary key (lxrq, lxpch)
);

create table gab_dxzp_sbxx  (
   csbwlsh              varchar2(53)                     not null,
   jybm                 char(6),
   sbpch                varchar2(36),
   ywsqbh               varchar2(36)                     not null,
   sqjgdm               char(12)                        not null,
   mbjgdm               char(12)                        not null,
   ywlx                 varchar2(4)                      not null,
   sjms                 varchar2(500)                    not null,
   sbjgdm               varchar2(16),
   sbjgmc               varchar2(200),
   jbrxm                varchar2(100)                    not null,
   jbrdh                varchar2(30)                     not null,
   ywrq                 varchar2(8),
   ywlsh                varchar2(32),
   jbjg                 varchar2(16),
   jbgy                 varchar2(16),
   clrq                 char(8),
   clsj                 char(6),
   sbjls                integer                         not null,
   sbjg                 char(2),
   respcode             varchar2(8),
   respmsg              varchar2(200),
   zwrq                 char(8)                         not null,
   systime              char(6)                         not null,
   zhqzlsh              varchar2(16)                     not null,
   sbpcwjm              varchar2(254),
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_sbxx primary key (csbwlsh)
);

create table gab_dxzp_xdxx  (
   ywsqbh             char(36)                        not null,
   jybm               char(6),
   xxlzms             char(2),
   csbwlsh            varchar2(53),
   gaywsqbh           char(36)                        not null,
   fsjgbm             char(12)                        not null,
   sqjgdm             char(12)                        not null,
   mbjgdm             char(12)                        not null,
   cxztlb             char(2)                         not null,
   ywlx               varchar2(4)                      not null,
   jjcd               char(2)                         not null,
   ajbh               varchar2(30),
   ajlx               varchar2(50)                     not null,
   ajsy               varchar2(300)                    not null,
   ajsm               varchar2(300),
   sqrq               char(8)                         not null,
   sqsj               char(6)                         not null,
   sqjgbm             char(12),
   sqjgmc             varchar2(150)                    not null,
   jbrxm              varchar2(40)                     not null,
   jbrzjlx            varchar2(2)                      not null,
   jbrzjhm            varchar2(30)                     not null,
   jbrdh              varchar2(30),
   xcrxm              varchar2(40)                     not null,
   xcrzjlx            varchar2(2)                      not null,
   xcrzjhm            varchar2(30)                     not null,
   ywrq               varchar2(8),
   ywlsh              varchar2(32),
   jbjg               varchar2(16),
   jbgy               varchar2(16),
   jbxm               varchar2(100)                    not null,
   jbdh               varchar2(30)                     not null,
   rwsl               integer                         not null,
   jgfkxdsj           integer,
   fkxdrq             char(8),
   fkxdsj             char(6),
   fkddrq             char(8),
   fkddsj             char(6),
   szclbz             char(1),
   clrq               char(8),
   clsj               char(6),
   zwrq               char(8)                         not null,
   systime            char(6)                         not null,
   zhqzlsh            varchar2(16)                     not null,
   qqdzt              char(2)                         not null,
   ywydm              char(4),
   ywydxx             varchar2(100),
   zxjg               char(1)                         not null,
   respcode           varchar2(8),
   respmsg            varchar2(100),
   zjrq               char(8),
   zjlsh              varchar2(32),
   dzxh               varchar2(36),
   sbpch              varchar2(36),
   lxrq               char(8),
   lxpch              varchar2(32),
   pcxh               integer,
   tjhxcs             integer,
   fkqzcs             integer,
   by11               varchar2(30),
   by12               varchar2(254),
   by13               varchar2(254),
   constraint pkdxzp_xdxx primary key (ywsqbh)
);

create table gab_dxzp_ztcx  (
   ywsqbh             varchar2(36)                     not null,
   rwxh               integer                         not null,
   khyh               varchar2(12),
   khyhmc             varchar2(150)                    not null,
   zhlb               varchar2(2)                      not null,
   zhmc               varchar2(150)                    not null,
   zh                 varchar2(30)                     not null,
   jgfksj             integer                         not null,
   zxjg               char(1),
   respcode           varchar2(8),
   respmsg            varchar2(100),
   fksm               varchar2(300),
   fkjgmc             varchar2(150),
   zwrq               char(8)                         not null,
   systime            char(6)                         not null,
   by1                varchar2(30),
   by2                varchar2(254),
   by3                varchar2(254),
   constraint pkdxzp_ztcx primary key (ywsqbh, rwxh)
);

create table gab_dxzp_djxj  (
   ywsqbh               varchar2(36)                     not null,
   rwxh                 integer                         not null,
   yywsqbh              varchar2(36),
   khyh                 varchar2(12),
   khyhmc               varchar2(150)                    not null,
   zhlb                 varchar2(2)                      not null,
   zhmc                 varchar2(120)                    not null,
   zh                   varchar2(50)                     not null,
   zjlx                 varchar2(2),
   zjhm                 varchar2(30),
   djfs                 char(2),
   bz                   varchar2(3),
   je                   varchar2(18)                     not null,
   dqr                  char(8)                         not null,
   djqssj               char(14),
   djjssj               char(14),
   jgfksj               integer                         not null,
   zxjg                 char(1),
   respcode             varchar2(8),
   respmsg              varchar2(100),
   kh                   varchar2(30),
   zxqssj               char(14),
   zxjssj               char(14),
   fksm                 varchar2(300),
   fkjgmc               varchar2(150),
   djje                 varchar2(20),
   zhye                 varchar2(20),
   zxdjje               varchar2(20),
   zxdjrq               varchar2(12),
   zhkyye               varchar2(20),
   zxdjjg               varchar2(60),
   zwrq                 char(8)                         not null,
   systime              char(6)                         not null,
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_djxj primary key (ywsqbh, rwxh)
);

create table gab_dxzp_jymx  (
   ywsqbh             varchar2(36)                     not null,
   rwxh               integer                         not null,
   khyh               varchar2(12),
   khyhmc             varchar2(150)                    not null,
   zhlb               varchar2(2)                      not null,
   zhmc               varchar2(120)                    not null,
   zh                 varchar2(30)                     not null,
   cxnr               char(8),
   cxqsrq             char(8),
   cxqssj             char(6),
   cxjzrq             char(8),
   cxjzsj             char(6),
   jgfksj             integer                         not null,
   zxjg               char(1),
   respcode           varchar2(8),
   respmsg            varchar2(100),
   fksm               varchar2(300),
   fkjgmc             varchar2(150),
   zwrq               char(8)                         not null,
   systime            char(6)                         not null,
   by1                varchar2(30),
   by2                varchar2(254),
   by3                varchar2(254),
   constraint pkdxzp_jymx primary key (ywsqbh, rwxh)
);

create table gab_dxzp_qhcx  (
   ywsqbh             varchar2(36)                     not null,
   rwxh               integer                         not null,
   zhlb               varchar2(2)                      not null,
   cxzjlx             varchar2(15)                     not null,
   cxzjhm             varchar2(30)                     not null,
   zhmc               varchar2(150),
   cxnr               char(8),
   jgfksj             integer                         not null,
   bankname           varchar2(150)                    not null,
   zxjg               char(1),
   respcode           varchar2(8),
   respmsg            varchar2(100),
   fksm               varchar2(500),
   fkjgmc             varchar2(200),
   zwrq               char(8)                         not null,
   systime            char(6)                         not null,
   by1                varchar2(30),
   by2                varchar2(254),
   by3                varchar2(254),
   constraint pkdxzp_qhcx primary key (ywsqbh, rwxh)
);

create table gab_dxzp_jjzf  (
   ywsqbh               varchar2(36)                     not null,
   rwxh                 integer                         not null,
   yywsqbh              varchar2(36),
   sfblc                char(2),
   yjbsqbh              varchar2(36),
   kh                   varchar2(30),
   zczhyh               varchar2(12),
   zczhyhmc             varchar2(150),
   zczhm                varchar2(100),
   zczh                 varchar2(30),
   bz                   varchar2(3),
   zcje                 varchar2(18)                     not null,
   zcrq                 char(8)                         not null,
   zcsj                 char(6)                         not null,
   khyh                 varchar2(12),
   khyhmc               varchar2(150)                    not null,
   zhlb                 varchar2(2)                      not null,
   zhmc                 varchar2(120)                    not null,
   zh                   varchar2(50)                     not null,
   dqr                  char(8)                         not null,
   jgfksj               integer                         not null,
   zfqssj               char(14),
   zfjssj               char(14),
   zxjg                 char(1),
   respcode             varchar2(8),
   respmsg              varchar2(100),
   zxqssj               char(14),
   zxjssj               char(14),
   fksm                 varchar2(300),
   fkjgmc               varchar2(150),
   zhye                 varchar2(20),
   zwrq                 char(8)                         not null,
   systime              char(6)                         not null,
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_jjzf primary key (ywsqbh, rwxh)
);

create table gab_dxzp_dtcx  (
   ywsqbh             varchar2(36)                     not null,
   rwxh               integer                         not null,
   yywsqbh            varchar2(36),
   bz                 varchar2(3),
   khyh               varchar2(12),
   khyhmc             varchar2(150)                    not null,
   zhlb               varchar2(2)                      not null,
   zhmc               varchar2(120)                    not null,
   kh                 varchar2(30),
   zh                 varchar2(30)                     not null,
   dtml               char(1)                         not null,
   zxqsrq             varchar2(14),
   zxjzrq             varchar2(14),
   dtcxqssj           varchar2(14),
   dtcxjzsj           varchar2(14),
   jgfksj             integer                         not null,
   zxjg               char(1),
   respcode           varchar2(8),
   respmsg            varchar2(100),
   fksm               varchar2(300),
   fkjgmc             varchar2(150),
   zwrq               char(8)                         not null,
   systime            char(6)                         not null,
   by1                varchar2(30),
   by2                varchar2(254),
   by3                varchar2(254),
   constraint pkdxzp_dtcx primary key (ywsqbh, rwxh)
);

create table gab_dxzp_ycsj  (
   sbpch                varchar2(36)                     not null,
   sbpcxh               integer                         not null,
   jybm                 char(6),
   csbwlsh              varchar2(53),
   ywsqbh               varchar2(36),
   ywlx                 varchar2(4),
   sjtzm                varchar2(4),
   yywsqbh              varchar2(36),
   jylsh                varchar2(64),
   jysj                 varchar2(14),
   jylx                 varchar2(20),
   bz                   varchar2(3),
   je                   varchar2(20),
   zcyhjg               varchar2(12),
   zcyhmc               varchar2(136),
   zczhhm               varchar2(60),
   zczh                 varchar2(30),
   ddyhjg               varchar2(12),
   ddyhmc               varchar2(136),
   ddzhm                varchar2(60),
   ddzh                 varchar2(30),
   ipdz                 varchar2(30),
   mac                  varchar2(20),
   sbid                 varchar2(20),
   jydd                 varchar2(150),
   beiz                 varchar2(150),
   zwrq                 char(8)                         not null,
   systime              char(6)                         not null,
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_ycsj primary key (sbpch, sbpcxh)
);

create table gab_dxzp_yckk  (
   sbpch                varchar2(36)                     not null,
   sbpcxh               integer                         not null,
   jybm                 char(6),
   csbwlsh              varchar2(53),
   ywsqbh               varchar2(36),
   ywlx                 varchar2(4),
   sjtzm                varchar2(4),
   yywsqbh              varchar2(36),
   zjlx                 varchar2(2),
   zjhm                 varchar2(30),
   xm                   varchar2(60),
   zwrq                 char(8)                         not null,
   systime              char(6)                         not null,
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_yckk primary key (sbpch, sbpcxh)
);

create table gab_dxzp_sajb  (
   sbpch                varchar2(36)                     not null,
   sbpcxh               integer                         not null,
   jybm                 char(6),
   csbwlsh              varchar2(53),
   ywsqbh               varchar2(36),
   jsjgid               varchar2(12),
   tgjgbm               varchar2(12),
   ywlx                 varchar2(4),
   shrxm                varchar2(60),
   shrlxdh              varchar2(30),
   zjlx                 varchar2(2),
   zjhm                 varchar2(30),
   sjms                 varchar2(300),
   ajjblx               char(2),
   zjrq                 char(8),
   zjlsh                varchar2(32),
   dzxh                 varchar2(36),
   yxbz                 char(1),
   qqdzt                char(2),
   zxjg                 char(1),
   respcode             varchar2(8),
   respmsg              varchar2(100),
   fkdjjzsj             varchar2(14),
   cxjg                 varchar2(4),
   zwrq                 char(8)                         not null,
   systime              char(6)                         not null,
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_sajb primary key (sbpch, sbpcxh)
);

create table gab_dxzp_sazh  (
   sbpch                varchar2(36)                     not null,
   sbpcxh               integer                         not null,
   jybm                 char(6),
   csbwlsh              varchar2(53),
   ywsqbh               varchar2(36),
   ywlx                 varchar2(4),
   sjtzm                varchar2(4),
   yywsqbh              varchar2(36),
   kh                   varchar2(30),
   zhm                  varchar2(120),
   zjlx                 varchar2(2),
   zjhm                 varchar2(30),
   lxdh                 varchar2(30),
   txdz                 varchar2(150),
   yzbm                 varchar2(10),
   zhlx                 varchar2(30),
   zhzt                 varchar2(10),
   khrq                 char(8),
   xhrq                 char(8),
   kkdd                 varchar2(20),
   zwrq                 char(8)                         not null,
   systime              char(6)                         not null,
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_sazh primary key (sbpch, sbpcxh)
);

create table gab_dxzp_zhsa  (
   jybm                 char(6),
   csbwlsh              varchar2(53)                     not null,
   ywsqbh               varchar2(36)                     not null,
   ywlx                 varchar2(4)                      not null,
   zh                   varchar2(30)                     not null,
   zhm                  varchar2(120)                    not null,
   zt                   char(1),
   zwrq                 char(8)                         not null,
   systime              char(6)                         not null,
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_zhsa primary key (csbwlsh)
);

create table gab_dxzp_sfsa  (
   jybm                 char(6),
   csbwlsh              varchar2(53)                     not null,
   ywsqbh               varchar2(36)                     not null,
   ywlx                 varchar2(4)                      not null,
   zjlx                 varchar2(6)                      not null,
   zjhm                 varchar2(30)                     not null,
   zhhm                 varchar2(120),
   zt                   char(1),
   zwrq                 char(8)                         not null,
   systime              char(6)                         not null,
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_sfsa primary key (csbwlsh)
);

create table gab_dxzp_zhxx_zhjyxx  (
   ywsqbh             varchar2(36)                     not null,
   rwxh               integer                         not null,
   zhxh               varchar2(8)                      not null,
   zhjyxh             varchar2(4)                      not null,
   jylx               varchar2(50),
   jdbz               varchar2(1)                      not null,
   bz                 varchar2(10)                     not null,
   jyje               varchar2(20)                     not null,
   jyye               varchar2(20)                     not null,
   jysj               varchar2(14)                     not null,
   jylsh              varchar2(50)                     not null,
   jydfmc             varchar2(60),
   jydfzh             varchar2(50),
   jydfzjhm           varchar2(30),
   jydfzhkhh          varchar2(90),
   jyzy               varchar2(150),
   jywdmc             varchar2(150)                    not null,
   jywddm             varchar2(20)                     not null,
   rzh                varchar2(30),
   cph                varchar2(30),
   pzzl               varchar2(10),
   pzh                varchar2(30),
   xjbz               char(2)                         not null,
   zdh                varchar2(30),
   jysfcg             char(2)                         not null,
   jyfsd              varchar2(150),
   shmc               varchar2(150),
   shh                varchar2(30),
   ip                 varchar2(30),
   mac                varchar2(50),
   jygyh              varchar2(20),
   beiz               varchar2(150),
   zwrq               char(8)                         not null,
   systime            char(6)                         not null,
   by1                varchar2(30),
   by2                varchar2(254),
   by3                varchar2(254),
   constraint pkdxzp_zhxx_zhjyxx primary key (ywsqbh, rwxh, zhxh, zhjyxh)
);

create table gab_dxzp_zhjbxx_zhxx  (
   ywsqbh               varchar2(36)                     not null,
   rwxh                 integer                         not null,
   zhxh                 varchar2(8)                      not null,
   zh                   varchar2(50)                     not null,
   zhlx                 varchar2(30)                     not null,
   zhzt                 varchar2(10)                     not null,
   bz                   varchar2(3)                      not null,
   chbz                 varchar2(4),
   zhye                 varchar2(18)                     not null,
   kyye                 varchar2(18)                     not null,
   zhjysj               char(14)                        not null,
   zwrq                 char(8)                         not null,
   systime              char(6)                         not null,
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_zhjbxx_zhxx primary key (ywsqbh, rwxh, zhxh)
);

create table gab_dxzp_jymx_zhjbxx  (
   ywsqbh             varchar2(36)                     not null,
   rwxh               integer                         not null,
   zhm                varchar2(120)                    not null,
   kzh                varchar2(30),
   khwd               varchar2(150)                    not null,
   khwddm             varchar2(20)                     not null,
   khrq               char(14)                        not null,
   xhrq               char(14),
   xhwd               varchar2(150),
   beiz               varchar2(150),
   zwrq               char(8)                         not null,
   systime            char(6)                         not null,
   by1                varchar2(30),
   by2                varchar2(254),
   by3                varchar2(254),
   constraint pkdxzp_jymx_zhjbxx primary key (ywsqbh, rwxh)
);

create table gab_dxzp_qhcx_sfqzxx  (
   ywsqbh             varchar2(36)                     not null,
   rwxh               integer                         not null,
   csxh               varchar2(8)                      not null,
   zh                 varchar2(50),
   kh                 varchar2(30),
   djksr              char(14),
   djjzr              char(14),
   djjgmc             varchar2(50),
   bz                 varchar2(3),
   djje               varchar2(20),
   beiz               varchar2(1000),
   djcslx             char(4),
   zwrq               char(8)                         not null,
   systime            char(6)                         not null,
   by1                varchar2(30),
   by2                varchar2(254),
   by3                varchar2(254),
   constraint pkdxzp_qhcx_sfqzxx primary key (ywsqbh, rwxh, csxh)
);

create table gab_dxzp_qhcx_zzhxx  (
   ywsqbh             varchar2(36)                     not null,
   rwxh               integer                         not null,
   zzhxh              varchar2(8)                      not null,
   zh                 varchar2(40),
   zzhlb              varchar2(30),
   zhzt               varchar2(10),
   bz                 varchar2(3),
   chbz               varchar2(8),
   zhye               varchar2(20),
   kyye               varchar2(20),
   zhjysj             char(14)                        not null,
   zwrq               char(8)                         not null,
   systime            char(6)                         not null,
   by1                varchar2(30),
   by2                varchar2(254),
   by3                varchar2(254),
   constraint pkdxzp_qhcx_zzhxx primary key (ywsqbh, rwxh, zzhxh)
);

create table gab_dxzp_qhcx_qlxx  (
   ywsqbh             varchar2(36)                     not null,
   rwxh               integer                         not null,
   xh                 varchar2(8)                      not null,
   zh                 varchar2(50),
   kh                 varchar2(30),
   zjlx               varchar2(15)                     not null,
   zjhm               varchar2(30),
   qllx               varchar2(2),
   qlrxm              varchar2(60),
   qlje               varchar2(20),
   qlrtxdz            varchar2(60),
   qlrlxfs            varchar2(50),
   zwrq               char(8)                         not null,
   systime            char(6)                         not null,
   by1                varchar2(30),
   by2                varchar2(254),
   by3                varchar2(254),
   constraint pkdxzp_qhcx_qlxx primary key (ywsqbh, rwxh, xh)
);

create table gab_dxzp_dtcx_resp  (
   sbpch              varchar2(36)                     not null,
   sbpcxh             integer                         not null,
   ywsqbh             varchar2(36),
   rwxh               integer,
   zhm                varchar2(120)                    not null,
   zh                 varchar2(50),
   jylx               varchar2(50),
   jdbz               varchar2(1)                      not null,
   bz                 varchar2(3)                      not null,
   jyje               varchar2(18)                     not null,
   jyye               varchar2(18)                     not null,
   jysj               char(14)                        not null,
   jylsh              varchar2(50)                     not null,
   jydfmc             varchar2(60),
   jydfzh             varchar2(30),
   jydfzjhm           varchar2(30),
   jydfzhkhh          varchar2(60),
   jyzy               varchar2(150),
   jywdmc             varchar2(150),
   jywddm             varchar2(20),
   rzh                varchar2(30),
   cph                varchar2(30),
   pzzl               varchar2(10),
   pzh                varchar2(30),
   xjbz               char(2)                         not null,
   zdh                varchar2(30),
   jysfcg             char(2)                         not null,
   jyfsd              varchar2(150),
   shmc               varchar2(150),
   shh                varchar2(30),
   ip                 varchar2(30),
   mac                varchar2(50),
   jygyh              varchar2(20),
   beiz               varchar2(150),
   fksm               varchar2(300),
   fkjgmc             varchar2(150),
   zwrq               char(8)                         not null,
   systime            char(6)                         not null,
   by1                varchar2(30),
   by2                varchar2(254),
   by3                varchar2(254),
   constraint pkdxzp_dtcx_resp primary key (sbpch, sbpcxh)
);

create table gab_dxzp_dtjc_resp  (
   ywsqbh               varchar2(36)                     not null,
   rwxh                 integer                         not null,
   jcdtcxsm             varchar2(300),
   fksm                 varchar2(150),
   zwrq                 char(8)                         not null,
   systime              char(6)                         not null,
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_dtjc_resp primary key (ywsqbh, rwxh)
);

create table gab_dxzp_ztcx_resp  (
   ywsqbh             varchar2(36)                     not null,
   rwxh               integer                         not null,
   fkjgmc             varchar2(150),
   fksm               varchar2(300),
   zjlx               varchar2(2)                      not null,
   zjhm               varchar2(30)                     not null,
   ztmc               varchar2(100)                    not null,
   lxsj               varchar2(20)                     not null,
   dbrxm              varchar2(60),
   dbrzjlx            varchar2(2),
   dbrzjhm            varchar2(30),
   zzdz               varchar2(150),
   zzdh               varchar2(20),
   gzdw               varchar2(100),
   dwdz               varchar2(150),
   dwdh               varchar2(20),
   yxdz               varchar2(60),
   frdb               varchar2(60),
   frdbzjlx           varchar2(2),
   frdbzjhm           varchar2(30),
   khgszzhm           varchar2(18),
   gsnsh              varchar2(20),
   dsnsh              varchar2(20),
   zwrq               char(8)                         not null,
   systime            char(6)                         not null,
   by1                varchar2(30),
   by2                varchar2(254),
   by3                varchar2(254),
   constraint pkdxzp_ztcx_resp primary key (ywsqbh, rwxh)
);

create table gab_dxzp_kzhzh  (
   zh                 varchar2(30)                     not null,
   kh                 varchar2(30),
   zhmc               varchar2(100),
   dccs               integer,
   dczt               char(1),
   dcywsqbh           varchar2(40),
   dcqssj             varchar2(14),
   dcjssj             varchar2(14),
   djcs               integer,
   djzt               char(1),
   djljje             number(18,2),
   djywsqbh           varchar2(40),
   djqssj             varchar2(14),
   djjssj             varchar2(14),
   zfcs               integer,
   zfzt               char(1),
   zfljje             number(18,2),
   zfywsqbh           varchar2(40),
   zfqssj             varchar2(14),
   zfjssj             varchar2(14),
   khcs               integer,
   khljje             number(18,2),
   khywsqbh           varchar2(40),
   by1                varchar2(32),
   by2                varchar2(255),
   by3                varchar2(255),
   constraint pkdxzp_kzhzh primary key (zh)
);

create table gab_dxzp_smjfj  (
   ywsqbh               varchar2(36)                     not null,
   xh                   integer                         not null,
   wjm                  varchar2(254),
   wjdx                 varchar2(12),
   yxjz                 varchar2(36),
   zwrq                 char(8)                         not null,
   systime              char(6)                         not null,
   by1                  varchar2(30),
   by2                  varchar2(254),
   by3                  varchar2(254),
   constraint pkdxzp_smjfj primary key (ywsqbh, xh)
);
