#ifndef  __ICPS_JB_BANK_XML_H__
#define  __ICPS_JB_BANK_XML_H__
		/* 蚂蚁借呗银行初审反馈信息 */
		#define XMLNM_ICPS_JB_BANK_ISEXISTCUST                      "/jiebei/drcbank/isExistCust"                /*是否存量客户*/                          
		#define XMLNM_ICPS_JB_BANK_ISEXISTDEBTCUST                  "/jiebei/drcbank/isExistDebtCust"            /*是否存量借记卡客户*/                    
		#define XMLNM_ICPS_JB_BANK_BALANCE                          "/jiebei/drcbank/balance"                    /*卡内余额*/                              
		#define XMLNM_ICPS_JB_BANK_AVGBALANCELAST3DAYS              "/jiebei/drcbank/avgBalanceLast3days"        /*近3个月日均余额*/                       
		#define XMLNM_ICPS_JB_BANK_AVGBALANCELAST6DAYS              "/jiebei/drcbank/avgBalanceLast6days"        /*近6个月日均余额*/                       
		#define XMLNM_ICPS_JB_BANK_INCOMELAST3M                     "/jiebei/drcbank/incomeLast3m"               /*近3个月银行流水收入金额数*/             
		#define XMLNM_ICPS_JB_BANK_PAYLAST3M                        "/jiebei/drcbank/payLast3m"                  /*近3个月银行流水支出金额数*/             
		#define XMLNM_ICPS_JB_BANK_INCOMELAST6M                     "/jiebei/drcbank/incomeLast6m"               /*近6个月银行流水收入金额数*/             
		#define XMLNM_ICPS_JB_BANK_PAYLAST6M                        "/jiebei/drcbank/payLast6m"                  /*近6个月银行流水支出金额数*/             
		#define XMLNM_ICPS_JB_BANK_ISEXISTCCUST                     "/jiebei/drcbank/isExistCCust"               /*是否存量信用卡客户*/                    
		#define XMLNM_ICPS_JB_BANK_CURRCCAMT                        "/jiebei/drcbank/currCCAmt"                  /*本行信用卡授信额度*/                    
		#define XMLNM_ICPS_JB_BANK_CURRDISBURSECCAMT                "/jiebei/drcbank/currDisburseCCAmt"          /*本行信用卡当前使用额度*/                
		#define XMLNM_ICPS_JB_BANK_ISEXISTFINCUST                   "/jiebei/drcbank/isExistFinCust"             /*是否存量理财客户*/                      
		#define XMLNM_ICPS_JB_BANK_FINBALANCE                       "/jiebei/drcbank/finBalance"                 /*理财余额*/                              
		#define XMLNM_ICPS_JB_BANK_AVGFINBALANCELAST6M              "/jiebei/drcbank/avgFinBalanceLast6m"        /*近6个月日均理余额*/                     
		#define XMLNM_ICPS_JB_BANK_ISEXISTINSURANCECUST             "/jiebei/drcbank/isExistInsuranceCust"       /*是否存量保险客户*/                      
		#define XMLNM_ICPS_JB_BANK_ISEXISTLOANCUST                  "/jiebei/drcbank/isExistLoanCust"            /*是否存量贷款客户*/                      
		#define XMLNM_ICPS_JB_BANK_OPERATIONLOANBAL                 "/jiebei/drcbank/operationLoanBal"           /*经营类贷款总余额*/                      
		#define XMLNM_ICPS_JB_BANK_PERSONALCREDITBAL                "/jiebei/drcbank/personalCreditBal"          /*个人信用类贷总余额*/                    
		#define XMLNM_ICPS_JB_BANK_AUTOLOANBAL                      "/jiebei/drcbank/autoLoanBal"                /*车贷余额*/                              
		#define XMLNM_ICPS_JB_BANK_AUTOASSET                        "/jiebei/drcbank/autoAsset"                  /*车产价值评估额*/                        
		#define XMLNM_ICPS_JB_BANK_HOUSELOANBAL                     "/jiebei/drcbank/houseLoanBal"               /*房贷余额*/                              
		#define XMLNM_ICPS_JB_BANK_HOUSEASSET                       "/jiebei/drcbank/houseAsset"                 /*房产价值评估额*/                        
		#define XMLNM_ICPS_JB_BANK_ISSTOCKCUST                      "/jiebei/drcbank/isStockCust"                /*是否证券客户*/                          
		#define XMLNM_ICPS_JB_BANK_ISTHIRDDEPOSITORY                "/jiebei/drcbank/isThirdDepository"          /*是否第三方存管客户*/                    
		#define XMLNM_ICPS_JB_BANK_ISPAYROLLCUST                    "/jiebei/drcbank/isPayrollCust"              /*是否工资代发客户*/                      
		#define XMLNM_ICPS_JB_BANK_ISSOCIALSECURITYCUST             "/jiebei/drcbank/isSocialSecurityCust"       /*是否社保代缴客户*/                      
		#define XMLNM_ICPS_JB_BANK_ISLIFEPAYMENTCUST                "/jiebei/drcbank/isLifePaymentCUst"          /*是否水电煤代缴客户*/                    
		#define XMLNM_ICPS_JB_BANK_INCORPORATION                    "/jiebei/drcbank/incorporation"              /*工作单位*/                              
		#define XMLNM_ICPS_JB_BANK_INCORIGIN                        "/jiebei/drcbank/incOrigin"                  /*工作单位数据来源*/                      
		#define XMLNM_ICPS_JB_BANK_POSITION                         "/jiebei/drcbank/position"                   /*职位*/                                  
		#define XMLNM_ICPS_JB_BANK_POSITIONORIGIN                   "/jiebei/drcbank/positionOrigin"             /*职位信息来源*/                          
		#define XMLNM_ICPS_JB_BANK_INDUSTRY                         "/jiebei/drcbank/industry"                   /*行业*/                                  
		#define XMLNM_ICPS_JB_BANK_INDUSTRYORIGIN                   "/jiebei/drcbank/industryOrigin"             /*行业信息来源*/                          
		#define XMLNM_ICPS_JB_BANK_WORKYEARS                        "/jiebei/drcbank/workYears"                  /*工作年限*/                              
		#define XMLNM_ICPS_JB_BANK_WORKYEARSORIGIN                  "/jiebei/drcbank/workYearsOrigin"            /*工作年限信息来源*/                      
		#define XMLNM_ICPS_JB_BANK_INCOME                           "/jiebei/drcbank/income"                     /*月收入区间*/                            
		#define XMLNM_ICPS_JB_BANK_INCOMEORIGIN                     "/jiebei/drcbank/incomeOrigin"               /*月收入信息来源*/                        
		#define XMLNM_ICPS_JB_BANK_MARRIAGESTATUS                   "/jiebei/drcbank/marriageStatus"             /*婚姻状态*/                              
		#define XMLNM_ICPS_JB_BANK_MARRIAGEORIGIN                   "/jiebei/drcbank/marriageOrigin"             /*婚姻状态信息来源*/                      
		#define XMLNM_ICPS_JB_BANK_ISOPERATION                      "/jiebei/drcbank/isOperation"                /*是否经营者（工商企业或个体工商企业主）*/
		#define XMLNM_ICPS_JB_BANK_OPERATIONORIGIN                  "/jiebei/drcbank/operationOrigin"            /*是否经营者信息来源*/                    
		#define XMLNM_ICPS_JB_BANK_ISINNERBLACKCUST                 "/jiebei/drcbank/isInnerBlackCust"           /*是否击中内部黑名单客户*/                
		#define XMLNM_ICPS_JB_BANK_ISPOLICECERTIFIED                "/jiebei/drcbank/isPoliceCertified"          /*是否公安网身份验证成功*/                
		#define XMLNM_ICPS_JB_BANK_ISCOURTEXECCUST                  "/jiebei/drcbank/isCourtExecCust"            /*是否击中被执行人等涉诉信息*/            
		#define XMLNM_ICPS_JB_BANK_ISQUERYHOUSEFUND                 "/jiebei/drcbank/isQueryHouseFund"           /*是否有查询公积金信息*/                  
		#define XMLNM_ICPS_JB_BANK_FUNDQUERYDATE                    "/jiebei/drcbank/fundQueryDate"              /*公积金查询时间*/                        
		#define XMLNM_ICPS_JB_BANK_FUNDMONTHAMT                     "/jiebei/drcbank/fundMonthAmt"               /*公积金查询月缴纳额*/                    
		#define XMLNM_ICPS_JB_BANK_FUNDACCOUNTDATE                  "/jiebei/drcbank/fundAccountDate"            /*公积金开户日期*/                        
		#define XMLNM_ICPS_JB_BANK_FUNDMONTHSLAST6M                 "/jiebei/drcbank/fundMonthsLast6m"           /*近6个月累计缴纳月数*/                   
		#define XMLNM_ICPS_JB_BANK_FUNDAMTLAST6M                    "/jiebei/drcbank/fundAmtLast6m"              /*近6个月累计缴纳金额*/                   
		#define XMLNM_ICPS_JB_BANK_FUNDTOTALMONTHS                  "/jiebei/drcbank/fundTotalMonths"            /*总缴纳月数*/                            
		#define XMLNM_ICPS_JB_BANK_FUNDTOTALAMT                     "/jiebei/drcbank/fundTotalAmt"               /*总缴纳金额*/                            
		#define XMLNM_ICPS_JB_BANK_FUNDMAXAMT                       "/jiebei/drcbank/fundMaxAmt"                 /*公积金属地缴纳上限*/                    
		#define XMLNM_ICPS_JB_BANK_ISQUERYSOCIALSECURITY            "/jiebei/drcbank/isQuerySocialSecurity"      /*是否有查询社保信息*/                    
		#define XMLNM_ICPS_JB_BANK_SOCIALQUERYDATE                  "/jiebei/drcbank/socialQueryDate"            /*社保信息查询时间*/                      
		#define XMLNM_ICPS_JB_BANK_PENSIONQUERYMONTHAMT             "/jiebei/drcbank/pensionQueryMonthAmt"       /*养老保险查询月缴纳额*/                  
		#define XMLNM_ICPS_JB_BANK_PENSIONACCOUNTDATE               "/jiebei/drcbank/pensionAccountDate"         /*养老保险开户日期*/                      
		#define XMLNM_ICPS_JB_BANK_PENSIONMONTHSLAST6M              "/jiebei/drcbank/pensionMonthsLast6m"        /*近6个月养老保险累计缴纳月数*/           
		#define XMLNM_ICPS_JB_BANK_PENSIONAMTLAST6M                 "/jiebei/drcbank/pensionAmtLast6m"           /*近6个月养老保险累计缴纳金额*/           
		#define XMLNM_ICPS_JB_BANK_PENSIONTOTALMONTHS               "/jiebei/drcbank/pensionTotalMonths"         /*养老保险总缴纳月数*/                    
		#define XMLNM_ICPS_JB_BANK_PENSIONTOTALAMT                  "/jiebei/drcbank/pensionTotalAmt"            /*养老保险总缴纳金额*/                    
		#define XMLNM_ICPS_JB_BANK_MEDICAREMONTHAMT                 "/jiebei/drcbank/medicareMonthAmt"           /*医疗保险查询月缴纳额*/                  
		#define XMLNM_ICPS_JB_BANK_MEDICAREACCOUNTDATE              "/jiebei/drcbank/medicareAccountDate"        /*医疗保险开户日期*/                      
		#define XMLNM_ICPS_JB_BANK_MEDICAREMONTHSLAST6M             "/jiebei/drcbank/medicareMonthsLast6m"       /*近6个月医疗保险累计缴纳月数*/           
		#define XMLNM_ICPS_JB_BANK_MEDICAREAMTLAST6M                "/jiebei/drcbank/medicareAmtLast6m"          /*近6个月医疗保险累计缴纳金额*/           
		#define XMLNM_ICPS_JB_BANK_MEDICARETOTALMONTHS              "/jiebei/drcbank/medicareTotalMonths"        /*医疗保险总缴纳月数*/                    
		#define XMLNM_ICPS_JB_BANK_MEDICARETOTALAMT                 "/jiebei/drcbank/medicareTotalAmt"           /*医疗保险总缴纳金额*/                    
		#define XMLNM_ICPS_JB_BANK_ISQUERYDEGREE                    "/jiebei/drcbank/isQueryDegree"              /*是否有查询学历信息*/                    
		#define XMLNM_ICPS_JB_BANK_SCHOOLNAME                       "/jiebei/drcbank/schoolName"                 /*院校名称*/                              
		#define XMLNM_ICPS_JB_BANK_DEGREELEVEL                      "/jiebei/drcbank/degreeLevel"                /*学历层次*/                              
		#define XMLNM_ICPS_JB_BANK_DEGREETYPE                       "/jiebei/drcbank/degreeType"                 /*学历类别*/                              
		#define XMLNM_ICPS_JB_BANK_ENTRANCEYEAR                     "/jiebei/drcbank/entranceYear"               /*入学年份*/                              
		#define XMLNM_ICPS_JB_BANK_ISQUERYCOMMUNICATION             "/jiebei/drcbank/isQueryCommunication"       /*是否有查询运营商信息*/                  
		#define XMLNM_ICPS_JB_BANK_COMMUNICATION                    "/jiebei/drcbank/communication"              /*运营商*/                                
		#define XMLNM_ICPS_JB_BANK_ONLINEDAYS                       "/jiebei/drcbank/onlineDays"                 /*在网时长*/                              
		#define XMLNM_ICPS_JB_BANK_TOTALTELFARE                     "/jiebei/drcbank/totalTelFare"               /*总话费账单金额*/                        
		#define XMLNM_ICPS_JB_BANK_TOTALCALHOURS                    "/jiebei/drcbank/totalCalHours"              /*半年内通话时长*/                        
		#define XMLNM_ICPS_JB_BANK_ISOUTBLACKCUST                   "/jiebei/drcbank/isOutBlackCust"             /*是否击中外部查询黑名单*/                
		#define XMLNM_ICPS_JB_BANK_BANKENCRYPTEDFEATURE            "/jiebei/drcbank/bankencryptedfeature"      /*AI加密数据*/
		#define XMLNM_ICPS_JB_BANK_BANK_ENCRYPTED_META              "/jiebei/drcbank/bank_encrypted_meta"        /*AI加密数据描述信息*/
          
#endif


