/**********************************************************************
版权所有:杭州恒生电子股份有限公司
项目名称:综合应用平台（GAPS）项目
版    本:V2.1.0.1
操作系统:AIX LINUX
数 据 库:
文 件 名:batch_msg.h
文件描述:批量平台出错信息宏定义头文件
项 目 组:中间业务产品研发组
程 序 员:中间业务产品研发组
发布时间:2011-8-1 10:53:19
**********************************************************************/
/*
修改记录
修改日期:
修改内容:
修改人:
*/
#ifndef __BATCH_MSG_H__
#define __BATCH_MSG_H__
    #define MSG_BATCH_AUDITING_NOFUND         "BATCH: 无对应数据审核配置信息[%s]"
    #define MSG_BATCH_AUDITINGREG_NOFUND      "BATCH: 无对应函数登记信息,funcid=[%s]"
    #define MSG_BATCH_BDCGBZ_FF               "BATCH: 步点成功标志非法[%s]"
    #define MSG_BATCH_BDZT_DD                 "BATCH: 步点状态为断点不允许重复操作"
    #define MSG_BATCH_BDZT_FF                 "BATCH: 步点状态非法不允许重复操作"
    #define MSG_BATCH_BDZT_SUCC               "BATCH: 步点操作已成功不允许重复操作"
    #define MSG_BATCH_BDZT_WAIT               "BATCH: 步点状态为等待不允许重复操作"
    #define MSG_BATCH_BUSITASKOVER            "BATCH: 应用任务数超限"
    #define MSG_BATCH_CFCZ                    "BATCH: 步点不允许重复操作"
    #define MSG_BATCH_CFCZOVER                "BATCH: 步点重复操作次数超限"
    #define MSG_BATCH_CZBD_NULL               "BATCH: 操作步点不能为空"
    #define MSG_BATCH_DEL_YWMX                "BATCH: 删除批量业务明细信息失败"
    #define MSG_BATCH_DJLSH_NULL              "BATCH: 登记流水号不能为空"
    #define MSG_BATCH_DJRQ_NULL               "BATCH: 登记日期不能为空"
    #define MSG_BATCH_EXEC_FLOW               "BATCH: 执行步点流程[%s]失败"
    #define MSG_BATCH_EXECSO                  "BATCH: 函数[%s]运行失败"
    #define MSG_BATCH_EXPORT                  "BATCH: 导出整个xml节点错误[%d],[%s]"
    #define MSG_BATCH_FILECOLUMN_LISTFAIL     "BATCH: 创建文件列信息链表失败,[%s]"
    #define MSG_BATCH_FILE_MAPFAIL            "BATCH: 映射文件失败,[%s]"
    #define MSG_BATCH_FILEMAP_LISTFAIL        "BATCH: 创建文件映射链表失败,[%s]"
    #define MSG_BATCH_FILESORT_LISTFAIL       "BATCH: 创建文件分类链表失败,[%s]"
    #define MSG_BATCH_FLOWCFG_NOFUND          "BATCH: 无对应流程配置信息"
    #define MSG_BATCH_GET_FILESORT            "BATCH: 取文件明细分类信息失败"
    #define MSG_BATCH_GET_STEPCFG             "BATCH: 获取流程步点属性处理失败"
    #define MSG_BATCH_GLB_NOFUND              "BATCH: 无对应的关联表信息[%s]"
    #define MSG_BATCH_HSRK_NOFUND             "BATCH: 查找审核函数[%s]入口失败"
    #define MSG_BATCH_INS_PLRW                "BATCH: 登记批量任务失败"    
    #define MSG_BATCH_INS_PLRWBD              "BATCH: 登记批量步点明细失败"
    #define MSG_BATCH_JYHS_FAIL               "BATCH: 审核函数校验失败"
    #define MSG_BATCH_LOAD_YWMX               "BATCH: 导入业务明细信息失败"
    #define MSG_BATCH_LPWJM_NULL              "BATCH: 来盘文件名不能为空"
    #define MSG_BATCH_LRZBS_MXZBS             "BATCH: 录入总金额总笔数与明细不符,若客户端请检查密钥"
    #define MSG_BATCH_LRZJE_MXZJE             "BATCH: 录入总金额总笔数与明细不符,若客户端请检查密钥"
    #define MSG_BATCH_LXX_NOFUND              "BATCH: 无对应列信息"
    #define MSG_BATCH_PKRQ_NULL               "BATCH: 批扣日期不能为空"
    #define MSG_BATCH_PRODUCTTASKOVER         "BATCH: 业务[%s]任务数超限"
    #define MSG_BATCH_PTPCH_NULL              "BATCH: 平台批次号不能为空"
    #define MSG_BATCH_SEL_MAPINFO             "BATCH: 查询映射信息失败"
    #define MSG_BATCH_SEL_PLRW                "BATCH: 查询批量任务表记录失败"
    #define MSG_BATCH_SEL_PLRWBD              "BATCH: 查询批量任务步点失败"
    #define MSG_BATCH_SEL_RUNCTR              "BATCH: 查询运行控制信息失败"
    #define MSG_BATCH_SEL_SHGZPZ              "BATCH: 查询审核规则配置失败"
    #define MSG_BATCH_SEL_WBWJDJ              "BATCH: 查询外部文件登记失败"
    #define MSG_BATCH_SH_WBWJDJ               "BATCH: 该批量任务需要先对外部文件进行审核"
    #define MSG_BATCH_SEL_WJLX                "BATCH: 查询文件类型信息失败"
    #define MSG_BATCH_WJLX_NULL               "BATCH: 文件类型空"
    #define MSG_BATCH_SHPCH                   "BATCH: 该商户批次已录入"
    #define MSG_BATCH_WJDJ_EXIST              "BATCH: 该商户来盘文件已录入"
    #define MSG_BATCH_SJRK                    "BATCH: 数据入库失败"
    #define MSG_BATCH_SO_CLOSE                "BATCH: 关闭动态链接库[%s]失败[%s]"
    #define MSG_BATCH_SO_OPEN                 "BATCH: 打开动态链接库[%s]失败"
    #define MSG_BATCH_SQLSEL_PLRW_ERR         "BATCH: 查询批量任务记录失败"
    #define MSG_BATCH_TABLEREG_LISTFAIL       "BATCH: 创建注册表信息链表失败,[%s]"
    #define MSG_BATCH_TOTALPROC               "BATCH: 汇总记录处理失败,ret=[%d]"
    #define MSG_BATCH_DETAILPROC              "BATCH: 明细记录处理失败,ret=[%d]"
    #define MSG_BATCH_UPDFLAG_FF              "BATCH: 外部文件更新标志非法"
    #define MSG_BATCH_UPD_PLRW                "BATCH: 更新批量任务表失败"
    #define MSG_BATCH_UPD_PLRWBD              "BATCH: 更新批量步点明细失败"
    #define MSG_BATCH_UPD_SHZT                "BATCH: 更新审核状态失败"
    #define MSG_BATCH_UPD_WBWJDJ              "BATCH: 更新外部文件登记失败"
    #define MSG_BATCH_WBWJDJ_CX               "BATCH: 该批次文件已取销"
    #define MSG_BATCH_WBWJDJ_FAIL             "BATCH: 批次文件已处理失败"
    #define MSG_BATCH_WBWJDJ_NOFUND           "BATCH: 无对应外部文件登记信息"
    #define MSG_BATCH_WBWJDJ_PRE              "BATCH: 该批次文件未就绪,文件名=[%s]"
    #define MSG_BATCH_WBWJDJ_RUNNING          "BATCH: 批次文件正在处理"
    #define MSG_BATCH_WBWJDJ_SUCC             "BATCH: 该批次文件已处理结束"
    #define MSG_BATCH_WBWJDJ_UNKNOWN          "BATCH: 该批次文件状态[%s]不允许发起任务"
    #define MSG_BATCH_WJBS_NULL               "BATCH: 文件标识不能为空"
    #define MSG_BATCH_WJM_NULL                "BATCH: 文件名不能为空"
    #define MSG_BATCH_WJZBS_MXZBS             "BATCH: 来盘文件汇总信息总笔数[%d]与明细[%d]不符"
    #define MSG_BATCH_WJZJE_MXZJE             "BATCH: 来盘文件汇总信息总金额与明细不符"
    #define MSG_BATCH_XMLDEL                  "BATCH: 删除XML元素[%s]失败 XMLMSG[%s]"
    #define MSG_BATCH_XMLIMPORT               "BATCH: 导入XML结构数据错误 XMLMSG[%s]"
    #define MSG_BATCH_YSBS_NULL               "BATCH: 映射标识不能为空"
    #define MSG_BATCH_YWBH_NULL               "BATCH: 业务编号不能为空"
    #define MSG_BATCH_YWBM_NULL               "BATCH: 业务表名不能为空"
    #define MSG_BATCH_INS_WBWJDJ              "BATCH: 登记外部文件失败"
    #define MSG_BATCH_OPENFILE                "BATCH: 打开批量业务文件失败"
    #define MSG_BATCH_WRITEFILE               "BATCH: 写入批量业务文件失败"
    #define MSG_BATCH_SJTJ_GENFILE            "BATCH: 生成数据提交核心文件失败"
    #define MSG_BATCH_LPWJ_NULL               "BATCH: 来盘文件明细记录为空"
    #define MSG_BATCH_BREAK_LAUNCHED          "BATCH: 断点任务已触发"
    #define MSG_BATCH_FILECOLUMN_NOTFOUND     "BATCH: 获取文件列信息失败"
    #define MSG_BATCH_WJGS_FF                 "BATCH: 文件格式非法"
    #define MSG_BATCH_TABLECOL_NOTFOUND       "BATCH: 表字段配置信息未找到"
    #define MSG_BATCH_SJTH_ZJE                "BATCH: 数据提回合计金额不符"
    #define MSG_BATCH_SJTH_ZBS                "BATCH: 数据提回合计笔数不符"
    #define MSG_BATCH_SJHP_UNLOAD             "BATCH: 回盘数据导出失败"
    #define MSG_BATCH_RESP_CONV               "BATCH: 转换响应码失败"
    #define MSG_BATCH_PROC_DETAIL             "BATCH: 处理文件明细信息失败"
    #define MSG_BATCH_PROC_TOTAL              "BATCH: 处理文件汇总信息失败"
    #define MSG_BATCH_SJHP_PZNULL             "BATCH: 未配置回盘文件信息,请检查外部文件映射"
    #define MSG_BATCH_SJHP_HPBZ               "BATCH: 数据回盘标志非法"
    #define MSG_BATCH_CANCELED                "BATCH: 任务已被撤销或冲正"
    #define MSG_BATCH_SJTH_PROC               "BATCH: 数据提回处理失败"
    #define MSG_BATCH_HQSJ_GETFILE            "BATCH: 获取批扣数据文件失败"
    #define MSG_BATCH_QUERY_PQRYERR           "BATCH: 明细分页查询失败"
    #define MSG_BATCH_QUERY_COLERR            "BATCH: 明细分页查询字段超长"
    #define MSG_BATCH_JYFSERR                 "BATCH: 交易方式未设置为批量"
    #define MSG_BATCH_TIMEERR                 "BATCH: 未到开始处理时间"
    #define MSG_BATCH_TIME_SETERR             "BATCH: 开始处理时间未设置"
    #define MSG_BATCH_LAUNCHED                "BATCH: 当前任务已触发"
    #define MSG_BATCH_SPLIT_INVAL             "BATCH: 非法分隔符"
    #define MSG_BATCH_DE_FLAG                 "BATCH: 加解密标志非法"
    #define MSG_BATCH_GEN_KHBH                "BATCH: 生成批量客户端客户编号出错"
    #define MSG_BATCH_GEN_XYBH                "BATCH: 生成批量客户端协议编号出错"
    #define MSG_BATCH_NULL_CLI_BH             "BATCH: 协议编号客户编号不能同时为空"
    #define MSG_BATCH_NO_CLIINFO              "BATCH: 客户端签约信息不存在,若是客户端，请确认是否领用密钥"
    #define MSG_BATCH_UPD_CLIINFO             "BATCH: 无需要更新信息"
    #define MSG_BATCH_QUYCON                  "BATCH: 查询条件不能为空"
    #define MSG_BATCH_FIELTRANSFER            "BATCH: 文件类型转换失败"
    #define MSG_BATCH_SJRK_SQLNOTNULL         "BATCH: 文件解析失败(第%ld行非空字段存在空值)"
    #define MSG_BATCH_DES_FILEERR             "BATCH: 读取加密文件失败，加密文件不规则"
    #define MSG_BATCH_DES_WRERR               "BATCH: 加解密过程写文件失败"
    #define MSG_BATCH_RESPNULL                "BATCH: 响应码转换标识不能为空"	
    #define MSG_BATCH_SJRK_OVERLEN            "BATCH: 文件解析失败(第%ld行有数据超长),若客户端请检查密钥"
    #define MSG_BATCH_UPDPLRW_NFND            "BATCH: 未找到需要处理的批量任务或已被处理"
    #define MSG_BATCH_STEPINFO                "BATCH: 外围传入和查询库表步点信息不一致,或已处理"
    #define MSG_BATCH_STEP_SUCC               "BATCH: 批量任务已处理完成，不需要再次发起"
    #define MSG_BATCH_PROCING                 "BATCH: 批量任务正在处理中，请稍候"
    #define MSG_BATCH_SJHP_NOTHIS             "BATCH: 批量任务流程没有配置数据回盘步点"
    #define MSG_BATCH_SJHP_FORCE              "BATCH: 强制回盘，处理失败"
    #define MSG_BATCH_SJTH_NOCONFIG           "BATCH: 主机映射，更新条件或者更新内容未配置" 
    #define MSG_BATCH_TOTALLINE_NOTNULL       "BATCH: 汇总记录第[%d-%s]域非空为空"
    #define MSG_BATCH_DETAILLINE_NOTNULL      "BATCH: 明细行第[%d-%s]域非空为空"
    #define MSG_BATCH_DETAILLINE_SPECHAR      "BATCH: 明细行第[%d-%s]域第%d个是特殊字符"
    #define MSG_BATCH_WJGS_CONV               "BATCH: 文件编码格式[%s]转换失败"
    #define MSG_BATCH_RWQT_CPDMNEQ            "BATCH: 被嵌套任务的产品代码配置有误"
    #define MSG_BATCH_DIRRETURN               "BATCH: 只有某步点失败时才能直接回盘"
    #define MSG_BATCH_DIRFORCE                "BATCH: 被嵌套批量任务不能被直接终止"
    #define MSG_BATCH_TOTALLINE_COLS          "BATCH: 汇总行列数不符,配置%d列,实际%d列"
    #define MSG_BATCH_DETAILLINE_COLS         "BATCH: 明细行列数不符,配置%d列,实际%d列"
    #define MSG_BATCH_SJTJ_NIGHT              "BATCH: 只有夜间批量才能指定数据提交开始处理日期或时间"
    #define MSG_BATCH_SJTH_UPDZERO            "BATCH: 数据提回明细更新条件作用于零条记录"
    #define MSG_BATCH_SJTH_UPDMULT            "BATCH: 数据提回明细更新条件作用于多条记录"
    #define MSG_BATCH_JYJGNULL                "BATCH: 交易机构不能为空"
    #define MSG_BATCH_SJRK_SUMAMT             "BATCH: 文件解析失败(汇总金额超限)"
    #define MSG_BATCH_SJTJ_WAIT               "BATCH: 未到达指定的处理日期及时间点"
#endif                                                                               
