drop table gab_dxzp_lxdx ;
drop table gab_dxzp_sbxx ;
drop table gab_dxzp_xdxx ;
drop table gab_dxzp_ztcx ;
drop table gab_dxzp_jymx ;
drop table gab_dxzp_qhcx ;
drop table gab_dxzp_djxj ;
drop table gab_dxzp_dtcx ;
drop table gab_dxzp_ycsj ;
drop table gab_dxzp_yckk ;
drop table gab_dxzp_jjzf ;
drop table gab_dxzp_sajb ;
drop table gab_dxzp_sazh ;
drop table gab_dxzp_zhsa ;
drop table gab_dxzp_sfsa ;
drop table gab_dxzp_zhxx_zhjyxx ;
drop table gab_dxzp_zhjbxx_zhxx ;
drop table gab_dxzp_jymx_zhjbxx ;
drop table gab_dxzp_qhcx_sfqzxx ;
drop table gab_dxzp_qhcx_zzhxx ;
drop table gab_dxzp_qhcx_qlxx ;
drop table gab_dxzp_dtcx_resp ;
drop table gab_dxzp_dtjc_resp ;
drop table gab_dxzp_ztcx_resp ;
drop table gab_dxzp_kzhzh ;
drop table gab_dxzp_bwpz ;
drop table gab_dxzp_smjfj ;
drop table gab_dxzp_hhmd;
drop table gab_dxzp_sbxx_jymx;
drop table gab_dxzp_sbxx_glzhxx;
drop table gab_dxzp_sbxx_zhxx;
drop table gab_dxzp_sbxx_plzt;
drop table gab_dxzp_hmhh ;
drop table gab_dxzp_pcgy ;
drop table gab_dxzp_jghh ;
drop table gab_dxzp_gajgbm;
drop table gab_dxzp_lltj ;

create table gab_dxzp_lltj  (
   csbwlsh              varchar(53)                     not null,
   ywsqbh               varchar(36),
   tgjgbm               varchar(12),
   ywlx                 varchar(4),
   ptywlx               varchar(4),
   qssj                 varchar(14),
   jzsj                 varchar(14),
   tjsm                 varchar(300),
   llzz                 integer,
   wfkllzz              integer,
   qttjz                integer,
   qttjsjsm             varchar(150),
   bz                   varchar(150),
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_lltj primary key (csbwlsh)
);

create table gab_dxzp_gajgbm  (
   jgbm                 varchar(12)                        not null,
   jgmc                 varchar(120),
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_gajgbm primary key (jgbm)
);

create table gab_dxzp_jghh  (
   jgh                  varchar(16)                     not null,
   hh                   varchar(14)                     not null,
   jgmc                 varchar(100),
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_jghh primary key (jgh)
);

create table gab_dxzp_pcgy  (
   sbpch                varchar(36)                     not null,
   scrq                 varchar(8)                         not null,
   sjgs                 varchar(10),
   sjtzm                varchar(6),
   sbjg                 varchar(16),
   sbgy                 varchar(16),
   sbrq                 varchar(8),
   sbsj                 varchar(6),
   ysbjls               integer                         not null,
   wsbjls               integer,
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_pcgy primary key (sbpch)
);

create table gab_dxzp_hmhh  (
   hh                   varchar(14)                     not null,
   xh                   integer                         not null,
   hm                   varchar(100)                    not null,
   hb                   varchar(1)                         not null,
   hbsm                 varchar(20)                     not null,
   jbjg                 varchar(16),
   jbgy                 varchar(16),
   lxdh                 varchar(20),
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_hmhh primary key (hh)
);

create table gab_dxzp_sbxx_plzt  (
   sbpch                varchar(36)                     not null,
   sbpcxh               integer                         not null,
   sbjydm               varchar(6)                      not null,
   sbzt                 varchar(1)                         not null,
   respcode             varchar(8),
   respmsg              varchar(200),
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_sbxx_plzt primary key (sbpch, sbpcxh)
);

create table gab_dxzp_sbxx_zhxx  (
   sbpch                varchar(36)                     not null,
   sbpcxh               integer                         not null,
   zhxh                 varchar(8)                      not null,
   jybm                 varchar(6),
   csbwlsh              varchar(53),
   ywsqbh               varchar(36),
   zh                   varchar(30),
   kksj                 varchar(14),
   kkdd                 varchar(20),
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_sbxx_zhxx primary key (sbpch, sbpcxh, zhxh)
);

create table gab_dxzp_sbxx_glzhxx  (
   sbpch                varchar(36)                     not null,
   sbpcxh               integer                         not null,
   zhxh                 varchar(8)                      not null,
   jybm                 varchar(6),
   csbwlsh              varchar(53),
   ywsqbh               varchar(36),
   zh                   varchar(30),
   zhlx                 varchar(30),
   zhzt                 varchar(10),
   bz                   varchar(3),
   chbz                 varchar(10),
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_sbxx_glzhxx primary key (sbpch, sbpcxh, zhxh)
);

create table gab_dxzp_sbxx_jymx  (
   sbpch                varchar(36)                     not null,
   sbpcxh               integer                         not null,
   zhxh                 varchar(8)                      not null,
   jyxh                 integer                         not null,
   jybm                 varchar(6),
   csbwlsh              varchar(53),
   ywsqbh               varchar(36),
   sjtzm                varchar(4),
   zh                   varchar(50),
   zhm                  varchar(120),
   zjlx                 varchar(2),
   zjhm                 varchar(30),
   jylsh                varchar(64),
   jysj                 varchar(14),
   jylx                 varchar(20),
   bz                   varchar(3),
   jyje                 varchar(20),
   zczhyhjg             varchar(12),
   zczhyhmc             varchar(136),
   zczhm                varchar(60),
   zczh                 varchar(30),
   ddzhyhjg             varchar(12),
   ddzhyhmc             varchar(136),
   ddzhm                varchar(60),
   ddzh                 varchar(30),
   ip                   varchar(30),
   mac                  varchar(20),
   sbid                 varchar(20),
   jydd                 varchar(150),
   beiz                 varchar(150),
   zfbz                 varchar(1),
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_sbxx_jymx primary key (sbpch, sbpcxh, zhxh, jyxh)
);

create table gab_dxzp_hhmd  (
   mdlx                 varchar(1),
   mdjz                 varchar(64)                     not null,
   mdly                 varchar(1),
   ajlx                 varchar(4),
   xm                   varchar(100),
   mdjb                 varchar(1)                         not null,
   gxrq                 varchar(8)                         not null,
   gxsj                 varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_hhmd primary key (mdjz)
);

create table gab_dxzp_bwpz  (
   jylxbm               varchar(6)                         not null,
   jylxmc               varchar(100),
   jydm                 varchar(6),
   jymc                 varchar(100),
   xxlzms               varchar(1),
   ldhzdbz              varchar(1),
   fkqzdbz              varchar(1),
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_bwpz primary key (jylxbm)
);

create table gab_dxzp_lxdx  (
   lxrq                 varchar(8)                      not null,
   lxpch                varchar(32)                     not null,
   lxsj                 varchar(6),
   respcode             varchar(6),
   respmsg              varchar(200),
   lxbs                 integer,
   lxwj                 varchar(254),
   by1                  varchar(32),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_lxdx primary key (lxrq, lxpch)
);

create table gab_dxzp_sbxx  (
   csbwlsh              varchar(53)                     not null,
   jybm                 varchar(6),
   sbpch                varchar(36),
   ywsqbh               varchar(36)                     not null,
   sqjgdm               varchar(12)                        not null,
   mbjgdm               varchar(12)                        not null,
   ywlx                 varchar(4)                      not null,
   sjms                 varchar(500)                    not null,
   sbjgdm               varchar(16),
   sbjgmc               varchar(200),
   jbrxm                varchar(100)                    not null,
   jbrdh                varchar(30)                     not null,
   ywrq                 varchar(8),
   ywlsh                varchar(32),
   jbjg                 varchar(16),
   jbgy                 varchar(16),
   clrq                 varchar(8),
   clsj                 varchar(6),
   sbjls                integer                         not null,
   sbjg                 varchar(2),
   respcode             varchar(8),
   respmsg              varchar(200),
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   zhqzlsh              varchar(16)                     not null,
   sbpcwjm              varchar(254),
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_sbxx primary key (csbwlsh)
);

create table gab_dxzp_xdxx  (
   ywsqbh             varchar(36)                        not null,
   jybm               varchar(6),
   xxlzms             varchar(2),
   csbwlsh            varchar(53),
   gaywsqbh           varchar(36)                        not null,
   fsjgbm             varchar(12)                        not null,
   sqjgdm             varchar(12)                        not null,
   mbjgdm             varchar(12)                        not null,
   cxztlb             varchar(2)                         not null,
   ywlx               varchar(4)                      not null,
   jjcd               varchar(2)                         not null,
   ajbh               varchar(30),
   ajlx               varchar(50)                     not null,
   ajsy               varchar(300)                    not null,
   ajsm               varchar(300),
   sqrq               varchar(8)                         not null,
   sqsj               varchar(6)                         not null,
   sqjgbm             varchar(12),
   sqjgmc             varchar(150)                    not null,
   jbrxm              varchar(40)                     not null,
   jbrzjlx            varchar(2)                      not null,
   jbrzjhm            varchar(30)                     not null,
   jbrdh              varchar(30),
   xcrxm              varchar(40)                     not null,
   xcrzjlx            varchar(2)                      not null,
   xcrzjhm            varchar(30)                     not null,
   ywrq               varchar(8),
   ywlsh              varchar(32),
   jbjg               varchar(16),
   jbgy               varchar(16),
   jbxm               varchar(100)                    not null,
   jbdh               varchar(30)                     not null,
   rwsl               integer                         not null,
   jgfkxdsj           integer,
   fkxdrq             varchar(8),
   fkxdsj             varchar(6),
   fkddrq             varchar(8),
   fkddsj             varchar(6),
   szclbz             varchar(1),
   clrq               varchar(8),
   clsj               varchar(6),
   zwrq               varchar(8)                         not null,
   systime            varchar(6)                         not null,
   zhqzlsh            varchar(16)                     not null,
   qqdzt              varchar(2)                         not null,
   ywydm              varchar(4),
   ywydxx             varchar(100),
   zxjg               varchar(1)                         not null,
   respcode           varchar(8),
   respmsg            varchar(100),
   zjrq               varchar(8),
   zjlsh              varchar(32),
   dzxh               varchar(36),
   sbpch              varchar(36),
   lxrq               varchar(8),
   lxpch              varchar(32),
   pcxh               integer,
   tjhxcs             integer,
   fkqzcs             integer,
   by11               varchar(30),
   by12               varchar(254),
   by13               varchar(254),
   constraint pkdxzp_xdxx primary key (ywsqbh)
);

create table gab_dxzp_ztcx  (
   ywsqbh             varchar(36)                     not null,
   rwxh               integer                         not null,
   khyh               varchar(12)                     not null,
   khyhmc             varchar(150),
   zhlb               varchar(2)                      not null,
   zhmc               varchar(150)                    not null,
   zh                 varchar(30)                     not null,
   jgfksj             integer                         not null,
   zxjg               varchar(1),
   respcode           varchar(8),
   respmsg            varchar(100),
   fksm               varchar(300),
   fkjgmc             varchar(150),
   zwrq               varchar(8)                         not null,
   systime            varchar(6)                         not null,
   by1                varchar(30),
   by2                varchar(254),
   by3                varchar(254),
   constraint pkdxzp_ztcx primary key (ywsqbh, rwxh)
);

create table gab_dxzp_djxj  (
   ywsqbh               varchar(36)                     not null,
   rwxh                 integer                         not null,
   yywsqbh              varchar(36),
   khyh                 varchar(12)                     not null,
   khyhmc               varchar(150),
   zhlb                 varchar(2)                      not null,
   zhmc                 varchar(120)                    not null,
   zh                   varchar(50)                     not null,
   zjlx                 varchar(2),
   zjhm                 varchar(30),
   djfs                 varchar(2),
   bz                   varchar(3),
   je                   varchar(18),
   dqr                  varchar(8)                         not null,
   djqssj               varchar(14),
   djjssj               varchar(14),
   jgfksj               integer                         not null,
   zxjg                 varchar(1),
   respcode             varchar(8),
   respmsg              varchar(100),
   kh                   varchar(30),
   zxqssj               varchar(14),
   zxjssj               varchar(14),
   fksm                 varchar(300),
   fkjgmc               varchar(150),
   djje                 varchar(20),
   zhye                 varchar(20),
   zxdjje               varchar(20),
   zxdjrq               varchar(12),
   zhkyye               varchar(20),
   zxdjjg               varchar(60),
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_djxj primary key (ywsqbh, rwxh)
);

create table gab_dxzp_jymx  (
   ywsqbh             varchar(36)                     not null,
   rwxh               integer                         not null,
   khyh               varchar(12)                     not null,
   khyhmc             varchar(150),
   zhlb               varchar(2)                      not null,
   zhmc               varchar(120)                    not null,
   zh                 varchar(30)                     not null,
   cxnr               varchar(8),
   cxqsrq             varchar(8),
   cxqssj             varchar(6),
   cxjzrq             varchar(8),
   cxjzsj             varchar(6),
   jgfksj             integer                         not null,
   zxjg               varchar(1),
   respcode           varchar(8),
   respmsg            varchar(100),
   fksm               varchar(300),
   fkjgmc             varchar(150),
   zwrq               varchar(8)                         not null,
   systime            varchar(6)                         not null,
   by1                varchar(30),
   by2                varchar(254),
   by3                varchar(254),
   constraint pkdxzp_jymx primary key (ywsqbh, rwxh)
);

create table gab_dxzp_qhcx  (
   ywsqbh             varchar(36)                     not null,
   rwxh               integer                         not null,
   zhlb               varchar(2)                      not null,
   cxzjlx             varchar(15)                     not null,
   cxzjhm             varchar(30)                     not null,
   zhmc               varchar(150),
   cxnr               varchar(8),
   jgfksj             integer                         not null,
   bankname           varchar(150),
   bankid             varchar(12)                     not null,
   zxjg               varchar(1),
   respcode           varchar(8),
   respmsg            varchar(100),
   fksm               varchar(500),
   fkjgmc             varchar(200),
   zwrq               varchar(8)                         not null,
   systime            varchar(6)                         not null,
   by1                varchar(30),
   by2                varchar(254),
   by3                varchar(254),
   constraint pkdxzp_qhcx primary key (ywsqbh, rwxh)
);

create table gab_dxzp_jjzf  (
   ywsqbh               varchar(36)                     not null,
   rwxh                 integer                         not null,
   yywsqbh              varchar(36),
   sfblc                varchar(2),
   yjbsqbh              varchar(36),
   kh                   varchar(30),
   zczhyh               varchar(12),
   zczhyhmc             varchar(150),
   zczhm                varchar(100),
   zczh                 varchar(30),
   bz                   varchar(3),
   zcje                 varchar(18)                     not null,
   zcrq                 varchar(8)                         not null,
   zcsj                 varchar(6)                         not null,
   khyh                 varchar(12)                     not null,
   khyhmc               varchar(150),
   zhlb                 varchar(2)                      not null,
   zhmc                 varchar(120)                    not null,
   zh                   varchar(50)                     not null,
   dqr                  varchar(8)                         not null,
   jgfksj               integer                         not null,
   zfqssj               varchar(14),
   zfjssj               varchar(14),
   zxjg                 varchar(1),
   respcode             varchar(8),
   respmsg              varchar(100),
   zxqssj               varchar(14),
   zxjssj               varchar(14),
   fksm                 varchar(300),
   fkjgmc               varchar(150),
   zhye                 varchar(20),
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_jjzf primary key (ywsqbh, rwxh)
);

create table gab_dxzp_dtcx  (
   ywsqbh             varchar(36)                     not null,
   rwxh               integer                         not null,
   yywsqbh            varchar(36),
   bz                 varchar(3),
   khyh               varchar(12)                     not null,
   khyhmc             varchar(150),
   zhlb               varchar(2)                      not null,
   zhmc               varchar(120)                    not null,
   kh                 varchar(30),
   zh                 varchar(30)                     not null,
   dtml               varchar(1)                         not null,
   zxqsrq             varchar(14),
   zxjzrq             varchar(14),
   dtcxqssj           varchar(14),
   dtcxjzsj           varchar(14),
   jgfksj             integer                         not null,
   zxjg               varchar(1),
   respcode           varchar(8),
   respmsg            varchar(100),
   fksm               varchar(300),
   fkjgmc             varchar(150),
   zwrq               varchar(8)                         not null,
   systime            varchar(6)                         not null,
   by1                varchar(30),
   by2                varchar(254),
   by3                varchar(254),
   constraint pkdxzp_dtcx primary key (ywsqbh, rwxh)
);

create table gab_dxzp_ycsj  (
   sbpch                varchar(36)                     not null,
   sbpcxh               integer                         not null,
   jybm                 varchar(6),
   csbwlsh              varchar(53),
   ywsqbh               varchar(36),
   ywlx                 varchar(4),
   sjtzm                varchar(4),
   yywsqbh              varchar(36),
   jylsh                varchar(64),
   jysj                 varchar(14),
   jylx                 varchar(20),
   bz                   varchar(3),
   je                   varchar(20),
   zcyhjg               varchar(12),
   zcyhmc               varchar(136),
   zczhhm               varchar(60),
   zczh                 varchar(30),
   ddyhjg               varchar(12),
   ddyhmc               varchar(136),
   ddzhm                varchar(60),
   ddzh                 varchar(30),
   ipdz                 varchar(30),
   mac                  varchar(20),
   sbid                 varchar(20),
   jydd                 varchar(150),
   beiz                 varchar(150),
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_ycsj primary key (sbpch, sbpcxh)
);

create table gab_dxzp_yckk  (
   sbpch                varchar(36)                     not null,
   sbpcxh               integer                         not null,
   jybm                 varchar(6),
   csbwlsh              varchar(53),
   ywsqbh               varchar(36),
   ywlx                 varchar(4),
   sjtzm                varchar(4),
   yywsqbh              varchar(36),
   zjlx                 varchar(2),
   zjhm                 varchar(30),
   xm                   varchar(60),
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_yckk primary key (sbpch, sbpcxh)
);

create table gab_dxzp_sajb  (
   sbpch                varchar(36)                     not null,
   sbpcxh               integer                         not null,
   jybm                 varchar(6),
   csbwlsh              varchar(53),
   ywsqbh               varchar(36),
   jsjgid               varchar(12),
   tgjgbm               varchar(12),
   ywlx                 varchar(4),
   shrxm                varchar(60),
   shrlxdh              varchar(30),
   zjlx                 varchar(2),
   zjhm                 varchar(30),
   sjms                 varchar(300),
   ajjblx               varchar(2),
   zjrq                 varchar(8),
   zjlsh                varchar(32),
   dzxh                 varchar(36),
   yxbz                 varchar(1),
   qqdzt                varchar(2),
   zxjg                 varchar(1),
   respcode             varchar(8),
   respmsg              varchar(100),
   fkdjjzsj             varchar(14),
   cxjg                 varchar(4),
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_sajb primary key (sbpch, sbpcxh)
);

create table gab_dxzp_sazh  (
   sbpch                varchar(36)                     not null,
   sbpcxh               integer                         not null,
   jybm                 varchar(6),
   csbwlsh              varchar(53),
   ywsqbh               varchar(36),
   ywlx                 varchar(4),
   sjtzm                varchar(4),
   yywsqbh              varchar(36),
   kh                   varchar(30),
   zhm                  varchar(120),
   zjlx                 varchar(2),
   zjhm                 varchar(30),
   lxdh                 varchar(30),
   txdz                 varchar(150),
   yzbm                 varchar(10),
   zhlx                 varchar(30),
   zhzt                 varchar(10),
   khrq                 varchar(8),
   xhrq                 varchar(8),
   kkdd                 varchar(20),
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_sazh primary key (sbpch, sbpcxh)
);

create table gab_dxzp_zhsa  (
   jybm                 varchar(6),
   csbwlsh              varchar(53)                     not null,
   ywsqbh               varchar(36)                     not null,
   ywlx                 varchar(4)                      not null,
   zh                   varchar(30)                     not null,
   zhm                  varchar(120)                    not null,
   zt                   varchar(1),
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_zhsa primary key (csbwlsh)
);

create table gab_dxzp_sfsa  (
   jybm                 varchar(6),
   csbwlsh              varchar(53)                     not null,
   ywsqbh               varchar(36)                     not null,
   ywlx                 varchar(4)                      not null,
   zjlx                 varchar(6)                      not null,
   zjhm                 varchar(30)                     not null,
   zhhm                 varchar(120),
   zt                   varchar(1),
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_sfsa primary key (csbwlsh)
);

create table gab_dxzp_zhxx_zhjyxx  (
   ywsqbh             varchar(36)                     not null,
   rwxh               integer                         not null,
   zhxh               varchar(8)                      not null,
   zhjyxh             varchar(4)                      not null,
   jylx               varchar(50),
   jdbz               varchar(1)                      not null,
   bz                 varchar(10)                     not null,
   jyje               varchar(20)                     not null,
   jyye               varchar(20)                     not null,
   jysj               varchar(14)                     not null,
   jylsh              varchar(50)                     not null,
   jydfmc             varchar(60),
   jydfzh             varchar(50),
   jydfzjhm           varchar(30),
   jydfzhkhh          varchar(90),
   jyzy               varchar(150),
   jywdmc             varchar(150)                    not null,
   jywddm             varchar(20)                     not null,
   rzh                varchar(30),
   cph                varchar(30),
   pzzl               varchar(10),
   pzh                varchar(30),
   xjbz               varchar(2)                         not null,
   zdh                varchar(30),
   jysfcg             varchar(2)                         not null,
   jyfsd              varchar(150),
   shmc               varchar(150),
   shh                varchar(30),
   ip                 varchar(30),
   mac                varchar(50),
   jygyh              varchar(20),
   beiz               varchar(150),
   zwrq               varchar(8)                         not null,
   systime            varchar(6)                         not null,
   by1                varchar(30),
   by2                varchar(254),
   by3                varchar(254),
   constraint pkdxzp_zhxx_zhjyxx primary key (ywsqbh, rwxh, zhxh, zhjyxh)
);

create table gab_dxzp_zhjbxx_zhxx  (
   ywsqbh               varchar(36)                     not null,
   rwxh                 integer                         not null,
   zhxh                 varchar(8)                      not null,
   zh                   varchar(50)                     not null,
   zhlx                 varchar(30)                     not null,
   zhzt                 varchar(10)                     not null,
   bz                   varchar(3)                      not null,
   chbz                 varchar(4),
   zhye                 varchar(18)                     not null,
   kyye                 varchar(18)                     not null,
   zhjysj               varchar(14)                        not null,
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_zhjbxx_zhxx primary key (ywsqbh, rwxh, zhxh)
);

create table gab_dxzp_jymx_zhjbxx  (
   ywsqbh             varchar(36)                     not null,
   rwxh               integer                         not null,
   zhm                varchar(120)                    not null,
   kzh                varchar(30),
   khwd               varchar(150)                    not null,
   khwddm             varchar(20)                     not null,
   khrq               varchar(14)                        not null,
   xhrq               varchar(14),
   xhwd               varchar(150),
   beiz               varchar(150),
   zwrq               varchar(8)                         not null,
   systime            varchar(6)                         not null,
   by1                varchar(30),
   by2                varchar(254),
   by3                varchar(254),
   constraint pkdxzp_jymx_zhjbxx primary key (ywsqbh, rwxh)
);

create table gab_dxzp_qhcx_sfqzxx  (
   ywsqbh             varchar(36)                     not null,
   rwxh               integer                         not null,
   csxh               varchar(8)                      not null,
   zh                 varchar(50),
   kh                 varchar(30),
   djksr              varchar(14),
   djjzr              varchar(14),
   djjgmc             varchar(50),
   bz                 varchar(3),
   djje               varchar(20),
   beiz               varchar(1000),
   djcslx             varchar(4),
   zwrq               varchar(8)                         not null,
   systime            varchar(6)                         not null,
   by1                varchar(30),
   by2                varchar(254),
   by3                varchar(254),
   constraint pkdxzp_qhcx_sfqzxx primary key (ywsqbh, rwxh, csxh)
);

create table gab_dxzp_qhcx_zzhxx  (
   ywsqbh             varchar(36)                     not null,
   rwxh               integer                         not null,
   zzhxh              varchar(8)                      not null,
   zh                 varchar(40),
   zzhlb              varchar(30),
   zhzt               varchar(10),
   bz                 varchar(3),
   chbz               varchar(8),
   zhye               varchar(20),
   kyye               varchar(20),
   zhjysj             varchar(14)                        not null,
   zwrq               varchar(8)                         not null,
   systime            varchar(6)                         not null,
   by1                varchar(30),
   by2                varchar(254),
   by3                varchar(254),
   constraint pkdxzp_qhcx_zzhxx primary key (ywsqbh, rwxh, zzhxh)
);

create table gab_dxzp_qhcx_qlxx  (
   ywsqbh             varchar(36)                     not null,
   rwxh               integer                         not null,
   xh                 varchar(8)                      not null,
   zh                 varchar(50),
   kh                 varchar(30),
   zjlx               varchar(15),
   zjhm               varchar(30),
   qllx               varchar(2),
   qlrxm              varchar(60),
   qlje               varchar(20),
   qlrtxdz            varchar(60),
   qlrlxfs            varchar(50),
   zwrq               varchar(8)                         not null,
   systime            varchar(6)                         not null,
   by1                varchar(30),
   by2                varchar(254),
   by3                varchar(254),
   constraint pkdxzp_qhcx_qlxx primary key (ywsqbh, rwxh, xh)
);

create table gab_dxzp_dtcx_resp  (
   sbpch              varchar(36)                     not null,
   sbpcxh             integer                         not null,
   ywsqbh             varchar(36),
   rwxh               integer,
   zhm                varchar(120)                    not null,
   zh                 varchar(50),
   jylx               varchar(50),
   jdbz               varchar(1)                      not null,
   bz                 varchar(3)                      not null,
   jyje               varchar(18)                     not null,
   jyye               varchar(18)                     not null,
   jysj               varchar(14)                        not null,
   jylsh              varchar(50)                     not null,
   jydfmc             varchar(60),
   jydfzh             varchar(30),
   jydfzjhm           varchar(30),
   jydfzhkhh          varchar(60),
   jyzy               varchar(150),
   jywdmc             varchar(150),
   jywddm             varchar(20),
   rzh                varchar(30),
   cph                varchar(30),
   pzzl               varchar(10),
   pzh                varchar(30),
   xjbz               varchar(2)                         not null,
   zdh                varchar(30),
   jysfcg             varchar(2)                         not null,
   jyfsd              varchar(150),
   shmc               varchar(150),
   shh                varchar(30),
   ip                 varchar(30),
   mac                varchar(50),
   jygyh              varchar(20),
   beiz               varchar(150),
   fksm               varchar(300),
   fkjgmc             varchar(150),
   zwrq               varchar(8)                         not null,
   systime            varchar(6)                         not null,
   by1                varchar(30),
   by2                varchar(254),
   by3                varchar(254),
   constraint pkdxzp_dtcx_resp primary key (sbpch, sbpcxh)
);

create table gab_dxzp_dtjc_resp  (
   ywsqbh               varchar(36)                     not null,
   rwxh                 integer                         not null,
   jcdtcxsm             varchar(300),
   fksm                 varchar(150),
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_dtjc_resp primary key (ywsqbh, rwxh)
);

create table gab_dxzp_ztcx_resp  (
   ywsqbh             varchar(36)                     not null,
   rwxh               integer                         not null,
   fkjgmc             varchar(150),
   fksm               varchar(300),
   zjlx               varchar(2)                      not null,
   zjhm               varchar(30)                     not null,
   ztmc               varchar(100)                    not null,
   lxsj               varchar(20)                     not null,
   dbrxm              varchar(60),
   dbrzjlx            varchar(2),
   dbrzjhm            varchar(30),
   zzdz               varchar(150),
   zzdh               varchar(20),
   gzdw               varchar(100),
   dwdz               varchar(150),
   dwdh               varchar(20),
   yxdz               varchar(60),
   frdb               varchar(60),
   frdbzjlx           varchar(2),
   frdbzjhm           varchar(30),
   khgszzhm           varchar(18),
   gsnsh              varchar(20),
   dsnsh              varchar(20),
   zwrq               varchar(8)                         not null,
   systime            varchar(6)                         not null,
   by1                varchar(30),
   by2                varchar(254),
   by3                varchar(254),
   constraint pkdxzp_ztcx_resp primary key (ywsqbh, rwxh)
);

create table gab_dxzp_kzhzh  (
   zh                 varchar(30)                     not null,
   kh                 varchar(30),
   zhmc               varchar(100),
   dccs               integer,
   dczt               varchar(1),
   dcywsqbh           varchar(40),
   dcqssj             varchar(14),
   dcjssj             varchar(14),
   djcs               integer,
   djzt               varchar(1),
   djljje             numeric(18,2),
   djywsqbh           varchar(40),
   djqssj             varchar(14),
   djjssj             varchar(14),
   zfcs               integer,
   zfzt               varchar(1),
   zfljje             numeric(18,2),
   zfywsqbh           varchar(40),
   zfqssj             varchar(14),
   zfjssj             varchar(14),
   khcs               integer,
   khljje             numeric(18,2),
   khywsqbh           varchar(40),
   by1                varchar(32),
   by2                varchar(255),
   by3                varchar(255),
   constraint pkdxzp_kzhzh primary key (zh)
);

create table gab_dxzp_smjfj  (
   ywsqbh               varchar(36)                     not null,
   xh                   integer                         not null,
   wjm                  varchar(254),
   wjdx                 varchar(12),
   yxjz                 varchar(36),
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_smjfj primary key (ywsqbh, xh)
);
