drop table APP_TBXX;

create table APP_TBXX
(
	TELLER			CHAR(30) NOT NULL,
	AUTH_USER_ID		CHAR(30),
	AUTH_PASSWORD		CHAR(30),
	WS_ID			CHAR(30) NOT NULL,
	OPER_FLAG		CHAR(10) NOT NULL,
	STAND_AGREE_NO		CHAR(60) NOT NULL,
	AGREE_NO		CHAR(65) NOT NULL,
	CLIENT_NO		CHAR(20) NOT NULL,
	BOOK_ACCT_NO		CHAR(50),
	AGREE_CODE		CHAR(10),
	SIGN_TYPE		CHAR(9),
	SIGN_NO			CHAR(30),
	SUPER_SIGN_TYPE		CHAR(10),
	SUPER_SIGN_NO		CHAR(30),
	MOBILE			CHAR(30),
	EFFECT_DATE		CHAR(8),
	EXPIRY_DATE		CHAR(8),
	SIGN_DATE		CHAR(8),
	CANCEL_DATE		CHAR(8),
	SIGN_TELLER		CHAR(30),
	CANCEL_TELLER		CHAR(30),
	SIGN_STATUS		CHAR(10),
	EX_REGION_VALUE		VARCHAR(600),
	TIMES			INTEGER,
	ORI_CONSUMER_ID		CHAR(6),
	SIGN_CHANNEL		CHAR(20),
	SIGN_BRANCH_ID		VARCHAR(20),
	REMARK			VARCHAR(300),
	COUNTER_ACCT_NO		VARCHAR(50),
	SIGN_DES		VARCHAR(500),
	STAT			CHAR(2)
	/*constraint PK_APP_TBXX_1 primary key (XYH)*/
);

CREATE INDEX APP_TBXX_IDX1 ON APP_TBXX(AGREE_NO);

comment on table APP_TBXX is
'客户协议同步信息表';

comment on column APP_TBXX.STAT is
'状态 1：已同步 0：未同步';
