CREATE TABLE
    BATCH_FILECHECK_DETAIL
    (
        PKRQ CHARACTER(8) NOT NULL,
        PTPCH CHARACTER(8) NOT NULL,
        LSXH INTEGER NOT NULL,
        WJXH INTEGER NOT NULL,
        JDBZ CHARACTER(1),
        ZYDM CHARACTER(16),
        YWBH CHARACTER(16),
        DWBH CHARACTER(16),
        JLBS CHARACTER(32),
        YHH1 CHARACTER(32),
        YHXM CHARACTER(200),
        ZJHM CHARACTER(32),
        YHZH CHARACTER(32),
        FKRZH CHARACTER(32),
        FKRXM CHARACTER(200),
        FKHHH CHARACTER(12),
        FKHHM CHARACTER(200),
        SKRZH CHARACTER(32),
        SKRXM CHARACTER(200),
        SKHHH CHARACTER(12),
        SKHHM CHARACTER(200),
        JYJE DECIMAL(15,2),
        SJJE DECIMAL(15,2),
        PTLSH CHARACTER(32) NOT NULL,
        YWLSH CHARACTER(32) NOT NULL,
        JYLSH CHARACTER(32) NOT NULL,
        PTDM CHARACTER(32),
        BFKKBZ CHARACTER(1),
        BZ CHARACTER(8),
        GYLSH CHARACTER(32),
        ZWRQ CHARACTER(8),
        CZLSH CHARACTER(32),
        CZRQ CHARACTER(8),
        DJXTRQ CHARACTER(8),
        DJXTSJ CHARACTER(6),
        ZHGXRQ CHARACTER(8),
        ZHGXSJ CHARACTER(6),
        BYZD1 CHARACTER(40),
        BYZD2 CHARACTER(40),
        BYZD3 DECIMAL(15,2),
        BYZD4 INTEGER,
        JLZT CHARACTER(8),
        ZJYXQ CHARACTER(8),
        ZJLX CHARACTER(3),
        XB CHARACTER(1),
        CSRQ CHARACTER(8),
        FZJG CHARACTER(60),
        DZ CHARACTER(120),
        YZBM CHARACTER(7),
        DHHM CHARACTER(15),
        ZY CHARACTER(40),
        GZDW CHARACTER(120),
        SSJMSF CHARACTER(3),
        KXRQ CHARACTER(8),
        YWJE DECIMAL(15,2),
        SJYWJE DECIMAL(15,2),
        FYJE1 DECIMAL(15,2),
        SJFYJE1 DECIMAL(15,2),
        FYJE2 DECIMAL(15,2),
        SJFYJE2 DECIMAL(15,2),
        FYJE3 DECIMAL(15,2),
        SJFYJE3 DECIMAL(15,2),
        FYJE4 DECIMAL(15,2),
        SJFYJE4 DECIMAL(15,2),
        FYJE5 DECIMAL(15,2),
        SJFYJE5 DECIMAL(15,2),
        SXFJE DECIMAL(15,2),
        SJSXFJE DECIMAL(15,2),
        SHZT CHARACTER(1),
        CLZT CHARACTER(1),
        CGBZ CHARACTER(1),
        XYM CHARACTER(8),
        XYXX CHARACTER(60),
        ZJRQ CHARACTER(8),
        ZJSJ CHARACTER(6),
        ZJLSH CHARACTER(32),
        ZJXYM CHARACTER(8),
        ZJXYXX CHARACTER(60),
        DSFRQ CHARACTER(8),
        DSFSJ CHARACTER(6),
        DSFLSH CHARACTER(32),
        DSFXYM CHARACTER(8),
        DSFXYXX CHARACTER(60),
        WBRQ CHARACTER(8),
        WBPCH CHARACTER(32) NOT NULL,
        WBXH INTEGER NOT NULL,
        ZJPCH CHARACTER(32) NOT NULL,
        KZZD1 VARCHAR(100),
        KZZD2 VARCHAR(100),
        KZZD3 VARCHAR(100),
        KZZD4 VARCHAR(100),
        KZZD5 VARCHAR(200),
        KZZD6 VARCHAR(256),
        KZZD7 VARCHAR(512),
        KZZD8 VARCHAR(1024),
        KZZD9 VARCHAR(1024),
        KZZD10 DECIMAL(20,2),
        REMARK1 VARCHAR(1024),
        REMARK2 VARCHAR(1024),
        CONSTRAINT PK_BATCH_FILECHECK_DETAIL_1 PRIMARY KEY (PKRQ, PTPCH, LSXH, WJXH)
    );
COMMENT ON TABLE BATCH_FILECHECK_DETAIL
IS
    '批量代收付业务表';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.PKRQ
IS
    '批扣日期';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.PTPCH
IS
    '平台批次号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.LSXH
IS
    '流水序号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.WJXH
IS
    '文件序号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.JDBZ
IS
    '借贷标志';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.ZYDM
IS
    '摘要代码';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.YWBH
IS
    '业务编号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.DWBH
IS
    '单位编号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.JLBS
IS
    '记录标识';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.YHH1
IS
    '用户号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.YHXM
IS
    '用户姓名';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.ZJHM
IS
    '证件号码';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.YHZH
IS
    '用户帐户';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.FKRZH
IS
    '付款人账号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.FKRXM
IS
    '付款人姓名';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.FKHHH
IS
    '付款行行号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.FKHHM
IS
    '付款行行名';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.SKRZH
IS
    '收款人账号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.SKRXM
IS
    '收款人姓名';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.SKHHH
IS
    '收款行行号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.SKHHM
IS
    '收款行行名';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.JYJE
IS
    '交易金额';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.SJJE
IS
    '实际金额';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.PTLSH
IS
    '平台流水号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.YWLSH
IS
    '业务流水号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.JYLSH
IS
    '交易流水号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.PTDM
IS
    '平台代码';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.BFKKBZ
IS
    '部分扣款标志';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.BZ
IS
    '币种';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.GYLSH
IS
    '柜员流水号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.ZWRQ
IS
    '账务日期';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.CZLSH
IS
    '冲正流水号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.CZRQ
IS
    '冲正日期';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.DJXTRQ
IS
    '登记系统日期';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.DJXTSJ
IS
    '登记系统时间';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.ZHGXRQ
IS
    '最后更新日期';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.ZHGXSJ
IS
    '最后更新时间';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.BYZD1
IS
    '备用字段1';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.BYZD2
IS
    '备用字段2';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.BYZD3
IS
    '备用字段3';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.BYZD4
IS
    '备用字段4';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.JLZT
IS
    '记录状态';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.ZJYXQ
IS
    '证件有效期';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.ZJLX
IS
    '证件类型';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.XB
IS
    '性别';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.CSRQ
IS
    '出生日期';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.FZJG
IS
    '发证机关';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.DZ
IS
    '地址';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.YZBM
IS
    '邮政编码';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.DHHM
IS
    '电话号码';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.ZY
IS
    '职业';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.GZDW
IS
    '工作单位';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.SSJMSF
IS
    '税收居民身份';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.KXRQ
IS
    '款项日期';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.YWJE
IS
    '业务金额';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.SJYWJE
IS
    '实际业务金额';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.FYJE1
IS
    '费用1';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.SJFYJE1
IS
    '实际费用1';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.FYJE2
IS
    '费用2';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.SJFYJE2
IS
    '实际费用2';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.FYJE3
IS
    '费用3';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.SJFYJE3
IS
    '实际费用3';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.FYJE4
IS
    '费用4';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.SJFYJE4
IS
    '实际费用4';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.FYJE5
IS
    '费用5';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.SJFYJE5
IS
    '实际费用5';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.SXFJE
IS
    '手续费金额';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.SJSXFJE
IS
    '实际手续费金额';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.SHZT
IS
    '审核状态';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.CLZT
IS
    '处理状态';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.CGBZ
IS
    '成功标志';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.XYM
IS
    '响应码';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.XYXX
IS
    '响应信息';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.ZJRQ
IS
    '主机日期';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.ZJSJ
IS
    '主机时间';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.ZJLSH
IS
    '主机流水号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.ZJXYM
IS
    '主机响应吗';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.ZJXYXX
IS
    '主机响应信息';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.DSFRQ
IS
    '第三方日期';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.DSFSJ
IS
    '第三方时间';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.DSFLSH
IS
    '第三方流水号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.DSFXYM
IS
    '第三方响应码';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.DSFXYXX
IS
    '第三方响应信息';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.WBRQ
IS
    '外部日期';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.WBPCH
IS
    '外部批次号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.WBXH
IS
    '外部序号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.ZJPCH
IS
    '主机批次号';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.KZZD1
IS
    '扩展字段1';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.KZZD2
IS
    '扩展字段2';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.KZZD3
IS
    '扩展字段3';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.KZZD4
IS
    '扩展字段4';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.KZZD5
IS
    '扩展字段5';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.KZZD6
IS
    '扩展字段6';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.KZZD7
IS
    '扩展字段7';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.KZZD8
IS
    '扩展字段8';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.KZZD9
IS
    '扩展字段9';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.KZZD10
IS
    '扩展字段10';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.REMARK1
IS
    '备用1';
COMMENT ON COLUMN BATCH_FILECHECK_DETAIL.REMARK2
IS
    '备用2';

CREATE INDEX
    BATCH_FILECHECK_DETAIL_IDX1
ON
	BATCH_FILECHECK_DETAIL
    (
        ZJPCH,
        WBXH
    )
    ALLOW REVERSE SCANS;
CREATE INDEX
    BATCH_FILECHECK_DETAIL_IDX2
ON
    BATCH_FILECHECK_DETAIL
    (
        WBPCH,
        WBXH
    )
    ALLOW REVERSE SCANS;
CREATE INDEX
    BATCH_FILECHECK_DETAIL_IDX3
ON
    BATCH_FILECHECK_DETAIL
    (
        PKRQ,
        YWBH
    )
    ALLOW REVERSE SCANS;
CREATE INDEX
    BATCH_FILECHECK_DETAIL_IDX4
ON
    BATCH_FILECHECK_DETAIL
    (
        PKRQ,
        PTPCH,
        SHZT,
        CLZT
    )
    ALLOW REVERSE SCANS;
CREATE INDEX
    BATCH_FILECHECK_DETAIL_IDX5
ON
    BATCH_FILECHECK_DETAIL
    (
        YHZH,
        ZWRQ,
        ZYDM
    )
    ALLOW REVERSE SCANS;