DROP   TABLE  AGENT_KHCPXY_CCXT;
CREATE TABLE  AGENT_KHCPXY_CCXT
    (
        CPDM VARCHAR(16) NOT NULL,
        YWBH VARCHAR(16) NOT NULL,
        QYLX CHARACTER(2) NOT NULL,
        KHLX CHARACTER(2) NOT NULL,
        QYZH VARCHAR(32) NOT NULL,
        KHHM VARCHAR(90) NOT NULL,
        KHSJH VARCHAR(20) NOT NULL,
        KHZJHM VARCHAR(32),
        FRHM VARCHAR(90),
        FRZJHM VARCHAR(32),
        SKDWMC VARCHAR(32),
        SKDWZH VARCHAR(120),
        HYKSRQ CHARACTER(8),
        HYJSRQ CHARACTER(8),
        ZT CHARACTER(2) NOT NULL,
        REQID VARCHAR(50) NOT NULL,
        KZZD1 VARCHAR(50),
        KZZD2 VARCHAR(50),
        CONSTRAINT P_AGENT_KHCPXY_CCXT PRIMARY KEY (REQID)
    );
COMMENT ON TABLE AGENT_KHCPXY_CCXT
IS
    '村财客户协议临时表';
COMMENT ON COLUMN AGENT_KHCPXY_CCXT.CPDM
IS
    '产品代码';
COMMENT ON COLUMN AGENT_KHCPXY_CCXT.YWBH
IS
    '业务编号';
COMMENT ON COLUMN AGENT_KHCPXY_CCXT.QYLX
IS
    '操作类型 0-签约 1-解约 2-修改';
COMMENT ON COLUMN AGENT_KHCPXY_CCXT.KHLX
IS
    '客户类型 0-个人 1-单位';
COMMENT ON COLUMN AGENT_KHCPXY_CCXT.QYZH
IS
    '签约账号';
COMMENT ON COLUMN AGENT_KHCPXY_CCXT.KHHM
IS
    '客户户名';
COMMENT ON COLUMN AGENT_KHCPXY_CCXT.KHSJH
IS
    '客户手机号';
COMMENT ON COLUMN AGENT_KHCPXY_CCXT.FRHM
IS
    '法人户名';
COMMENT ON COLUMN AGENT_KHCPXY_CCXT.FRZJHM
IS
    '法人证件号码';
COMMENT ON COLUMN AGENT_KHCPXY_CCXT.SKDWMC
IS
    '收款单位名称';
COMMENT ON COLUMN AGENT_KHCPXY_CCXT.SKDWZH
IS
    '收款单位账号';
COMMENT ON COLUMN AGENT_KHCPXY_CCXT.HYKSRQ
IS
    '合约开始日期';
COMMENT ON COLUMN AGENT_KHCPXY_CCXT.HYJSRQ
IS
    '合约结束日期';
COMMENT ON COLUMN AGENT_KHCPXY_CCXT.ZT
IS
    '状态 0-初始状态 1-待验证 2-验证失败 3-验证成功';
COMMENT ON COLUMN AGENT_KHCPXY_CCXT.REQID
IS
    '请求ID';
COMMENT ON COLUMN AGENT_KHCPXY_CCXT.KZZD1
IS
    '扩展字段1';
COMMENT ON COLUMN AGENT_KHCPXY_CCXT.KZZD2
IS
    '扩展字段2';

INSERT INTO APP_CPXX (CPDM, CPMC, YYBS, ZBJG, ZBGY, KHJL, YWRQLX, QDKZBZ, JGKZCS, SXFBZ, SFQYBZ, QYMS, XYXLJZ, KKFS, JZSX, DZMS, ZJYYH, ZJZYYH, LSBLTS, PDBLTS, JYFS, RZMS, WHJG, WHGY, WHSJ, EXTFLD1, EXTFLD2, CPZT, SXFTKBZ, PZBD, YWB) VALUES ('0041001', '村财系统批量代收', '003', '00000', '', '', '1', '1', '0', '0', '2', '3', 'K_KHCPQY', '1', '0', '1', '', '', 0, 0, '2', '0', '00000', 'czh', '20170823152817', '', '', '0', null, null, null);
INSERT INTO APP_TXAQXX (LJBS, LJMC, LJLX, DWBH, QDKZ, TXMS, TXDZ, TXDK, FSCS, JSCS, LJJGH, LJGYH, LJZDH, KEY1, KEY2, KEY3, FTPDZ, FTPYH, FTPMM, FTPGZFS, FTPCSFS, FTPZDMS, FTPDFLJ, FTPBDLJ, WHJG, WHGY, WHSJ, EXTFLD1, EXTFLD2, TXZT, QDZT) VALUES ('ccxt', '三资管理平台', '3', 'ccxt', '1', '1', '10.8.208.140', '50042', null, null, null, null, null, 'gapsv4', 'gapsv4', null, '59.37.40.252', 'dgnsdkcs', 'dgnsdkcs123', null, '1', '', '/dgnsdkcs', '/home/gapsv4/file/batch/ccxt', '00000', 'admin', '20180202155758', '6069', '10.8.208.142', '0', null);
INSERT INTO AGENT_CSYS (LB, SRCS, SCCS, MS, KZZD1, KZZD2, KZZD3, KZZD4, KZZD5) VALUES ('CCXT', '701256', 'http://59.37.40.252:8899/rmis/rmis/economy/deduct/callBack.action', '村财文件通知接口访问地址', null, null, null, null, null);
INSERT INTO APP_CSKZ (CSJZ, CSLX, CSTJ, JDM, JDZ, REMARK, JZLX, WHJG, WHGY, WHSJ) VALUES ('K_CCXT_QDBS', '2', '80', '/ccxt/bank_qdbs', '293bb744949deb3f', '村财规定农商行渠道标识', '0', '00000', 'admin', '20171113100322');
