
--创建缓冲池(按照以下比例调整,总大小为内存大小的10%)
CREATE BUFFERPOOL GAPS_BUFFER_32K_0 IMMEDIATE  SIZE 20000 PAGESIZE 32 K @

--创建表空间

--临时表空间(表空间大小不用修改)
--用户临时表空间用于存储已说明的临时表（用 DECLARE GLOBAL TEMPORARY TABLE 语句定义）
CREATE USER TEMPORARY TABLESPACE GAPS_USER_TMPSPACE PAGESIZE 32 K MANAGED BY SYSTEM USING ('/home/gapsinst/gapsdata/GAPS_USER_TEMPSPACE') EXTENTSIZE 256 BUFFERPOOL GAPS_BUFFER_32K_0 @
--系统临时表空间
CREATE SYSTEM TEMPORARY TABLESPACE GAPS_SYS_TMPSPACE PAGESIZE 32 K MANAGED BY SYSTEM USING('/home/gapsinst/gapsdata/GAPS_SYS_TEMPSPACE')  EXTENTSIZE 256 BUFFERPOOL GAPS_BUFFER_32K_0 @

--AGENT表空间
CREATE large TABLESPACE AGENT_DATA  PAGESIZE 32 K MANAGED BY DATABASE  USING  (FILE  '/home/gapsinst/gapsdata/AGENT_DATA'  1024 M) DROPPED TABLE RECOVERY ON EXTENTSIZE 256 BUFFERPOOL GAPS_BUFFER_32K_0 PREFETCHSIZE 256 AUTORESIZE YES @
CREATE large TABLESPACE AGENT_INDEX PAGESIZE 32 K MANAGED BY DATABASE  USING  (FILE  '/home/gapsinst/gapsdata/AGENT_INDEX'  512 M) EXTENTSIZE 256 BUFFERPOOL GAPS_BUFFER_32K_0 PREFETCHSIZE 256 AUTORESIZE YES@
--APP表空间
CREATE large TABLESPACE APP_DATA    PAGESIZE 32 K MANAGED BY DATABASE  USING  (FILE  '/home/gapsinst/gapsdata/APP_DATA'  1024 M)   DROPPED TABLE RECOVERY ON EXTENTSIZE 256 BUFFERPOOL GAPS_BUFFER_32K_0 PREFETCHSIZE 256 AUTORESIZE YES@
CREATE large TABLESPACE APP_INDEX   PAGESIZE 32 K MANAGED BY DATABASE  USING  (FILE  '/home/gapsinst/gapsdata/APP_INDEX'  512 M)   EXTENTSIZE 256 BUFFERPOOL GAPS_BUFFER_32K_0 PREFETCHSIZE 256 AUTORESIZE YES@
