db2 connect to gapsdb user gapsusr using qwer1234
db2 "export to /home/gapsv4/app/sql/app_cpxx.txt of del select * from app_cpxx"
db2 "export to /home/gapsv4/app/sql/app_dwcpxy.txt of del select * from app_dwcpxy"
db2 "export to /home/gapsv4/app/sql/app_dwxx.txt of del select * from app_dwxx"
db2 "export to /home/gapsv4/app/sql/app_jyxx.txt of del select * from app_jyxx where jydm in ('920302', '920003', '700064', '700111')"
db2 "export to /home/gapsv4/app/sql/app_txaqxx.txt of del select * from app_txaqxx"
db2 "export to /home/gapsv4/app/sql/app_yyxx.txt of del select * from app_yyxx where yybs = '003'"
db2 "export to /home/gapsv4/app/sql/ywty_tokeninfo.txt of del select * from ywty_tokeninfo"
db2 "export to /home/gapsv4/app/sql/t_dict.txt of del select * from t_dict where dict_kind in ('yyt_ywlx', 'yxt_ywlx', 'zflx', 'yyt_state', 'yxt_state' )"
db2 "export to /home/gapsv4/app/sql/t_send_server.txt of del select * from t_send_server"
db2 "export to /home/gapsv4/app/sql/app_qdxx.txt of del select * from app_qdxx"
db2 "export to /home/gapsv4/app/sql/t_report.txt of del select * from t_report"
db2 "export to /home/gapsv4/app/sql/t_report_cond.txt of del select * from t_report_cond"
db2 "export to /home/gapsv4/app/sql/t_org.txt of del select * from t_org"
db2 "export to /home/gapsv4/app/sql/yyt_citycode.txt of del select * from yyt_citycode where area_id = '2' "
