#连接数据库
db2 connect to gapsdb user gapsusr using qwer1234

db2 "ALTER TABLE TBL_CK_BDCRXXB DROP COLUMN QUERYCONTENT"
db2 "ALTER TABLE TBL_CK_BDCRXXB DROP COLUMN STARTDATE"
db2 "ALTER TABLE TBL_CK_BDCRXXB DROP COLUMN ENDDATE"
db2 "ALTER TABLE TBL_CK_WJXZBHXXB DROP COLUMN NEWFILENAME1"
db2 "ALTER TABLE TBL_CK_WJXZBHXXB DROP COLUMN NEWFILENAME2"
db2 "ALTER TABLE TBL_CK_WJCFXXB DROP COLUMN RESULTFILE1"
db2 "ALTER TABLE TBL_CK_WJCFXXB DROP COLUMN RESULTFILE2"

db2 "ALTER TABLE TBL_CK_BDCRXXB ADD QUERYCONTENT VARCHAR(10)"
db2 "ALTER TABLE TBL_CK_BDCRXXB ADD STARTDATE VARCHAR(20)"
db2 "ALTER TABLE TBL_CK_BDCRXXB ADD ENDDATE VARCHAR(20)"
db2 "ALTER TABLE TBL_CK_WJXZBHXXB ADD NEWFILENAME1 VARCHAR(64)"
db2 "ALTER TABLE TBL_CK_WJXZBHXXB ADD NEWFILENAME2 VARCHAR(64)"
db2 "ALTER TABLE TBL_CK_WJCFXXB ADD RESULTFILE1 VARCHAR(64)"
db2 "ALTER TABLE TBL_CK_WJCFXXB ADD RESULTFILE2 VARCHAR(64)"

db2 "commit"

db2 "terminate"
