--公积金数据表创建
--企业公积金账户信息表
CREATE
    TABLE TBL_GJJ_DWZH
    (
        DWZH CHARACTER(32) NOT NULL,
        DWMC CHARACTER(100) NOT NULL,
        DWDM CHARACTER(32),
        JCRS INTEGER,
        JCJE DECIMAL(20,2),
        SSZJ CHARACTER(100),
        BZ CHARACTER(100),
        GXRQ CHARACTER(8),
        GXSJ CHARACTER(6),
        STAT CHARACTER(1),
        BY1 CHARACTER(20),
        BY2 CHARACTER(40),
        CONSTRAINT PK_TBL_GJJ_DWZH PRIMARY KEY (DWZH)
    );
COMMENT ON TABLE GAPSUSR.TBL_GJJ_DWZH        IS '企业公积金账户';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_DWZH.DWZH IS '单位公积金账号';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_DWZH.DWMC IS '单位公积金名称';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_DWZH.DWDM IS '单位代码';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_DWZH.JCRS IS '缴存人数';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_DWZH.JCJE IS '缴存金额';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_DWZH.SSZJ IS '所属镇街';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_DWZH.BZ   IS '备注';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_DWZH.GXRQ IS '更新日期';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_DWZH.GXSJ IS '更新时间';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_DWZH.STAT IS '记录状态--0有效，1无效';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_DWZH.BY1  IS '备用1';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_DWZH.BY2  IS '备用2';
    
--公积金过渡账户信息    
CREATE
    TABLE TBL_GJJ_GDZH
    (
        ZHDM CHARACTER(32) NOT NULL,
        ZHMC CHARACTER(100) NOT NULL,
        ZHLX CHARACTER(1) NOT NULL,
        GXRQ CHARACTER(8),
        GXSJ CHARACTER(6),
        STAT CHARACTER(1) NOT NULL,
        BY1  CHARACTER(20),
        BY2  CHARACTER(40),
        CONSTRAINT PK_TBL_GJJ_GDZH PRIMARY KEY (ZHDM)
    );
COMMENT ON TABLE   GAPSUSR.TBL_GJJ_GDZH      IS  '公积金过渡账户信息表';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GDZH.ZHDM IS  '公积金过渡账号    ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GDZH.ZHMC IS  '公积金过渡账户名称';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GDZH.ZHLX IS  '账户类型          ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GDZH.GXRQ IS  '更新日期          ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GDZH.GXSJ IS  '更新时间          ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GDZH.STAT IS  '记录状态          ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GDZH.BY1  IS  '备用1             ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GDZH.BY2  IS  '备用2             ';

--公积金归集流水信息
CREATE
    TABLE TBL_GJJ_GJLS
    (
        PTLS CHARACTER(32) NOT NULL,
        YWLS CHARACTER(32),
        JYRQ CHARACTER(8),
        JYSJ CHARACTER(6),
        JYGY CHARACTER(10),
        SQGY CHARACTER(10),
        DWZH CHARACTER(32),
        DWMC CHARACTER(100),
        GJLX CHARACTER(1),
        WSBJ CHARACTER(1),
        JDBJ CHARACTER(1),
        TKBJ CHARACTER(1),
        KHBJ CHARACTER(2),
        XZBJ CHARACTER(1),
        CBBJ CHARACTER(1),
        FKZH CHARACTER(32),
        FKMC CHARACTER(100),
        FKHH CHARACTER(14),
        FKHM CHARACTER(100),
        SKZH CHARACTER(32),
        SKMC CHARACTER(100),
        SKHH CHARACTER(14),
        SKHM CHARACTER(100),
        JYJE DECIMAL(20,2),
        QRJE DECIMAL(20,2),
        TKJE DECIMAL(20,2),
        JZGY CHARACTER(10),
        GYLS CHARACTER(20),
        ZWRQ CHARACTER(8),
        WHGY CHARACTER(10),
        WHRQ CHARACTER(8),
        WHSJ CHARACTER(6),
        FY CHARACTER(100),
        BZ CHARACTER(100),
        ZYDM CHARACTER(10),
        STAT CHARACTER(1),
        BY1 CHARACTER(20),
        BY2 CHARACTER(40),
        BY3 CHARACTER(60),
        BY4 CHARACTER(100),
        JZZT CHARACTER(1),
        XYDM CHARACTER(12),
        XYXX CHARACTER(150),
        JYJG CHARACTER(12),
        CONSTRAINT PK_TBL_GJJ_GJLS PRIMARY KEY (PTLS)
    );
CREATE INDEX IX_TBL_GJJ_GJLS_PTLS ON GAPSUSR.TBL_GJJ_GJLS(YWLS);
CREATE INDEX IX_TBL_GJJ_GJLS_JYRQ ON GAPSUSR.TBL_GJJ_GJLS(JYRQ,GJLX);
CREATE INDEX IX_TBL_GJJ_GJLS_DWZH ON GAPSUSR.TBL_GJJ_GJLS(DWZH,JYRQ,GJLX);
COMMENT ON TABLE GAPSUSR.TBL_GJJ_GJLS IS '公积金归集流水信息';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.PTLS IS '平台流水号      ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.YWLS IS '业务流水号      ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.JYRQ IS '交易日期        ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.JYSJ IS '交易时间        ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.JYGY IS '交易柜员        ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.SQGY IS '授权柜员        ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.DWZH IS '单位公积金账号  ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.DWMC IS '单位公积金名称  ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.GJLX IS '归集类型--0汇缴、1汇缴确认、2汇缴退回、3外市转出、4外市转出汇款确认、5外市转出退汇、6外市转出重汇、7外市转出撤销';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.WSBJ IS '外市标记--0否、1是';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.JDBJ IS '借贷标记--0借、1贷';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.TKBJ IS '退款标记--0正常、1退款';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.KHBJ IS '跨行标记--0行内、1行外';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.XZBJ IS '现转标记--0现金、1转账';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.CBBJ IS '冲补标记--0正常、1冲补';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.FKZH IS '付款人账号      ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.FKMC IS '付款人名称      ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.FKHH IS '付款人开户行行号';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.FKHM IS '付款人开户行名  ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.SKZH IS '收款人账号      ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.SKMC IS '收款人名称      ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.SKHH IS '收款人开户行行号';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.SKHM IS '收款人开户行名  ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.JYJE IS '交易金额        ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.QRJE IS '已确认金额      ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.TKJE IS '已退款金额      ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.JZGY IS '记账柜员        ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.GYLS IS '柜员财务流水号  ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.ZWRQ IS '账务日期        ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.WHGY IS '维护柜员        ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.WHRQ IS '维护日期        ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.WHSJ IS '维护时间        ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.FY IS '附言            ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.BZ IS '备注            ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.ZYDM IS '摘要代码        ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.STAT IS '记录状态--0待确认、1已确认、4删除、8记账失败、9初始';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.BY1 IS '备用1           ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.BY2 IS '备用2           ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.BY3 IS '备用3           ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.BY4 IS '备用4           ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.JZZT IS '记账状态--0成功、1失败、2待查证、9初始';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.XYDM IS '记账响应码      ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.XYXX IS '记账响应信息    ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_GJLS.JYJG IS '交易机构        ';    


--公积金归集流水操作信息
CREATE
    TABLE TBL_GJJ_LSCZ
    (
        CZLS CHARACTER(32) NOT NULL,
        PTLS CHARACTER(32) NOT NULL,
        GLLS CHARACTER(32),
        CZLX CHARACTER(1),
        JYRQ CHARACTER(8),
        JYSJ CHARACTER(6),
        JYGY CHARACTER(10),
        STAT CHARACTER(1),
        BY1 CHARACTER(20),
        BY2 CHARACTER(40),
        BY3 CHARACTER(40),
        JYJG CHARACTER(12),
        CONSTRAINT PK_TBL_GJJ_LSCZ PRIMARY KEY (CZLS)
    );
CREATE INDEX IX_TBL_GJJ_LSCZ_PTLS ON GAPSUSR.TBL_GJJ_LSCZ(PTLS);
CREATE INDEX IX_TBL_GJJ_LSCZ_GLLS ON GAPSUSR.TBL_GJJ_LSCZ(GLLS);
CREATE INDEX IX_TBL_GJJ_LSCZ_JYRQ ON GAPSUSR.TBL_GJJ_LSCZ(JYRQ);
COMMENT ON TABLE GAPSUSR.TBL_GJJ_LSCZ IS '公积金归集流水操作信息';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_LSCZ.CZLS IS '操作流水';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_LSCZ.PTLS IS '平台流水';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_LSCZ.GLLS IS '关联流水';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_LSCZ.CZLX IS '操作类型--0新增、1维护';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_LSCZ.JYRQ IS '交易日期';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_LSCZ.JYSJ IS '交易时间';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_LSCZ.JYGY IS '交易柜员';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_LSCZ.STAT IS '记录状态--0有效、1无效';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_LSCZ.BY1 IS '备用1   ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_LSCZ.BY2 IS '备用2   ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_LSCZ.BY3 IS '备用3   ';
COMMENT ON COLUMN GAPSUSR.TBL_GJJ_LSCZ.JYJG IS '交易机构        ';
