ALTER TABLE GAPSUSR.TBL_JZZF_BGORGCODE  ALTER COLUMN FINANO SET DATA TYPE VARCHAR ( 200 ) ;
reorg table GAPSUSR.TBL_JZZF_BGORGCODE ;

ALTER TABLE GAPSUSR.TBL_JZZF_BILLNO  ALTER COLUMN FINANO SET DATA TYPE VARCHAR ( 200 ) ;
ALTER TABLE GAPSUSR.TBL_JZZF_BILLNO  ALTER COLUMN bgacccode SET DATA TYPE VARCHAR ( 30 ) ;
ALTER TABLE GAPSUSR.TBL_JZZF_BILLNO  ALTER COLUMN PROJECTCODE SET DATA TYPE VARCHAR ( 30 ) ;
reorg table GAPSUSR.TBL_JZZF_BILLNO ;

ALTER TABLE GAPSUSR.TBL_JZZF_EDHZ  ALTER COLUMN FINANO SET DATA TYPE VARCHAR ( 200 ) ;
reorg table GAPSUSR.TBL_JZZF_EDHZ ;

ALTER TABLE GAPSUSR.TBL_JZZF_EDHZJL  ALTER COLUMN FINANO SET DATA TYPE VARCHAR ( 200 ) ;
reorg table GAPSUSR.TBL_JZZF_EDHZJL ;

ALTER TABLE GAPSUSR.TBL_JZZF_PROJECTCLASSCODE   ALTER COLUMN FINANO SET DATA TYPE VARCHAR ( 200 ) ;
reorg table GAPSUSR.TBL_JZZF_PROJECTCLASSCODE ;

ALTER TABLE GAPSUSR.TBL_JZZF_EDHZJLMX  ALTER COLUMN bgacccode SET DATA TYPE VARCHAR ( 30 ) ;
reorg table GAPSUSR.TBL_JZZF_EDHZJLMX ;

ALTER TABLE GAPSUSR.TBL_JZZF_OUTLAYCODE  ALTER COLUMN FINANO SET DATA TYPE VARCHAR ( 30 ) ;
reorg table GAPSUSR.TBL_JZZF_OUTLAYCODE ;

ALTER TABLE GAPSUSR.TBL_JZZF_EDKZ  ALTER COLUMN PROJECTCODE SET DATA TYPE VARCHAR ( 30 ) ;
ALTER TABLE GAPSUSR.TBL_JZZF_EDKZ  ALTER COLUMN bgacccode SET DATA TYPE VARCHAR ( 30 ) ;
reorg table GAPSUSR.TBL_JZZF_EDKZ ;

ALTER TABLE GAPSUSR.TBL_JZZF_EDMX  ALTER COLUMN PROJECTCODE SET DATA TYPE VARCHAR ( 30 ) ;
ALTER TABLE GAPSUSR.TBL_JZZF_EDMX  ALTER COLUMN bgacccode SET DATA TYPE VARCHAR ( 30 ) ;
reorg table GAPSUSR.TBL_JZZF_EDMX ;

ALTER TABLE GAPSUSR.TBL_JZZF_BGACCCODE ALTER COLUMN bgaccsortcode SET DATA TYPE VARCHAR ( 30 ) ;
ALTER TABLE GAPSUSR.TBL_JZZF_BGACCCODE ALTER COLUMN bgacckindcode SET DATA TYPE VARCHAR ( 30 ) ;
ALTER TABLE GAPSUSR.TBL_JZZF_BGACCCODE ALTER COLUMN bgaccitemcode SET DATA TYPE VARCHAR ( 30 ) ;
ALTER TABLE GAPSUSR.TBL_JZZF_BGACCCODE ALTER COLUMN bgacccode SET DATA TYPE VARCHAR ( 30 ) ;
ALTER TABLE GAPSUSR.TBL_JZZF_BGACCCODE ALTER COLUMN bgcode SET DATA TYPE VARCHAR ( 30 ) ;
reorg table GAPSUSR.TBL_JZZF_BGACCCODE;

ALTER TABLE GAPSUSR.TBL_JZZF_BGDEPTCODE ALTER COLUMN bgcode SET DATA TYPE VARCHAR ( 30 ) ;
ALTER TABLE GAPSUSR.TBL_JZZF_BGDEPTCODE ALTER COLUMN FINANO SET DATA TYPE VARCHAR ( 200 ) ;
reorg table GAPSUSR.TBL_JZZF_BGDEPTCODE; 

ALTER TABLE GAPSUSR.TBL_JZZF_GWKINFO ALTER COLUMN FINANO SET DATA TYPE VARCHAR ( 200 ) ;
reorg table GAPSUSR.TBL_JZZF_GWKINFO ;

ALTER TABLE GAPSUSR.TBL_JZZF_GWKPLHK ALTER COLUMN FINANO SET DATA TYPE VARCHAR ( 200 ) ;
reorg table GAPSUSR.TBL_JZZF_GWKPLHK;

