drop INDEX TBL_JZZF_HXLSLOG_I_KEY1;
DROP TABLE TBL_JZZF_HXLSLOG;

CREATE TABLE TBL_JZZF_HXLSLOG
(
FLOWID VARCHAR(32) NOT NULL,
OPERTYPE VARCHAR(1)NOT NULL,
ISSUM VARCHAR(1) NOT NULL,
RZRQ VARCHAR(9)NOT NULL,
RZGYLS VARCHAR(12)NOT NULL,
SEQNO VARCHAR(9)NOT NULL,
AMT DECIMAL(16,2)NOT NULL,
TRANDATE VARCHAR(8)NOT NULL,
TRANTIME VARCHAR(6)NOT NULL
);


CREATE INDEX TBL_JZZF_HXLSLOG_I_KEY1 ON TBL_JZZF_HXLSLOG(RZRQ,RZGYLS);
COMMENT ON TABLE  TBL_JZZF_HXLSLOG  IS '核心流水拆分/合并登记表' ;
COMMENT ON COLUMN TBL_JZZF_HXLSLOG.FLOWID		IS	'业务流水' ; 
COMMENT ON COLUMN TBL_JZZF_HXLSLOG.OPERTYPE   	IS	'操纵类型(0拆分、1合并)';
COMMENT ON COLUMN TBL_JZZF_HXLSLOG.ISSUM  	IS	'汇总标记(0否、1是)';
COMMENT ON COLUMN TBL_JZZF_HXLSLOG.RZRQ  	IS	'入账日期' ;
COMMENT ON COLUMN TBL_JZZF_HXLSLOG.RZGYLS 	IS	'入账柜员流水' ;
COMMENT ON COLUMN TBL_JZZF_HXLSLOG.SEQNO   	IS	'序号' ;
COMMENT ON COLUMN TBL_JZZF_HXLSLOG.AMT   	IS	'金额' ;
COMMENT ON COLUMN TBL_JZZF_HXLSLOG.TRANDATE   	IS	'交易日期' ;
COMMENT ON COLUMN TBL_JZZF_HXLSLOG.TRANTIME   	IS	'交易时间' ;
