DROP TABLE TBL_JZZF_HXDWLS_TMP;
CREATE TABLE TBL_JZZF_HXDWLS_TMP
(
ZBJG VARCHAR(11) NOT NULL,
KHJG VARCHAR(11) NOT NULL,
SRZH VARCHAR(33) NOT NULL,
JFJGH VARCHAR(15),
JFYHZH VARCHAR(33),
JFHM VARCHAR(101),
DJJGH VARCHAR(15),
DFYHZH VARCHAR(32),
DFHM        VARCHAR(100),
RZRQ VARCHAR(9) NOT NULL,
RZSJ VARCHAR(7) NOT NULL,
RZGYLSH VARCHAR(12) NOT NULL,
JDBZ VARCHAR(1) NOT NULL,
FSE DECIMAL(16,2) NOT NULL,
JSFS VARCHAR(1),
JSLS VARCHAR(36),
FY VARCHAR(63),
BZ VARCHAR(41),
SEQNO VARCHAR(9) NOT NULL,
ZZHXH VARCHAR(61) NOT NULL,
JFJGM VARCHAR(61),
DFJGM VARCHAR(61),
SENDFLAG VARCHAR(1),

CONSTRAINT PK_HXDWLS_TMP PRIMARY KEY(RZRQ, RZGYLSH, SEQNO)
);
CREATE INDEX TBL_JZZF_HXDWLS_TMP_I_KEY1 ON TBL_JZZF_HXDWLS_TMP(ZBJG, RZRQ);
COMMENT ON TABLE  TBL_JZZF_HXDWLS_TMP  IS '核心单位收入流水' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.ZBJG		IS	'主办结构' ; 
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.KHJG   	IS	'开户机构' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.SRZH  	IS	'财政收入账户  ' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.JFJGH  	IS	'借方机构号' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.JFYHZH 	IS	'借方银行账号' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.JFHM   	IS	'借方户名' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.DJJGH  	IS	'贷方机构号  ' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.DFYHZH 	IS	'贷方银行账号' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.DFHM   	IS	'贷方户名' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.RZRQ   	IS	'入账日期' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.RZSJ   	IS	'入账时间' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.RZGYLSH	IS	'入账柜员流水' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.JDBZ   	IS	'借贷标记' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.FSE    	IS	'发生额' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.JSFS   	IS	'结算方式' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.JSLS   	IS	'结算流水' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.FY     	IS	'附言' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.BZ     	IS	'备注' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.SEQNO  	IS	'流水序号' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.ZZHXH   IS	'子账户序号' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.JFJGM   IS	'借方机构名' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.DFJGM   IS	'贷方机构名' ;
COMMENT ON COLUMN TBL_JZZF_HXDWLS_TMP.SENDFLAG   IS	'发送标识' ;

