DROP TABLE TBL_JZZF_SRZZH;
CREATE TABLE TBL_JZZF_SRZZH
(
CZBM VARCHAR(12) NOT NULL,
SRZH VARCHAR(32) NOT NULL,
SRZHMC VARCHAR(100) NOT NULL,
INCOMETYPE VARCHAR(2) NOT NULL,
ZZHXH VARCHAR(12) NOT NULL,
ZZHMC VARCHAR(100) NOT NULL,
BGDEPTCODE VARCHAR(12) NOT NULL,
WHRY VARCHAR(12),
WHRQ VARCHAR(10),
STAT VARCHAR(1) NOT NULL,
BY1        VARCHAR(20),
BY2 VARCHAR(40),
CONSTRAINT PK_SRZZH PRIMARY KEY(SRZH, ZZHXH)
);
COMMENT ON TABLE  TBL_JZZF_SRZZH  IS '收入子账户信息' ;
COMMENT ON COLUMN TBL_JZZF_SRZZH.CZBM		IS	'财政编码    ' ; 
COMMENT ON COLUMN TBL_JZZF_SRZZH.SRZH   	IS	'单位账号    ' ;
COMMENT ON COLUMN TBL_JZZF_SRZZH.SRZHMC  	IS	'单位账户名称  ' ;
COMMENT ON COLUMN TBL_JZZF_SRZZH.INCOMETYPE  	IS	'收入类型:1.预算收入2.非税收入3.代管资金收入' ;
COMMENT ON COLUMN TBL_JZZF_SRZZH.ZZHXH  	IS	'子账号  ' ;
COMMENT ON COLUMN TBL_JZZF_SRZZH.ZZHMC 	IS	'子账户名称' ;
COMMENT ON COLUMN TBL_JZZF_SRZZH.BGDEPTCODE IS '单位代码';
COMMENT ON COLUMN TBL_JZZF_SRZZH.WHRY   	IS	'维护人员    ' ;
COMMENT ON COLUMN TBL_JZZF_SRZZH.WHRQ  	IS	'维护日期  ' ;
COMMENT ON COLUMN TBL_JZZF_SRZZH.STAT 	IS	'状态' ;
COMMENT ON COLUMN TBL_JZZF_SRZZH.BY1   	IS	'备用1    ' ;
COMMENT ON COLUMN TBL_JZZF_SRZZH.BY2   	IS	'备用2    ' ;

