DROP TABLE  COUPON_COUPON;
DROP TABLE  COUPON_COUPONDETAIL;
DROP TABLE  COUPON_COUPONPROVIDER;
DROP TABLE  COUPON_COUPONTRADER;
DROP TABLE  COUPON_ORDER;
DROP TABLE  COUPON_DZBPB;
DROP TABLE  COUPON_WIAMP_DZLSB;
DROP TABLE  COUPON_ZJYW_DZLSB;
DROP TABLE  COUPON_ZJYW_RZZT;

CREATE TABLE    COUPON_COUPON
    (
        COUPONNO VARCHAR(128) NOT NULL,
        COUPONNAME VARCHAR(128),
        COUPONAMT DECIMAL(15,2),
        COUPONTYPE VARCHAR(32),
        COUPONSRC VARCHAR(128),
        COUPONVALUE DECIMAL(15,2),
        COUPONDESC VARCHAR(256),
        COUPONPRIZE DECIMAL(15,2),
        COUPONNUM INTEGER,
        COUPONSTATUS VARCHAR(2) NOT NULL,
        TRADERNO VARCHAR(64),
        EFFECTDAY INTEGER,
        CONSTRAINT PK_COUPON_COUPON PRIMARY KEY (COUPONNO)
    )IN AGENT_DATA INDEX IN AGENT_INDEX;
COMMENT ON TABLE COUPON_COUPON IS      '卡券产品登记簿';
COMMENT ON COLUMN COUPON_COUPON.COUPONNO IS      '卡券编号';
COMMENT ON COLUMN COUPON_COUPON.COUPONNAME IS      '卡券名称';
COMMENT ON COLUMN COUPON_COUPON.COUPONAMT IS      '卡券金额';
COMMENT ON COLUMN COUPON_COUPON.COUPONTYPE IS      '卡券类型';
COMMENT ON COLUMN COUPON_COUPON.COUPONSRC IS      '卡券图片';
COMMENT ON COLUMN COUPON_COUPON.COUPONVALUE IS      '卡券面值';
COMMENT ON COLUMN COUPON_COUPON.COUPONDESC IS      '卡券使用说明';
COMMENT ON COLUMN COUPON_COUPON.COUPONPRIZE IS      '卡券协议价格';
COMMENT ON COLUMN COUPON_COUPON.COUPONNUM IS      '卡券数量';
COMMENT ON COLUMN COUPON_COUPON.COUPONSTATUS IS      '卡券状态 0-下架 1-上架 2-已删除';
COMMENT ON COLUMN COUPON_COUPON.TRADERNO IS      '商户编号';

CREATE TABLE    COUPON_COUPONDETAIL
    (
        SEQNO VARCHAR(10) NOT NULL,
        COUPONNO VARCHAR(128) NOT NULL,
        COUPONCODE VARCHAR(64) NOT NULL,
        EFFECTDATE VARCHAR(20),
        ENDDATE VARCHAR(20),
        STATUS VARCHAR(2) NOT NULL,
        CHANGEORDERNO VARCHAR(128) NOT NULL,
        COUPONREMARK VARCHAR(256),
        QRCODEURL VARCHAR(256),
        BARCODEURL VARCHAR(256),
        BARANDQRURL VARCHAR(256),
        CONSTRAINT PK_COUPON_COUPONDETAIL PRIMARY KEY (SEQNO, COUPONNO, COUPONCODE, CHANGEORDERNO)
    )IN AGENT_DATA INDEX IN AGENT_INDEX;
COMMENT ON TABLE COUPON_COUPONDETAIL  IS        '卡券详细信息登记簿';
COMMENT ON COLUMN COUPON_COUPONDETAIL.SEQNO  IS        '序号';
COMMENT ON COLUMN COUPON_COUPONDETAIL.COUPONNO  IS        '卡券编号';
COMMENT ON COLUMN COUPON_COUPONDETAIL.COUPONCODE  IS        '卡券码';
COMMENT ON COLUMN COUPON_COUPONDETAIL.EFFECTDATE  IS        '生效日期';
COMMENT ON COLUMN COUPON_COUPONDETAIL.ENDDATE  IS        '失效日期';
COMMENT ON COLUMN COUPON_COUPONDETAIL.STATUS  IS        '卡券状态 0-尚未分配 1-分配未接收 2-分配已接收  *-无效,过期,作废';
COMMENT ON COLUMN COUPON_COUPONDETAIL.CHANGEORDERNO  IS        '换购订单号';
COMMENT ON COLUMN COUPON_COUPONDETAIL.COUPONREMARK  IS        '附加内容';
COMMENT ON COLUMN COUPON_COUPONDETAIL.QRCODEURL  IS        '二维码短链接';
COMMENT ON COLUMN COUPON_COUPONDETAIL.BARCODEURL  IS        '条形码短链接';
COMMENT ON COLUMN COUPON_COUPONDETAIL.BARANDQRURL  IS        '组合码短链接';


CREATE TABLE    COUPON_COUPONPROVIDER
    (
        PROVIDERNO VARCHAR(64) NOT NULL,
        PROVIDERNAME VARCHAR(64) NOT NULL,
        CREATEDATE INTEGER,
        STATUS VARCHAR(2) NOT NULL,
        CONSTRAINT PK_COUPONPROVIDER PRIMARY KEY (PROVIDERNAME)
    )IN AGENT_DATA INDEX IN AGENT_INDEX;
COMMENT ON TABLE COUPON_COUPONPROVIDER  IS        '供应商登记簿';
COMMENT ON COLUMN COUPON_COUPONPROVIDER.PROVIDERNO  IS        '供应商编号';
COMMENT ON COLUMN COUPON_COUPONPROVIDER.PROVIDERNAME  IS        '供应商名';
COMMENT ON COLUMN COUPON_COUPONPROVIDER.CREATEDATE  IS        '供应商创建日期';
COMMENT ON COLUMN COUPON_COUPONPROVIDER.STATUS  IS        '状态  0-有效  *-无效';


CREATE TABLE    COUPON_COUPONTRADER
    (
        TRADERNO VARCHAR(64) NOT NULL,
        TRADERNAME VARCHAR(128) NOT NULL,
        TRADERTYPE VARCHAR(64) NOT NULL,
        TRADERADDRESS VARCHAR(256),
        PROVIDERNO VARCHAR(128),
        REMARK VARCHAR(128),
        LOGOSRC VARCHAR(256),
        STATUS VARCHAR(2) NOT NULL,
        PROVIDERNAME VARCHAR(64),
        BACKDROPSRC VARCHAR(256),
        CONSTRAINT PK_COUPONTRADER PRIMARY KEY (TRADERNO)
    )IN AGENT_DATA INDEX IN AGENT_INDEX;
COMMENT ON TABLE COUPON_COUPONTRADER  IS        '商户登记簿';
COMMENT ON COLUMN COUPON_COUPONTRADER.TRADERNO  IS        '商户编号';
COMMENT ON COLUMN COUPON_COUPONTRADER.TRADERNAME  IS        '商户名称';
COMMENT ON COLUMN COUPON_COUPONTRADER.TRADERTYPE  IS        '商户类型';
COMMENT ON COLUMN COUPON_COUPONTRADER.TRADERADDRESS  IS        '商户地址';
COMMENT ON COLUMN COUPON_COUPONTRADER.PROVIDERNO  IS        '供应商编号';
COMMENT ON COLUMN COUPON_COUPONTRADER.REMARK  IS        '备注';
COMMENT ON COLUMN COUPON_COUPONTRADER.LOGOSRC  IS        'LOGO';
COMMENT ON COLUMN COUPON_COUPONTRADER.STATUS  IS        '状态 0-有效 *-无效';


CREATE TABLE    COUPON_DZBPB
    (
        PTRQ VARCHAR(8) NOT NULL,
        DZRQ VARCHAR(8) NOT NULL,
        CHANGEORDERNO VARCHAR(128) NOT NULL,
        WEIORDERNO VARCHAR(128) NOT NULL,
        COUPONNO VARCHAR(128) NOT NULL,
        STATUS VARCHAR(2) NOT NULL,
        WIAMP_ORDERNUM INTEGER NOT NULL,
        ZJYW_ORDERNUM INTEGER NOT NULL,
        EXTFLD1 VARCHAR(20),
        EXTFLD2 VARCHAR(20),
        CONSTRAINT PK_COUPON_DZBPB PRIMARY KEY (PTRQ, DZRQ, CHANGEORDERNO)
    )IN AGENT_DATA INDEX IN AGENT_INDEX;
COMMENT ON TABLE COUPON_DZBPB  IS        '卡券对账不平表';
COMMENT ON COLUMN COUPON_DZBPB.PTRQ  IS        '平台日期';
COMMENT ON COLUMN COUPON_DZBPB.DZRQ  IS        '对账日期';
COMMENT ON COLUMN COUPON_DZBPB.CHANGEORDERNO  IS        '换购订单号';
COMMENT ON COLUMN COUPON_DZBPB.WEIORDERNO  IS        '微能订单号';
COMMENT ON COLUMN COUPON_DZBPB.COUPONNO  IS        '批次号';
COMMENT ON COLUMN COUPON_DZBPB.STATUS  IS        '状态 1-卡券平台多、2-中间业务多、3-卡券数量不符';
COMMENT ON COLUMN COUPON_DZBPB.WIAMP_ORDERNUM  IS        '卡券平台多卡券数量';
COMMENT ON COLUMN COUPON_DZBPB.ZJYW_ORDERNUM  IS        '中间业务多卡券数量';


CREATE TABLE    COUPON_ORDER
    (
        ORDERNO VARCHAR(128) NOT NULL,
        CHANGEORDERNO VARCHAR(128) NOT NULL,
        WEIORDERNO VARCHAR(128),
        ORDERNUM INTEGER,
        ORDERDATE VARCHAR(20),
        COUPONNO VARCHAR(128) NOT NULL,
        GETCHNL VARCHAR(32),
        FORWARDCHNL VARCHAR(32),
        CANCELCHNL VARCHAR(32),
        GETTIME VARCHAR(20),
        FORWARDTIME VARCHAR(20),
        CANCELTIME VARCHAR(20),
        ORDERSTATUS VARCHAR(2),
        FORWARDSTATUS VARCHAR(2),
        RETURNCODE VARCHAR(8)
    )IN AGENT_DATA INDEX IN AGENT_INDEX;
COMMENT ON TABLE COUPON_ORDER  IS        '采购订单登记簿';
COMMENT ON COLUMN COUPON_ORDER.ORDERNO  IS        '订单号';
COMMENT ON COLUMN COUPON_ORDER.CHANGEORDERNO  IS        '换购订单号,对应一个采购批次';
COMMENT ON COLUMN COUPON_ORDER.WEIORDERNO  IS        '微能订单号';
COMMENT ON COLUMN COUPON_ORDER.ORDERNUM  IS        '订单卡券数量';
COMMENT ON COLUMN COUPON_ORDER.ORDERDATE  IS        '订单创建日期';
COMMENT ON COLUMN COUPON_ORDER.COUPONNO  IS        '卡券编号';
COMMENT ON COLUMN COUPON_ORDER.GETCHNL  IS        '采购渠道';
COMMENT ON COLUMN COUPON_ORDER.FORWARDCHNL  IS        '分配渠道';
COMMENT ON COLUMN COUPON_ORDER.CANCELCHNL  IS        '作废渠道';
COMMENT ON COLUMN COUPON_ORDER.GETTIME  IS        '采购时间';
COMMENT ON COLUMN COUPON_ORDER.FORWARDTIME  IS        '分配时间';
COMMENT ON COLUMN COUPON_ORDER.CANCELTIME  IS        '作废时间';
COMMENT ON COLUMN COUPON_ORDER.ORDERSTATUS  IS        '订单状态 0-有效 ';
COMMENT ON COLUMN COUPON_ORDER.FORWARDSTATUS  IS        '分配状态 0-尚未分配 1-已分配';
COMMENT ON COLUMN COUPON_ORDER.RETURNCODE  IS        '采购返回代码';


CREATE TABLE    COUPON_WIAMP_DZLSB
    (
        DZRQ VARCHAR(8) NOT NULL,
        CHANGEORDERNO VARCHAR(128) NOT NULL,
        WEIORDERNO VARCHAR(128) NOT NULL,
        BUSSES_ID VARCHAR(20),
        COUPONNO VARCHAR(128) NOT NULL,
        USER_ID VARCHAR(20),
        COUPONNUM INTEGER NOT NULL,
        GETTIME VARCHAR(20),
        COUPONPRIZE DECIMAL(15,2),
        ORDERSTATUS VARCHAR(1) NOT NULL,
        CONSTRAINT PK_COUPON_WIAMP_DZLSB PRIMARY KEY (DZRQ, CHANGEORDERNO)
    )IN AGENT_DATA INDEX IN AGENT_INDEX;
COMMENT ON TABLE COUPON_WIAMP_DZLSB  IS        '卡券平台对账文件明细表';
COMMENT ON COLUMN COUPON_WIAMP_DZLSB.DZRQ  IS        '对账日期';
COMMENT ON COLUMN COUPON_WIAMP_DZLSB.CHANGEORDERNO  IS        '换购订单号';
COMMENT ON COLUMN COUPON_WIAMP_DZLSB.WEIORDERNO  IS        '微能订单号';
COMMENT ON COLUMN COUPON_WIAMP_DZLSB.BUSSES_ID  IS        '商户ID';
COMMENT ON COLUMN COUPON_WIAMP_DZLSB.COUPONNO  IS        '批次号';
COMMENT ON COLUMN COUPON_WIAMP_DZLSB.USER_ID  IS        '用户标识';
COMMENT ON COLUMN COUPON_WIAMP_DZLSB.COUPONNUM  IS        '卡券数量';
COMMENT ON COLUMN COUPON_WIAMP_DZLSB.GETTIME  IS        '交易时间';
COMMENT ON COLUMN COUPON_WIAMP_DZLSB.COUPONPRIZE  IS        '价格';
COMMENT ON COLUMN COUPON_WIAMP_DZLSB.ORDERSTATUS  IS        '订单状态';


CREATE TABLE    COUPON_ZJYW_DZLSB
    (
        DZRQ VARCHAR(8) NOT NULL,
        CHANGEORDERNO VARCHAR(128) NOT NULL,
        WEIORDERNO VARCHAR(128) NOT NULL,
        COUPONNO VARCHAR(128) NOT NULL,
        COUPONNUM INTEGER NOT NULL,
        GETTIME VARCHAR(20),
        COUPONPRIZE DECIMAL(15,2),
        ORDERSTATUS VARCHAR(2) NOT NULL,
        CONSTRAINT PK_COUPON_ZJYW_DZLSB PRIMARY KEY (DZRQ, CHANGEORDERNO)
    )IN AGENT_DATA INDEX IN AGENT_INDEX;
COMMENT ON TABLE COUPON_ZJYW_DZLSB  IS        '中间业务平台卡券对账明细表';
COMMENT ON COLUMN COUPON_ZJYW_DZLSB.DZRQ  IS        '对账日期';
COMMENT ON COLUMN COUPON_ZJYW_DZLSB.CHANGEORDERNO  IS        '换购订单号';
COMMENT ON COLUMN COUPON_ZJYW_DZLSB.WEIORDERNO  IS        '微能订单号';
COMMENT ON COLUMN COUPON_ZJYW_DZLSB.COUPONNO  IS        '批次号';
COMMENT ON COLUMN COUPON_ZJYW_DZLSB.COUPONNUM  IS        '卡券数量';
COMMENT ON COLUMN COUPON_ZJYW_DZLSB.GETTIME  IS        '交易时间';
COMMENT ON COLUMN COUPON_ZJYW_DZLSB.COUPONPRIZE  IS        '价格';
COMMENT ON COLUMN COUPON_ZJYW_DZLSB.ORDERSTATUS  IS        '订单状态';


CREATE TABLE    COUPON_ZJYW_RZZT
    (
        PTRQ VARCHAR(8) NOT NULL,
        DZRQ VARCHAR(8) NOT NULL,
        STATUS VARCHAR(2) NOT NULL,
        WIAMP_ZBS INTEGER NOT NULL,
        ZJYW_ZBS INTEGER NOT NULL,
        EXTFLD1 VARCHAR(20),
        EXTFLD2 VARCHAR(20),
        CONSTRAINT PK_COUPON_ZJYW_RZZT PRIMARY KEY (PTRQ, DZRQ)
    )IN AGENT_DATA INDEX IN AGENT_INDEX;
COMMENT ON TABLE COUPON_ZJYW_RZZT  IS        '卡券对账汇总表';
COMMENT ON COLUMN COUPON_ZJYW_RZZT.PTRQ  IS        '平台日期';
COMMENT ON COLUMN COUPON_ZJYW_RZZT.DZRQ  IS        '对账日期';
COMMENT ON COLUMN COUPON_ZJYW_RZZT.STATUS  IS        '状态 0-对账平 1-卡券平台多、2-中间业务多、3-卡券数量不符';
COMMENT ON COLUMN COUPON_ZJYW_RZZT.WIAMP_ZBS  IS        '卡券平台总笔数';
COMMENT ON COLUMN COUPON_ZJYW_RZZT.ZJYW_ZBS  IS        '中间业务总笔数';
