--支付网关对账数据表
DROP TABLE YWTY_ZFWG_DZ;
create table YWTY_ZFWG_DZ
(
   JYSX                 VARCHAR(4) NOT NULL,
   QSRQ                 VARCHAR(8) NOT NULL,
   TRAN_TIME            VARCHAR(14) NOT NULL,
   ORDER_NO             VARCHAR(32) NOT NULL,
   Merchant_SEQ         VARCHAR(32) NOT NULL,
   Merchant_Id          VARCHAR(19) NOT NULL,
   TRAN_AMT             DECIMAL(20,2) NOT NULL,
   SXF_AMT              DECIMAL(20,2) NOT NULL,
   QSJE_AMT             DECIMAL(20,2) NOT NULL,
   RESPCODE             VARCHAR(8) NOT NULL,
   REMARK1              VARCHAR(32) NOT NULL,
   REMARK2              VARCHAR(32) ,
   DZ_FLAG              VARCHAR(1) ,
   constraint P_YWTY_ZFWG_DZ primary key (QSRQ, Merchant_SEQ)
)--IN GAPS_DATA INDEX IN GAPS_INDEX 
;

CREATE INDEX YWTY_ZFWG_DZ_I_KEY1 ON YWTY_ZFWG_DZ(QSRQ,ORDER_NO);
COMMENT ON TABLE  YWTY_ZFWG_DZ  IS '支付网关对账数据表';
COMMENT ON COLUMN YWTY_ZFWG_DZ.JYSX IS'交易缩写';
COMMENT ON COLUMN YWTY_ZFWG_DZ.QSRQ IS'清算日期';
COMMENT ON COLUMN YWTY_ZFWG_DZ.TRAN_TIME IS'交易发生时间';
COMMENT ON COLUMN YWTY_ZFWG_DZ.ORDER_NO IS'订单号';
COMMENT ON COLUMN YWTY_ZFWG_DZ.Merchant_SEQ IS'第三方统一支付平台流水号';
COMMENT ON COLUMN YWTY_ZFWG_DZ.Merchant_Id IS'商户号';
COMMENT ON COLUMN YWTY_ZFWG_DZ.TRAN_AMT IS'交易金额';
COMMENT ON COLUMN YWTY_ZFWG_DZ.SXF_AMT IS'手续费';
COMMENT ON COLUMN YWTY_ZFWG_DZ.QSJE_AMT iS'净清算金额';
COMMENT ON COLUMN YWTY_ZFWG_DZ.RESPCODE IS'响应吗';
COMMENT ON COLUMN YWTY_ZFWG_DZ.REMARK1 IS'商户保留1';
COMMENT ON COLUMN YWTY_ZFWG_DZ.REMARK2 IS'商户保留2';
COMMENT ON COLUMN YWTY_ZFWG_DZ.DZ_FLAG IS'对账标识:1-参与对账 0-不参与对账';
