drop table ywty_drls;

--==============================================================
-- {$Id: ywty_drls_syb.sql 2219 2013-01-25 07:20:11Z tianhc $}
-- Table: ywty_drls for Sybase 必须要显式声明为允许null
--==============================================================
create table ywty_drls
(
   zwrq                 char(8)                not null,
   zhqzlsh              integer                not null,
   zxlsh                char(16)               null,
   dsfzwrq              char(8)               null,
   dsflsh               char(18)               null,
   jygzh                char(12)               null,
   zhqzlsh2             integer               null,
   sqm                  char(6)               null,
   sqczy                char(8)               null,
   sjjgbh               char(16)               null,
   jgbh                 char(16)               not null,
   nbjgbs               char(24)               null,
   wtjgbh               char(16)               null,
   wtnbjgbs             char(24)               null,
   czyh                 char(8)                not null,
   jdbh                 char(16)               null,
   jyqd                 char(12)               null,
   jyrq                 char(8)                not null,
   jysj                 char(6)                not null,
   jydm                 char(50)               null,
   jymc                 char(50)               null,
   ywdm                 char(10)               null,
   xmdh                 char(10)               null,
   khmc                 char(80)               null,
   jyzh                 char(32)               null,
   zhzl                 char(2)               null,
   jyzh2                char(32)               null,
   zhzl2                char(2)               null,
   zhjg2                char(32)               null,
   khh                  char(20)               null,
   yhh                  char(32)               null,
   bzh                  char(2)               null,
   jyje                 numeric(16,2)               null,
   sxf                  numeric(16,2)               null,
   gbf                  numeric(16,2)               null,
   znj                  numeric(16,2)               null,
   jyzt                 char(1)                not null,
   xym                  char(8)               null,
   xyxx                 char(60)               null,
   jyfs                 char(1)               null,
   jdbz                 char(1)               null,
   gdbz                 char(1)               null,
   jyzl                 char(1)               null,
   jzbz                 char(1)               null,
   qsbz                 char(1)               null,
   kzbz                 char(8)               null,
   wbzwbs               char(20)               null,
   trans_time           integer               null,
   byzd                 char(128)               null,
   constraint pk_ywty_drls primary key (zwrq, zhqzlsh)
);
