drop table gab_dxzp_sbxx_glzhxx;
drop table gab_dxzp_hhmd;
drop table gab_dxzp_zhxx_zhjyxx ;
drop table gab_dxzp_zhjbxx_zhxx ;
drop table gab_dxzp_qhcx_zzhxx ;
drop table gab_dxzp_sbxx_zhjyxx ;
drop table gab_dxzp_sf_szh ;
create table gab_dxzp_sbxx_glzhxx  (
   sbpch                varchar(36)                     not null,
   sbpcxh               integer                         not null,
   zhxh                 integer                         not null,
   jybm                 varchar(6),
   csbwlsh              varchar(53),
   ywsqbh               varchar(36),
   zh                   varchar(30),
   zhlx                 varchar(30),
   zhzt                 varchar(10),
   bz                   varchar(3),
   chbz                 varchar(10),
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_sbxx_glzhxx primary key (sbpch, sbpcxh, zhxh)
);
create table gab_dxzp_hhmd  (
   mdjz               varchar(70)                     not null,
   yhbh               varchar(12),
   mdlx               varchar(45),
   fsjgbm             varchar(12),
   hhbz               varchar(1),
   ajlx               varchar(12),
   xm                 varchar(180),
   galxr              varchar(60),
   galxdh             varchar(20),
   gashtgsj           varchar(14),
   kksj               varchar(14),
   yxq                varchar(30),
   mdsm               varchar(225),
   zwrq               varchar(8)                         not null,
   systime            varchar(6)                         not null,
   by1                varchar(254),
   by2                varchar(254),
   by3                varchar(254),
   constraint pkdxzp_hhmd primary key (mdjz)
);
create table gab_dxzp_zhxx_zhjyxx  (
   ywsqbh             varchar(36)                     not null,
   rwxh               integer                         not null,
   zhxh               varchar(8)                      not null,
   zhjyxh             integer                         not null,
   jylx               varchar(50),
   jdbz               varchar(1)                      not null,
   bz                 varchar(10)                     not null,
   jyje               varchar(20)                     not null,
   jyye               varchar(20)                     not null,
   jysj               varchar(14)                     not null,
   jylsh              varchar(50)                     not null,
   jydfmc             varchar(60),
   jydfzh             varchar(50),
   jydfzjhm           varchar(30),
   jydfzhkhh          varchar(90),
   jyzy               varchar(150),
   jywdmc             varchar(150)                    not null,
   jywddm             varchar(20)                     not null,
   rzh                varchar(30),
   cph                varchar(30),
   pzzl               varchar(10),
   pzh                varchar(30),
   xjbz               varchar(2)                         not null,
   zdh                varchar(30),
   jysfcg             varchar(2)                         not null,
   jyfsd              varchar(150),
   shmc               varchar(150),
   shh                varchar(30),
   ip                 varchar(30),
   mac                varchar(50),
   jygyh              varchar(20),
   beiz               varchar(150),
   zwrq               varchar(8)                         not null,
   systime            varchar(6)                         not null,
   by1                varchar(30),
   by2                varchar(254),
   by3                varchar(254),
   constraint pkdxzp_zhxx_zhjyxx primary key (ywsqbh, rwxh, zhxh, zhjyxh)
);
create table gab_dxzp_zhjbxx_zhxx  (
   ywsqbh               varchar(36)                     not null,
   rwxh                 integer                         not null,
   zhxh                 integer                         not null,
   zh                   varchar(50)                     not null,
   zhlx                 varchar(30)                     not null,
   zhzt                 varchar(10)                     not null,
   bz                   varchar(3)                      not null,
   chbz                 varchar(4),
   zhye                 varchar(18)                     not null,
   kyye                 varchar(18)                     not null,
   zhjysj               varchar(14)                        not null,
   zwrq                 varchar(8)                         not null,
   systime              varchar(6)                         not null,
   by1                  varchar(30),
   by2                  varchar(254),
   by3                  varchar(254),
   constraint pkdxzp_zhjbxx_zhxx primary key (ywsqbh, rwxh, zhxh)
);
create table gab_dxzp_qhcx_zzhxx  (
   ywsqbh             varchar(36)                     not null,
   rwxh               integer                         not null,
   zzhxh              integer                         not null,
   zh                 varchar(40),
   zzhlb              varchar(30),
   zhzt               varchar(10),
   bz                 varchar(3),
   chbz               varchar(8),
   zhye               varchar(20),
   kyye               varchar(20),
   zhjysj             varchar(14)                        not null,
   zwrq               varchar(8)                         not null,
   systime            varchar(6)                         not null,
   by1                varchar(30),
   by2                varchar(254),
   by3                varchar(254),
   constraint pkdxzp_qhcx_zzhxx primary key (ywsqbh, rwxh, zzhxh)
);
create table gab_dxzp_sbxx_zhjyxx  (
   sbpch              varchar(36)                     not null,
   sbpcxh             integer                         not null,
   zhxh               varchar(8)                      not null,
   zhjyxh             integer                         not null,
   csbwlsh            varchar(53),
   ywsqbh             varchar(36),
   sjtzm              varchar(4),
   jylx               varchar(50),
   jdbz               varchar(1)                      not null,
   bz                 varchar(10)                     not null,
   jyje               varchar(20)                     not null,
   jyye               varchar(20)                     not null,
   jysj               varchar(14)                     not null,
   jylsh              varchar(50)                     not null,
   jydfmc             varchar(60),
   jydfzh             varchar(50),
   jydfzjhm           varchar(30),
   jydfzhkhh          varchar(90),
   jyzy               varchar(150),
   jywdmc             varchar(150)                    not null,
   jywddm             varchar(20)                     not null,
   rzh                varchar(30),
   cph                varchar(30),
   pzzl               varchar(10),
   pzh                varchar(30),
   xjbz               varchar(2)                      not null,
   zdh                varchar(30),
   jysfcg             varchar(2)                      not null,
   jyfsd              varchar(150),
   shmc               varchar(150),
   shh                varchar(30),
   ip                 varchar(30),
   mac                varchar(50),
   jygyh              varchar(20),
   beiz               varchar(150),
   zwrq               varchar(8)                         not null,
   systime            varchar(6)                         not null,
   by1                varchar(30),
   by2                varchar(254),
   by3                varchar(254),
   constraint pkdxzp_sbxx_zhjyxx primary key (sbpch, sbpcxh, zhxh, zhjyxh)
);
create table gab_dxzp_sf_szh  (
   jybm               varchar(6),
   csbwlsh            varchar(53)                     not null,
   ywsqbh             varchar(36)                     not null,
   ywlx               varchar(4)                      not null,
   hcmdlx             varchar(6)                      not null,
   hcsjlx             varchar(45)                     not null,
   hcyhbm             varchar(12),
   hcsjx              varchar(30)                     not null,
   hczhm              varchar(120),
   hrmdlx             varchar(6)                      not null,
   hrsjlx             varchar(45)                     not null,
   hryhbm             varchar(12),
   hrsjx              varchar(30)                     not null,
   hrzhm              varchar(120),
   zt                 varchar(2),
   hcgalxr            varchar(40),
   hcgalxdh           varchar(30),
   hckksj             varchar(14),
   hcyxq              varchar(29),
   hcmdsm             varchar(254),
   hrgalxr            varchar(40),
   hrgalxdh           varchar(30),
   hrkksj             varchar(14),
   hryxq              varchar(29),
   hrmdsm             varchar(254),
   zwrq               varchar(8)                         not null,
   systime            varchar(6)                         not null,
   by1                varchar(30),
   by2                varchar(254),
   by3                varchar(254),
   constraint pkdxzp_sf_szh primary key (csbwlsh)
);