delete from ICPS_BUSI_INF where busi_no in ('jiebei','jintiao','wbank');

insert into ICPS_BUSI_INF (BUSI_NO, BUSI_NM, LOCAL_ID, TIME_ZONE, SIGN_TYPE, MESSAGE_CHARSET, VERSION, CLEAR_ACCT_ID, CLEAR_ACCT_NM, POSITION_ACCT_ID, POSITION_ACCT_NM, FEE_OUT_ACCT_ID, FEE_OUT_ACCT_NM, FEE_IN_ACCT_ID, FEE_IN_ACCT_NM, PROVISIONS_ACCT_ID, PROVISIONS_ACCT_NM, OPEN_FLAG, EXTEND_PARAM1, EXTEND_PARAM2, EXTEND_PARAM3)
values ('jiebei', 'ÂìÒÏ½èßÂ', 'HUNDSUN', 'UTC+8', 'RSA', 'UTF-8', '1.0.0', null, null, null, null, null, null, null, null, null, null, '1', null, null, null);

insert into ICPS_BUSI_INF (BUSI_NO, BUSI_NM, LOCAL_ID, TIME_ZONE, SIGN_TYPE, MESSAGE_CHARSET, VERSION, CLEAR_ACCT_ID, CLEAR_ACCT_NM, POSITION_ACCT_ID, POSITION_ACCT_NM, FEE_OUT_ACCT_ID, FEE_OUT_ACCT_NM, FEE_IN_ACCT_ID, FEE_IN_ACCT_NM, PROVISIONS_ACCT_ID, PROVISIONS_ACCT_NM, OPEN_FLAG, EXTEND_PARAM1, EXTEND_PARAM2, EXTEND_PARAM3)
values ('jintiao', '¾©¶«½ðÌõ', 'HUNDSUN', 'UTC+8', 'RSA', 'GBK', '1.0.0', null, null, null, null, null, null, null, null, null, null, '1', null, null, null);

insert into ICPS_BUSI_INF (BUSI_NO, BUSI_NM, LOCAL_ID, TIME_ZONE, SIGN_TYPE, MESSAGE_CHARSET, VERSION, CLEAR_ACCT_ID, CLEAR_ACCT_NM, POSITION_ACCT_ID, POSITION_ACCT_NM, FEE_OUT_ACCT_ID, FEE_OUT_ACCT_NM, FEE_IN_ACCT_ID, FEE_IN_ACCT_NM, PROVISIONS_ACCT_ID, PROVISIONS_ACCT_NM, OPEN_FLAG, EXTEND_PARAM1, EXTEND_PARAM2, EXTEND_PARAM3)
values ('wbank', 'Î¢Á£´û', 'HUNDSUN', 'UTC+8', 'RSA', 'GBK', '1.0.0', null, null, null, null, null, null, null, null, null, null, '1', null, null, null);

commit;