drop table TBL_SPFYSKJG_JGXM_JYMX;
create table TBL_SPFYSKJG_JGXM_JYMX
(
BOOKDATE             varchar(8)        not null,
RECORDID             varchar(40)       not null, 
ACCOUNT              varchar(40)       not null,
ACCOUNTNAME          varchar(100)      not null,
TRANDT               varchar(8)        not null,   
TRANSQ               varchar(40)       not null, 
PAYAMOUNT            DECIMAL(16,2)     not null, 
EARNAMOUNT           DECIMAL(16,2)     not null, 
BALAMOUNT            DECIMAL(16,2)     not null,
SMRYTX               varchar(120),
SMRYCD               varchar(40), 
POSTSCRIPT           varchar(120),
TOACCT               varchar(40), 
TOACNA               varchar(40), 
TOBRNA               varchar(40), 
OCCURS               varchar(2)        not null,  
PUSHDATE             varchar(8),  
MEMO                 varchar(100),
STATUS               varchar(2),  
PUSHNO               DECIMAL(2),    
ACCOUNTORG           Varchar(20),  
USERID               varchar(40), 
ORGID                varchar(40), 
UPDATEDATE           varchar(8),  
REMARK1              varchar(254), 
REMARK2              varchar(254), 
REMARK3              varchar(254), 
CONSTRAINT PK_TBL_SPFYSKJG_JGXM_JYMX PRIMARY KEY (BOOKDATE,RECORDID,ACCOUNT,ACCOUNTNAME,TRANDT,TRANSQ,PAYAMOUNT,EARNAMOUNT,BALAMOUNT,OCCURS))IN AGENT_DATA INDEX IN AGENT_INDEX;
COMMENT ON TABLE TBL_SPFYSKJG_JGXM_JYMX IS '预售监管账户交易明细登记表';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.BOOKDATE IS '登记日期';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.RECORDID IS '唯一标识码';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.ACCOUNT IS '账号';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.ACCOUNTNAME IS '账户名称';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.TRANDT IS '交易日期';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.TRANSQ IS '交易流水号';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.PAYAMOUNT IS '收入金额';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.EARNAMOUNT IS '支出金额';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.BALAMOUNT IS '余额';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.SMRYTX IS '摘要';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.SMRYCD IS '摘要码';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.POSTSCRIPT IS '附言';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.TOACCT IS '对方账号';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.TOACNA IS '对方账号名称';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.TOBRNA IS '对方所属行';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.OCCURS IS '资金交易方向';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.PUSHDATE IS '推送日期';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.MEMO IS '交易结果描述';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.STATUS IS '推送状态';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.PUSHNO IS '重推序号';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.ACCOUNTORG IS '账务所属机构';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.USERID IS '经办人';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.ORGID IS '经办机构';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.UPDATEDATE IS '维护日期';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.REMARK1 IS '备用字段1';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.REMARK2 IS '备用字段2';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM_JYMX.REMARK3 IS '备用字段3';

