drop table TBL_SPFYSKJG_JGXM;
create table TBL_SPFYSKJG_JGXM
(
BOOKDATE     varchar(8)    not null,
OPID         varchar(20)  not null,
RESULTCODE   varchar(2)   not null,
DESCRIPTION  varchar(100) not null,
PROJECTID    varchar(40)  not null,
ENTERPRISES  varchar(100) not null,
PROJECTNAME  varchar(1000)not null,
ADDRESS      varchar(200),
SUPERSTATUS  varchar(1)   not null,
ACCOUNTID    varchar(2)    not null,
ACCOUNT     varchar(40)  not null,
ACCOUNTNAME  varchar(100) not null,
OPENBNAME    varchar(300) not null,
CREATEDATE   varchar(8),
HEADOFFICE   varchar(10),
REMAIN       DECIMAL(16,2),
FREEZE       DECIMAL(16,2),
STATE        varchar(1),
QUERYTIMES   varchar(10),
FAILTIMES    varchar(10),
TRANTIME     varchar(16),
TRANFLOWNO   varchar(20),
TRANSTATUS   varchar(1),
MEMO         varchar(100),
ACCOUNTORG  varchar(20),
REMARK1      varchar(254),
REMARK2      varchar(254),
REMARK3      varchar(254),
CONSTRAINT PK_TBL_SPFYSKJG_JGXM PRIMARY KEY (BOOKDATE,OPID,RESULTCODE,DESCRIPTION,ENTERPRISES,PROJECTNAME,SUPERSTATUS,ACCOUNTID,ACCOUNTNAME,OPENBNAME))IN AGENT_DATA INDEX IN AGENT_INDEX;
COMMENT ON TABLE TBL_SPFYSKJG_JGXM IS '商品房预售款监管_监管项目表';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.BOOKDATE IS '账务日期 YYYYMMDD';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.OPID IS '流水号';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.RESULTCODE IS '返回码';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.DESCRIPTION IS '返回描述';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.PROJECTID IS '监管项目编号';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.ENTERPRISES IS '房地企业';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.PROJECTNAME IS '监管名称';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.ADDRESS IS '项目所属镇街';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.SUPERSTATUS IS '监管状态 0-有效，1-无效';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.ACCOUNTID IS '账户序号';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.ACCOUNT IS '监管账号';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.ACCOUNTNAME IS '户名';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.OPENBNAME IS '开户银行名称';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.CREATEDATE IS '监管账号设立日期';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.HEADOFFICE IS '总行';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.REMAIN IS '当前总余额';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.FREEZE IS '被冻结余额';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.STATE IS '账户状态';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.QUERYTIMES IS '核心账户信息查询次数';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.FAILTIMES IS '核心账户信息查询失败次数';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.TRANTIME IS '最新提交核心时间';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.TRANFLOWNO IS '最新提交核心流水号';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.TRANSTATUS IS '账户信息查询交易状态';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.MEMO IS '交易结果描述';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.ACCOUNTORG IS '账户所属机构';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.REMARK1 IS '备用1';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.REMARK2 IS '备用2';
COMMENT ON COLUMN TBL_SPFYSKJG_JGXM.REMARK3 IS '备用3';
