drop table TBL_SPFYSKJG_CHXX;
create table TBL_SPFYSKJG_CHXX
(
BOOKDATE           varchar(8)       not null,
OPID               varchar(20)      not null,
ORIRECORDID        varchar(40)      not null,
RECORDTYPE         DECIMAL(1)       not null,
MEMO               varchar(100), 
STATUS             varchar(2),    
REMARK1            varchar(254),  
REMARK2            varchar(254),  
REMARK3            varchar(254),  
CONSTRAINT PK_TBL_SPFYSKJG_CHXX PRIMARY KEY (BOOKDATE,OPID,ORIRECORDID,
RECORDTYPE))IN AGENT_DATA INDEX IN AGENT_INDEX;
COMMENT ON TABLE TBL_SPFYSKJG_CHXX IS '预售监管撤回信息表';
COMMENT ON COLUMN TBL_SPFYSKJG_CHXX.BOOKDATE IS '登记日期';
COMMENT ON COLUMN TBL_SPFYSKJG_CHXX.OPID IS '流水号';
COMMENT ON COLUMN TBL_SPFYSKJG_CHXX.ORIRECORDID IS '索引';
COMMENT ON COLUMN TBL_SPFYSKJG_CHXX.RECORDTYPE IS '信息类型';
COMMENT ON COLUMN TBL_SPFYSKJG_CHXX.MEMO IS '交易结果描述';
COMMENT ON COLUMN TBL_SPFYSKJG_CHXX.STATUS IS '推送状态';
COMMENT ON COLUMN TBL_SPFYSKJG_CHXX.REMARK1 IS '备用字段1';
COMMENT ON COLUMN TBL_SPFYSKJG_CHXX.REMARK2 IS '备用字段2';
COMMENT ON COLUMN TBL_SPFYSKJG_CHXX.REMARK3 IS '备用字段3'; 
