/********************************************************************
版权所有:杭州恒生电子股份有限公司
项目名称:综合应用平台（GAPS）项目
版    本:V1.0
操作系统:AIX SCO LINUX SunOS HP-UX
数 据 库:
文件名称:通用XML元素名称宏定义头文件
文件描述:icc_xmlmacro.h
项 目 组:
程 序 员:
发布日期:
修    订:
修改日期:
*********************************************************************/
/*
修改记录
修改日期:
修改内容:
修改人:
*/


#ifndef __APP_XMLMACRO_H__
#define __APP_XMLMACRO_H__

/* 交易耗时 */
#define XMLNM_APP_TRANSTIME            "/app/transtime"

#define XMLNM_APP_YYXX_YYBS            "/app/yyxx/yybs"
#define XMLNM_APP_YYXX_YYMC            "/app/yyxx/yymc"
#define XMLNM_APP_YYXX_YYSM            "/app/yyxx/yysm"
#define XMLNM_APP_YYXX_YYKFKSRQ        "/app/yyxx/yykfksrq"
#define XMLNM_APP_YYXX_YYKFJSRQ        "/app/yyxx/yykfjsrq"
#define XMLNM_APP_YYXX_YYFBRQ          "/app/yyxx/yyfbrq"
#define XMLNM_APP_YYXX_YYBBH           "/app/yyxx/yybbh"
#define XMLNM_APP_YYXX_YHH             "/app/yyxx/yhh"
#define XMLNM_APP_YYXX_SQH             "/app/yyxx/sqh"
#define XMLNM_APP_YYXX_YYKFJL          "/app/yyxx/yykfjl"
#define XMLNM_APP_YYXX_YYZBJL          "/app/yyxx/yyzbjl"
#define XMLNM_APP_YYXX_YYZT            "/app/yyxx/yyzt"
#define XMLNM_APP_YYXX_EXTFLD          "/app/yyxx/extfld"

#define XMLNM_APP_QDXX_QDBS            "/app/qdxx/qdbs"
#define XMLNM_APP_QDXX_QDMC            "/app/qdxx/qdmc"
#define XMLNM_APP_QDXX_QDSM            "/app/qdxx/qdsm"
#define XMLNM_APP_QDXX_SJKZBZ          "/app/qdxx/sjkzbz"
#define XMLNM_APP_QDXX_QSSJ            "/app/qdxx/qssj"
#define XMLNM_APP_QDXX_JSSJ            "/app/qdxx/jssj"
#define XMLNM_APP_QDXX_CZBZ            "/app/qdxx/czbz"
#define XMLNM_APP_QDXX_ZDCZBZ          "/app/qdxx/zdczbz"
#define XMLNM_APP_QDXX_EXTFLD1         "/app/qdxx/extfld1"
#define XMLNM_APP_QDXX_EXTFLD2         "/app/qdxx/extfld2"
#define XMLNM_APP_QDXX_QDZT            "/app/qdxx/qdzt"

#define XMLNM_APP_JGXX_ORG_ID1          "/app/org/org_id1"
#define XMLNM_APP_JGXX_ORG_ID2          "/app/org/org_id2"
#define XMLNM_APP_JGXX_ORG_ID3          "/app/org/org_id3"
#define XMLNM_APP_JGXX_ORG_ID4          "/app/org/org_id4"
#define XMLNM_APP_JGXX_ORG_ID          "/app/org/org_id"
#define XMLNM_APP_JGXX_ORG_NAME        "/app/org/org_name"
#define XMLNM_APP_JGXX_ORG_DESC        "/app/org/org_desc"
#define XMLNM_APP_JGXX_ABOVE_ORG_ID    "/app/org/above_org_id"
#define XMLNM_APP_JGXX_INNER_ORG_ID    "/app/org/inner_org_id"
#define XMLNM_APP_JGXX_ORG_LEVEL       "/app/org/org_level"
#define XMLNM_APP_JGXX_ORG_ADRESS      "/app/org/org_adress"
#define XMLNM_APP_JGXX_ORG_TYPE        "/app/org/org_type"
#define XMLNM_APP_JGXX_TEL             "/app/org/tel"
#define XMLNM_APP_JGXX_EMAIL           "/app/org/email"
#define XMLNM_APP_JGXX_BAK1            "/app/org/bak1"
#define XMLNM_APP_JGXX_BAK2            "/app/org/bak2"
#define XMLNM_APP_JGXX_BAK3            "/app/org/bak3"

#define XMLNM_APP_JYXX_JYDM            "/app/jyxx/jydm"
#define XMLNM_APP_JYXX_JYMC            "/app/jyxx/jymc"
#define XMLNM_APP_JYXX_YYBS            "/app/jyxx/yybs"
#define XMLNM_APP_JYXX_JYLX            "/app/jyxx/jylx"
#define XMLNM_APP_JYXX_LSJLBZ          "/app/jyxx/lsjlbz"
#define XMLNM_APP_JYXX_RZBZ            "/app/jyxx/rzbz"
#define XMLNM_APP_JYXX_BBBZ            "/app/jyxx/bbbz"
#define XMLNM_APP_JYXX_CPXG            "/app/jyxx/cpxg"
#define XMLNM_APP_JYXX_EXTFLD1         "/app/jyxx/extfld1"
#define XMLNM_APP_JYXX_EXTFLD2         "/app/jyxx/extfld2"
#define XMLNM_APP_JYXX_QTBZ            "/app/jyxx/qtbz"
                       
#define XMLNM_APP_CPXX_CPDM            "/app/cpxx/cpdm"
#define XMLNM_APP_CPXX_CPMC            "/app/cpxx/cpmc"
#define XMLNM_APP_CPXX_YYBS            "/app/cpxx/yybs"
#define XMLNM_APP_CPXX_ZBJG            "/app/cpxx/zbjg"
#define XMLNM_APP_CPXX_ZBGY            "/app/cpxx/zbgy"
#define XMLNM_APP_CPXX_KHJL            "/app/cpxx/khjl"
#define XMLNM_APP_CPXX_YWRQLX          "/app/cpxx/ywrqlx"
#define XMLNM_APP_CPXX_QDKZBZ          "/app/cpxx/qdkzbz"
#define XMLNM_APP_CPXX_JGKZCS          "/app/cpxx/jgkzcs"
#define XMLNM_APP_CPXX_SXFBZ           "/app/cpxx/sxfbz"
#define XMLNM_APP_CPXX_SFQYBZ          "/app/cpxx/sfqybz"
#define XMLNM_APP_CPXX_QYMS            "/app/cpxx/qyms"
#define XMLNM_APP_CPXX_XYXLJZ          "/app/cpxx/xyxljz"
#define XMLNM_APP_CPXX_KKFS            "/app/cpxx/kkfs"
#define XMLNM_APP_CPXX_DZMS            "/app/cpxx/dzms"
#define XMLNM_APP_CPXX_ZJYYH           "/app/cpxx/zjyyh"
#define XMLNM_APP_CPXX_ZJZYYH          "/app/cpxx/zjzyyh"
/*#define XMLNM_APP_CPXX_SFBZ            "/app/cpxx/sfbz"*/
#define XMLNM_APP_CPXX_LSBLTS          "/app/cpxx/lsblts"
#define XMLNM_APP_CPXX_PDBLCS          "/app/cpxx/pdblcs"
#define XMLNM_APP_CPXX_JYFS            "/app/cpxx/jyfs"
#define XMLNM_APP_CPXX_RZMS            "/app/cpxx/rzms"
#define XMLNM_APP_CPXX_EXTFLD1         "/app/cpxx/extfld1"
#define XMLNM_APP_CPXX_EXTFLD2         "/app/cpxx/extfld2"
#define XMLNM_APP_CPXX_CPZT            "/app/cpxx/cpzt"
#define XMLNM_APP_CPXX_JZSX            "/app/cpxx/jzsx"


#define XMLNM_APP_CPXX_YWRQ            "/app/cpxx/ywrq"    
#define XMLNM_APP_CPXX_YWLSH           "/app/cpxx/ywlsh" 
#define XMLNM_APP_CPXX_CCH             "/app/cpxx/cch"



#define XMLNM_APP_CPQDGX_CPDM         "/app/cpqdgx/cpdm"
#define XMLNM_APP_CPQDGX_QDBS         "/app/cpqdgx/qdbs"
#define XMLNM_APP_CPQDGX_SJKZBZ       "/app/cpqdgx/sjkzbz"
#define XMLNM_APP_CPQDGX_QSSJ         "/app/cpqdgx/qssj"
#define XMLNM_APP_CPQDGX_JSSJ         "/app/cpqdgx/jssj"
#define XMLNM_APP_CPQDGX_XEKZBZ       "/app/cpqdgx/xekzbz"
#define XMLNM_APP_CPQDGX_ZXXE         "/app/cpqdgx/zxxe"
#define XMLNM_APP_CPQDGX_ZDXE         "/app/cpqdgx/zdxe"
#define XMLNM_APP_CPQDGX_CZBZ         "/app/cpqdgx/czbz"
#define XMLNM_APP_CPQDGX_ZDCZBZ       "/app/cpqdgx/zdczbz"
#define XMLNM_APP_CPQDGX_FPBCBZ       "/app/cpqdgx/fpbcbz"
#define XMLNM_APP_CPQDGX_FPCSFS       "/app/cpqdgx/fpcsfs"
#define XMLNM_APP_CPQDGX_EXTFLD1      "/app/cpqdgx/extfld1"
#define XMLNM_APP_CPQDGX_EXTFLD2      "/app/cpqdgx/extfld2"
#define XMLNM_APP_CPQDGX_ZT           "/app/cpqdgx/zt"

#define XMLNM_APP_CPJGGX_CPDM         "/app/cpjggx/cpdm"
#define XMLNM_APP_CPJGGX_JGBH         "/app/cpjggx/jgbh"
#define XMLNM_APP_CPJGGX_SJKZBZ       "/app/cpjggx/sjkzbz"
#define XMLNM_APP_CPJGGX_QSSJ         "/app/cpjggx/qssj"
#define XMLNM_APP_CPJGGX_JSSJ         "/app/cpjggx/jssj"
#define XMLNM_APP_CPJGGX_EXTFLD1      "/app/cpjggx/extfld1"
#define XMLNM_APP_CPJGGX_EXTFLD2      "/app/cpjggx/extfld2"
#define XMLNM_APP_CPJGGX_EXTFLD3      "/app/cpjggx/extfld3"
#define XMLNM_APP_CPJGGX_ZT           "/app/cpjggx/zt"

#define XMLNM_APP_KHCPQYXX_XYBH       "/app/khcpqy/xybh"
#define XMLNM_APP_KHCPQYXX_CPDM       "/app/khcpqy/cpdm"
#define XMLNM_APP_KHCPQYXX_YWBH       "/app/khcpqy/ywbh"
#define XMLNM_APP_KHCPQYXX_ZHLX       "/app/khcpqy/zhlx"
#define XMLNM_APP_KHCPQYXX_KHJG       "/app/khcpqy/khjg"
#define XMLNM_APP_KHCPQYXX_QYZH       "/app/khcpqy/qyzh"
#define XMLNM_APP_KHCPQYXX_ZHHM       "/app/khcpqy/zhhm"
#define XMLNM_APP_KHCPQYXX_DLZJLX     "/app/khcpqy/dlzjlx"
#define XMLNM_APP_KHCPQYXX_DLZJHM     "/app/khcpqy/dlzjhm"
#define XMLNM_APP_KHCPQYXX_ZJLX       "/app/khcpqy/zjlx"
#define XMLNM_APP_KHCPQYXX_ZJHM       "/app/khcpqy/zjhm"
#define XMLNM_APP_KHCPQYXX_QYLX       "/app/khcpqy/qylx"
#define XMLNM_APP_KHCPQYXX_KHJL       "/app/khcpqy/khjl"
#define XMLNM_APP_KHCPQYXX_HYKSRQ     "/app/khcpqy/hyksrq"
#define XMLNM_APP_KHCPQYXX_HYJSRQ     "/app/khcpqy/hyjsrq"
#define XMLNM_APP_KHCPQYXX_KTQD       "/app/khcpqy/ktqd"
#define XMLNM_APP_KHCPQYXX_BLJG       "/app/khcpqy/bljg"
#define XMLNM_APP_KHCPQYXX_BLGY       "/app/khcpqy/blgy"
#define XMLNM_APP_KHCPQYXX_BLRQ       "/app/khcpqy/blrq"
#define XMLNM_APP_KHCPQYXX_YHH1       "/app/khcpqy/yhh1"
#define XMLNM_APP_KHCPQYXX_YHH2       "/app/khcpqy/yhh2"
#define XMLNM_APP_KHCPQYXX_YHH3       "/app/khcpqy/yhh3"
#define XMLNM_APP_KHCPQYXX_YHMC       "/app/khcpqy/yhmc"
#define XMLNM_APP_KHCPQYXX_YHLX       "/app/khcpqy/yhlx"
#define XMLNM_APP_KHCPQYXX_YHYB       "/app/khcpqy/yhyb"
#define XMLNM_APP_KHCPQYXX_YHDH       "/app/khcpqy/yhdh"
#define XMLNM_APP_KHCPQYXX_YHDZ       "/app/khcpqy/yhdz"
#define XMLNM_APP_KHCPQYXX_JYBZ       "/app/khcpqy/jybz"
#define XMLNM_APP_KHCPQYXX_KKZDXE     "/app/khcpqy/kkzdxe"
#define XMLNM_APP_KHCPQYXX_KKZQ       "/app/khcpqy/kkzq"
#define XMLNM_APP_KHCPQYXX_YDKKRQ     "/app/khcpqy/ydkkrq"
#define XMLNM_APP_KHCPQYXX_KKZT       "/app/khcpqy/kkzt"
#define XMLNM_APP_KHCPQYXX_KKRQ       "/app/khcpqy/kkrq"
#define XMLNM_APP_KHCPQYXX_DXTZBZ     "/app/khcpqy/dxtzbz"
#define XMLNM_APP_KHCPQYXX_ZHZDED     "/app/khcpqy/zhzded"
#define XMLNM_APP_KHCPQYXX_EXTFLD1    "/app/khcpqy/extfld1"
#define XMLNM_APP_KHCPQYXX_EXTFLD2    "/app/khcpqy/extfld2"
#define XMLNM_APP_KHCPQYXX_EXTFLD3    "/app/khcpqy/extfld3"
#define XMLNM_APP_KHCPQYXX_EXTFLD4    "/app/khcpqy/extfld4"
#define XMLNM_APP_KHCPQYXX_EXTFLD5    "/app/khcpqy/extfld5"
#define XMLNM_APP_KHCPQYXX_EXTFLD6    "/app/khcpqy/extfld6"
#define XMLNM_APP_KHCPQYXX_QYZT       "/app/khcpqy/qyzt"

#define XMLNM_APP_TXAQXX_LJBS         "/app/txaqxx/ljbs"
#define XMLNM_APP_TXAQXX_LJMC         "/app/txaqxx/ljmc"
#define XMLNM_APP_TXAQXX_LJLX         "/app/txaqxx/ljlx"
#define XMLNM_APP_TXAQXX_DWBH         "/app/txaqxx/dwbh"
#define XMLNM_APP_TXAQXX_QDKZ         "/app/txaqxx/qdkz"
#define XMLNM_APP_TXAQXX_TXMS         "/app/txaqxx/txms"
#define XMLNM_APP_TXAQXX_TXDZ         "/app/txaqxx/txdz"
#define XMLNM_APP_TXAQXX_TXDK         "/app/txaqxx/txdk"
#define XMLNM_APP_TXAQXX_FSCS         "/app/txaqxx/fscs"
#define XMLNM_APP_TXAQXX_JSCS         "/app/txaqxx/jscs"
#define XMLNM_APP_TXAQXX_LJJGH        "/app/txaqxx/ljjgh"
#define XMLNM_APP_TXAQXX_LJGYH        "/app/txaqxx/ljgyh"
#define XMLNM_APP_TXAQXX_LJZDH        "/app/txaqxx/ljzdh"
#define XMLNM_APP_TXAQXX_KEY1         "/app/txaqxx/key1"
#define XMLNM_APP_TXAQXX_KEY2         "/app/txaqxx/key2"
#define XMLNM_APP_TXAQXX_KEY3         "/app/txaqxx/key3"
#define XMLNM_APP_TXAQXX_FTPDZ        "/app/txaqxx/ftpdz"
#define XMLNM_APP_TXAQXX_FTPYH        "/app/txaqxx/ftpyh"
#define XMLNM_APP_TXAQXX_FTPMM        "/app/txaqxx/ftpmm"
#define XMLNM_APP_TXAQXX_FTPGZFS      "/app/txaqxx/ftpgzfs"
#define XMLNM_APP_TXAQXX_FTPCSFS      "/app/txaqxx/ftpcsfs"
#define XMLNM_APP_TXAQXX_FTPZDMS      "/app/txaqxx/ftpzdms"
#define XMLNM_APP_TXAQXX_FTPDFLJ      "/app/txaqxx/ftpdflj"
#define XMLNM_APP_TXAQXX_FTPBDLJ      "/app/txaqxx/ftpbdlj"
#define XMLNM_APP_TXAQXX_EXTFLD1      "/app/txaqxx/extfld1"
#define XMLNM_APP_TXAQXX_EXTFLD2      "/app/txaqxx/extfld2"
#define XMLNM_APP_TXAQXX_TXZT         "/app/txaqxx/txzt"
#define XMLNM_APP_TXAQXX_QDZT         "/app/txaqxx/qdzt"

#define XMLNM_APP_DWXX_DWBH	          "/app/dwxx/dwbh"
#define XMLNM_APP_DWXX_DWMC	          "/app/dwxx/dwmc"
#define XMLNM_APP_DWXX_DWZJLX	      "/app/dwxx/dwzjlx"
#define XMLNM_APP_DWXX_DWZJHM	      "/app/dwxx/dwzjhm"
#define XMLNM_APP_DWXX_DWLXR	      "/app/dwxx/dwlxr"
#define XMLNM_APP_DWXX_DWLXRDH	      "/app/dwxx/dwlxrdh"
#define XMLNM_APP_DWXX_DWDZ	          "/app/dwxx/dwdz"
#define XMLNM_APP_DWXX_DWEMAIL	      "/app/dwxx/dwemail"
#define XMLNM_APP_DWXX_EXTFLD1	      "/app/dwxx/extfld1"
#define XMLNM_APP_DWXX_EXTFLD2	      "/app/dwxx/extfld2"
#define XMLNM_APP_DWXX_ZT	          "/app/dwxx/zt"

#define XMLNM_APP_RWKZB_YYBS          "/app/rwjkb/yybs"
#define XMLNM_APP_RWKZB_YYMC          "/app/rwjkb/yymc"
#define XMLNM_APP_RWKZB_CPDM          "/app/rwjkb/cpdm"
#define XMLNM_APP_RWKZB_CPMC          "/app/rwjkb/cpmc"
#define XMLNM_APP_RWJKB_RWMC          "/app/rwjkb/rwmc"
#define XMLNM_APP_RWKZB_JYDM          "/app/rwjkb/jydm"
#define XMLNM_APP_RWJKB_JYMC          "/app/rwjkb/jymc"
#define XMLNM_APP_RWKZB_PTLS          "/app/rwjkb/ptls"
#define XMLNM_APP_RWJKB_PTRQ          "/app/rwjkb/ptrq"
#define XMLNM_APP_RWJKB_JYJG          "/app/rwjkb/jyjg"
#define XMLNM_APP_RWJKB_JYGY          "/app/rwjkb/jygy"
#define XMLNM_APP_RWJKB_QDBS          "/app/rwjkb/qdbs"
#define XMLNM_APP_RWJKB_KSSJ          "/app/rwjkb/kssj"
#define XMLNM_APP_RWJKB_JSSJ          "/app/rwjkb/jssj"
#define XMLNM_APP_RWKZB_YXSJ          "/app/rwjkb/yxsj"
#define XMLNM_APP_RWJKB_ZXCS          "/app/rwjkb/zxcs"
#define XMLNM_APP_RWJKB_ZXZT          "/app/rwjkb/zxzt"
#define XMLNM_APP_RWKZB_XYM           "/app/rwjkb/xym"
#define XMLNM_APP_RWJKB_XYXX          "/app/rwjkb/xyxx"
#define XMLNM_APP_RWJKB_EXTFLD1       "/app/rwjkb/extfld1"
#define XMLNM_APP_RWJKB_EXTFLD2       "/app/rwjkb/extfld2"
#define XMLNM_APP_RWJKB_EXTFLD3       "/app/rwjkb/extfld3"

/* added 20090224 */
#define XMLNM_APP_KHXX_KHBH           "/app/khxx/khbh"
#define XMLNM_APP_KHXX_KHXM           "/app/khxx/khxm"
#define XMLNM_APP_KHXX_YWXM           "/app/khxx/ywxm"
#define XMLNM_APP_KHXX_BM             "/app/khxx/bm"
#define XMLNM_APP_KHXX_KHLX           "/app/khxx/khlx"
#define XMLNM_APP_KHXX_ZJKHBH         "/app/khxx/zjkhbh"
#define XMLNM_APP_KHXX_ZJLX           "/app/khxx/zjlx"
#define XMLNM_APP_KHXX_ZJHM           "/app/khxx/zjhm"
#define XMLNM_APP_KHXX_CSNY           "/app/khxx/csny"
#define XMLNM_APP_KHXX_SEX            "/app/khxx/sex"
#define XMLNM_APP_KHXX_GJ             "/app/khxx/gj"
#define XMLNM_APP_KHXX_HK             "/app/khxx/hk"
#define XMLNM_APP_KHXX_HYZK           "/app/khxx/hyzk"
#define XMLNM_APP_KHXX_JYCD           "/app/khxx/jycd"
#define XMLNM_APP_KHXX_ZY             "/app/khxx/zy"
#define XMLNM_APP_KHXX_ZW             "/app/khxx/zw"
#define XMLNM_APP_KHXX_SRQK           "/app/khxx/srqk"
#define XMLNM_APP_KHXX_GSDZ           "/app/khxx/gsdz"
#define XMLNM_APP_KHXX_GSYB           "/app/khxx/gsyb"
#define XMLNM_APP_KHXX_GSDH           "/app/khxx/gsdh"
#define XMLNM_APP_KHXX_ZZDZ           "/app/khxx/zzdz"
#define XMLNM_APP_KHXX_ZZYB           "/app/khxx/zzyb"
#define XMLNM_APP_KHXX_ZZDH           "/app/khxx/zzdh"
#define XMLNM_APP_KHXX_SJHM           "/app/khxx/sjhm"
#define XMLNM_APP_KHXX_EMAIL          "/app/khxx/email"
#define XMLNM_APP_KHXX_YJDZLX         "/app/khxx/yjdzlx"
#define XMLNM_APP_KHXX_BZ             "/app/khxx/bz"

/* added 20090904 */
#define XMLNM_APP_DWCPXY_XYBH          "/app/dwcpxy/xybh"
#define XMLNM_APP_DWCPXY_DWBH          "/app/dwcpxy/dwbh"
#define XMLNM_APP_DWCPXY_CPDM          "/app/dwcpxy/cpdm"
#define XMLNM_APP_DWCPXY_YWBH          "/app/dwcpxy/ywbh"
#define XMLNM_APP_DWCPXY_YWMC          "/app/dwcpxy/ywmc"
#define XMLNM_APP_DWCPXY_XYBH          "/app/dwcpxy/xybh"
#define XMLNM_APP_DWCPXY_YHDM          "/app/dwcpxy/yhdm"
#define XMLNM_APP_DWCPXY_LJBS          "/app/dwcpxy/ljbs"
#define XMLNM_APP_DWCPXY_ZHLX          "/app/dwcpxy/zhlx"
#define XMLNM_APP_DWCPXY_SFBZ          "/app/dwcpxy/sfbz"
#define XMLNM_APP_DWCPXY_DSZH          "/app/dwcpxy/dszh"
#define XMLNM_APP_DWCPXY_DSZHMC        "/app/dwcpxy/dszhmc"
#define XMLNM_APP_DWCPXY_DFZH          "/app/dwcpxy/dfzh"
#define XMLNM_APP_DWCPXY_DFZHMC        "/app/dwcpxy/dfzhmc"
#define XMLNM_APP_DWCPXY_KHJL          "/app/dwcpxy/khjl"
#define XMLNM_APP_DWCPXY_LXR           "/app/dwcpxy/lxr"
#define XMLNM_APP_DWCPXY_EMAIL         "/app/dwcpxy/email"
#define XMLNM_APP_DWCPXY_LXDH          "/app/dwcpxy/lxdh"
#define XMLNM_APP_DWCPXY_HYKSRQ        "/app/dwcpxy/hyksrq"
#define XMLNM_APP_DWCPXY_HYJSRQ        "/app/dwcpxy/hyjsrq"
#define XMLNM_APP_DWCPXY_BLJG          "/app/dwcpxy/bljg"
#define XMLNM_APP_DWCPXY_BLGY          "/app/dwcpxy/blgy"
#define XMLNM_APP_DWCPXY_BLRQ          "/app/dwcpxy/blrq"
#define XMLNM_APP_DWCPXY_ZHZDED        "/app/dwcpxy/zhzded"
#define XMLNM_APP_DWCPXY_EXTFLD1       "/app/dwcpxy/extfld1"
#define XMLNM_APP_DWCPXY_EXTFLD2       "/app/dwcpxy/extfld2"
#define XMLNM_APP_DWCPXY_QYZT          "/app/dwcpxy/qyzt"
#define XMLNM_APP_DWCPXY_FWRX          "/app/dwcpxy/fwrx"
#define XMLNM_APP_DWCPXY_JFBHXSMC      "/app/dwcpxy/jfbhxsmc"
#define XMLNM_APP_DWCPXY_KHH           "/app/dwcpxy/khh"
#define XMLNM_APP_DWCPXY_NBHZHMC       "/app/dwcpxy/nbhzhmc"
#define XMLNM_APP_DWCPXY_NBHZH         "/app/dwcpxy/nbhzh"
#define XMLNM_APP_DWCPXY_SXFNBHZHMC    "/app/dwcpxy/sxfnbhzhmc"
#define XMLNM_APP_DWCPXY_SXFNBHZH      "/app/dwcpxy/sxfnbhzh"
#define XMLNM_APP_DWCPXY_SCFS          "/app/dwcpxy/scfs"
#define XMLNM_APP_DWCPXY_SHZT          "/app/dwcpxy/shzt"
#define XMLNM_APP_DWCPXY_SHSJ          "/app/dwcpxy/shsj"
#define XMLNM_APP_DWCPXY_SHGY          "/app/dwcpxy/shgy"
#define XMLNM_APP_DWCPXY_SHJG          "/app/dwcpxy/shjg"
/* end of add */ 

#define XMLNM_APP_GYXX_GYH             "/app/gyxx/gyh"
#define XMLNM_APP_GYXX_JGBH            "/app/gyxx/jgbh"
#define XMLNM_APP_GYXX_GYJB            "/app/gyxx/gyjb"
#define XMLNM_APP_GYXX_GYGW            "/app/gyxx/gygw"
#define XMLNM_APP_GYXX_GYMC            "/app/gyxx/gymc"
#define XMLNM_APP_GYXX_EMAIL           "/app/gyxx/email"
#define XMLNM_APP_GYXX_FAX             "/app/gyxx/fax"
#define XMLNM_APP_GYXX_TEL             "/app/gyxx/tel"
#define XMLNM_APP_GYXX_EXTFLD1         "/app/gyxx/extfld1"
#define XMLNM_APP_GYXX_EXTFLD2         "/app/gyxx/extfld2"
#define XMLNM_APP_GYXX_ZT              "/app/gyxx/zt"

#define XMLNM_APP_REQ_YWBH		       "/app/req/ywbh"
#define XMLNM_APP_REQ_DWBH		       "/app/req/dwbh"
#define XMLNM_APP_REQ_YHH1		       "/app/req/yhh1"
#define XMLNM_APP_REQ_QYZH		       "/app/req/qyzh"
#define XMLNM_APP_REQ_YPTLSH	       "/app/req/yptlsh"
#define XMLNM_APP_REQ_JYJG		       "/app/req/jyjg"
#define XMLNM_APP_REQ_JYGY		       "/app/req/jygy"
#define XMLNM_APP_REQ_SQJG		       "/app/req/sqjg"
#define XMLNM_APP_REQ_SQGY		       "/app/req/sqgy"
#define XMLNM_APP_REQ_QDBS		       "/app/req/qdbs"
#define XMLNM_APP_REQ_ZDSBBH		   "/app/req/zdsbbh"
#define XMLNM_APP_REQ_YYBS		       "/app/req/yybs"
#define XMLNM_APP_REQ_RZBZ		       "/app/req/rzbz"
#define XMLNM_APP_REQ_JYDM		       "/app/req/jydm"
#define XMLNM_APP_REQ_YHBH		       "/app/req/yhbh"
#define XMLNM_APP_REQ_XZBZ		       "/app/req/xzbz"
#define XMLNM_APP_REQ_JDBZ		       "/app/req/jdbz"
#define XMLNM_APP_REQ_YHZH		       "/app/req/yhzh"
#define XMLNM_APP_REQ_DFZH		       "/app/req/dfzh"
#define XMLNM_APP_REQ_JYJE		       "/app/req/jyje"
#define XMLNM_APP_REQ_SXF		       "/app/req/sxf"
#define XMLNM_APP_REQ_PCBH		       "/app/req/pcbh"
#define XMLNM_APP_REQ_EXTFLD1	       "/app/req/extfld1"
#define XMLNM_APP_REQ_EXTFLD2	       "/app/req/extfld2"
#define XMLNM_APP_REQ_CPDM		       "/app/req/cpdm"
#define XMLNM_APP_REQ_DSZH		       "/app/req/dszh"
#define XMLNM_APP_REQ_JYJE		       "/app/req/jyje"
#define XMLNM_APP_REQ_SXF		       "/app/req/sxf"
#define XMLNM_APP_REQ_JYZT		       "/app/req/jyzt"
#define XMLNM_APP_REQ_ZHLX		       "/app/req/zhlx"
#define XMLNM_APP_REQ_FWRX             "/app/req/fwrx"
#define XMLNM_APP_REQ_JFBHXSMC         "/app/req/jfbhxsmc"
#define XMLNM_APP_REQ_KHH              "/app/req/khh"
#define XMLNM_APP_REQ_NBHZHMC          "/app/req/nbhzhmc"
#define XMLNM_APP_REQ_NBHZH            "/app/req/nbhzh"
#define XMLNM_APP_REQ_SXFNBHZHMC       "/app/req/sxfnbhzhmc"
#define XMLNM_APP_REQ_SXFNBHZH         "/app/req/sxfnbhzh"
#define XMLNM_APP_REQ_SCFS             "/app/req/scfs"
/* end of add */

#define XMLNM_APP_REQ_QXLX		   "/app/req/qxlx"

#define XMLNM_APP_REQ_DFZHMC		       "/app/req/dfzhmc"
#define XMLNM_APP_REQ_DSZHMC		       "/app/req/dszhmc"
#define XMLNM_APP_REQ_NBKHH			"/app/req/nbkhh"
#define XMLNM_APP_REQ_NBZH			"/app/req/nbzh"
#define XMLNM_APP_REQ_DWEMAIL			"/app/req/dwemail"
#define XMLNM_APP_REQ_DWLXR			"/app/req/dwlxr"
#define XMLNM_APP_REQ_DWLXRDH			"/app/req/dwlxrdh"
#define XMLNM_APP_REQ_DWDZ			"/app/req/dwdz"
#define XMLNM_APP_REQ_DWMC			"/app/req/dwmc"
#define XMLNM_APP_REQ_JYQY			"/app/req/jyqy"
#define XMLNM_APP_REQ_ZDED			"/app/req/zded"
#define XMLNM_APP_REQ_HYKSRQ			"/app/req/hyksrq"
#define XMLNM_APP_REQ_HYJSRQ			"/app/req/hyjsrq"
#define XMLNM_APP_REQ_KHJL			"/app/req/khjl"
#define XMLNM_APP_REQ_ZHLX			"/app/req/zhlx"
#define XMLNM_APP_REQ_XYBH			"/app/req/xybh"
#define XMLNM_APP_REQ_YHDM			"/app/req/yhdm"
#define XMLNM_APP_REQ_DWZJLX			"/app/req/dwzjlx"
#define XMLNM_APP_REQ_DWZJHM			"/app/req/dwzjhm"
#define XMLNM_APP_REQ_YWMC			"/app/req/ywmc"
#define XMLNM_APP_REQ_QYJY		       "/app/req/qyjy"
#define XMLNM_APP_REQ_QXJG		   "/app/req/qxjg"
#define XMLNM_APP_REQ_QXGY		   "/app/req/qxgy"
#define XMLNM_APP_RESP_DWBH			"/app/resp/dwbh"
#define XMLNM_APP_RESP_YWBH			"/app/resp/ywbh"
#define XMLNM_APP_RESP_COUNT			"/app/resp/count"

/* 扩展属性放在和原信息相同节点下 */
#define XMLNM_APP_CPXX_KZSX_PATH       "/app/cpxx"
#define XMLNM_APP_QDXX_KZSX_PATH       "/app/qdxx"
#define XMLNM_APP_JYXX_KZSX_PATH       "/app/jyxx"
#define XMLNM_APP_DWXX_KZSX_PATH       "/app/dwxx"
#define XMLNM_APP_DWCPXY_KZSX_PATH     "/app/dwcpxy"
#define XMLNM_APP_TXAQXX_PATH          "/app/txaqxx"

#define XMLNM_APP_BILL_PZSL            "/app/bill/pzsl"
#define XMLNM_APP_BILL_PZHM            "/app/bill/pzhm"
#define XMLNM_APP_BILL_QSHM            "/app/bill/qshm"
#define XMLNM_APP_BILL_JSHM            "/app/bill/jshm"
#define XMLNM_APP_BILL_PZLY            "/app/bill/pzly"
#define XMLNM_APP_BILL_JYJG            "/app/bill/jyjg"
#define XMLNM_APP_BILL_JYGY            "/app/bill/jygy"
#define XMLNM_APP_BILL_NBJG            "/app/bill/nbjg"
#define XMLNM_APP_BILL_PZMD            "/app/bill/pzmd"
#define XMLNM_APP_BILL_QLSL            "/app/bill/qlsl"
#define XMLNM_APP_BILL_QLSM            "/app/bill/qlsm"
#define XMLNM_APP_BILL_QLDBH           "/app/bill/qldbh"
#define XMLNM_APP_BILL_QLDZT           "/app/bill/qldzt"
#define XMLNM_APP_BILL_QSRQ            "/app/bill/qsrq"
#define XMLNM_APP_BILL_JSRQ            "/app/bill/jsrq"
#define XMLNM_APP_BILL_DFJG            "/app/bill/dfjg"
#define XMLNM_APP_BILL_DFGY            "/app/bill/dfgy"
#define XMLNM_APP_BILL_PZZT            "/app/bill/pzzt"
#define XMLNM_APP_BILL_JGFS            "/app/bill/jgfs"
#define XMLNM_APP_BILL_PZZL            "/app/bill/pzzl"
#define XMLNM_APP_BILL_PZJG            "/app/bill/pzjg"
#define XMLNM_APP_BILL_PZNBJG          "/app/bill/pznbjg"
#define XMLNM_APP_BILL_PZGY            "/app/bill/pzgy"
#define XMLNM_APP_BILL_GYGW            "/app/bill/gygw"
#define XMLNM_APP_BILL_YPZZT           "/app/bill/ypzzt"

#define XMLNM_APP_CUSTOM_KHBH          "/app/custom/khbh"
#define XMLNM_APP_CUSTOM_KHXM          "/app/custom/khxm"
#define XMLNM_APP_CUSTOM_YWXM          "/app/custom/ywxm"
#define XMLNM_APP_CUSTOM_BM            "/app/custom/bm"
#define XMLNM_APP_CUSTOM_KHLX          "/app/custom/khlx"
#define XMLNM_APP_CUSTOM_ZJKHBH        "/app/custom/zjkhbh"
#define XMLNM_APP_CUSTOM_ZJLX          "/app/custom/zjlx"
#define XMLNM_APP_CUSTOM_ZJHM          "/app/custom/zjhm"
#define XMLNM_APP_CUSTOM_CSNY          "/app/custom/csny"
#define XMLNM_APP_CUSTOM_SEX           "/app/custom/sex"
#define XMLNM_APP_CUSTOM_GJ            "/app/custom/gj"
#define XMLNM_APP_CUSTOM_HK            "/app/custom/hk"
#define XMLNM_APP_CUSTOM_HYZK          "/app/custom/hyzk"
#define XMLNM_APP_CUSTOM_JYCD          "/app/custom/jycd"
#define XMLNM_APP_CUSTOM_ZY            "/app/custom/zy"
#define XMLNM_APP_CUSTOM_ZW            "/app/custom/zw"
#define XMLNM_APP_CUSTOM_SRQK          "/app/custom/srqk"
#define XMLNM_APP_CUSTOM_TXDZ          "/app/custom/txdz"
#define XMLNM_APP_CUSTOM_YZBM          "/app/custom/yzbm"
#define XMLNM_APP_CUSTOM_TXDH          "/app/custom/txdh"
#define XMLNM_APP_CUSTOM_GSDZ          "/app/custom/gsdz"
#define XMLNM_APP_CUSTOM_GSYB          "/app/custom/gsyb"
#define XMLNM_APP_CUSTOM_GSDH          "/app/custom/gsdh"
#define XMLNM_APP_CUSTOM_ZZDZ          "/app/custom/zzdz"
#define XMLNM_APP_CUSTOM_ZZYB          "/app/custom/zzyb"
#define XMLNM_APP_CUSTOM_ZZDH          "/app/custom/zzdh"
#define XMLNM_APP_CUSTOM_YJDZLX        "/app/custom/yjdzlx"
#define XMLNM_APP_CUSTOM_SJHM          "/app/custom/sjhm"
#define XMLNM_APP_CUSTOM_Email         "/app/custom/email"
#define XMLNM_APP_CUSTOM_BZ            "/app/custom/bz"

#define XMLNM_APP_CUSTOM_XYBH       "/app/custom/xybh"  
#define XMLNM_APP_CUSTOM_CPDM       "/app/custom/cpdm"
#define XMLNM_APP_CUSTOM_YWBH       "/app/custom/ywbh"
#define XMLNM_APP_CUSTOM_ZHLX       "/app/custom/zhlx"
#define XMLNM_APP_CUSTOM_QYZH       "/app/custom/qyzh"
#define XMLNM_APP_CUSTOM_ZHHM       "/app/custom/zhhm"
   
#define XMLNM_APP_CUSTOM_QYLX       "/app/custom/qylx"
#define XMLNM_APP_CUSTOM_KHJL       "/app/custom/khjl"
#define XMLNM_APP_CUSTOM_HYKSRQ     "/app/custom/hyksrq"
#define XMLNM_APP_CUSTOM_HYJSRQ     "/app/custom/hyjsrq"
#define XMLNM_APP_CUSTOM_KTQD       "/app/custom/ktqd"
#define XMLNM_APP_CUSTOM_BLJG       "/app/custom/bljg"
#define XMLNM_APP_CUSTOM_BLGY       "/app/custom/blgy"
#define XMLNM_APP_CUSTOM_BLRQ       "/app/custom/blrq"
#define XMLNM_APP_CUSTOM_YHH1       "/app/custom/yhh1"
#define XMLNM_APP_CUSTOM_YHH2       "/app/custom/yhh2"
#define XMLNM_APP_CUSTOM_YHH3       "/app/custom/yhh3"
#define XMLNM_APP_CUSTOM_DXTZBZ     "/app/custom/dxtzbz"
#define XMLNM_APP_CUSTOM_ZHZDED     "/app/custom/zhzded"
#define XMLNM_APP_CUSTOM_EXTFLD1    "/app/custom/extfld1"
#define XMLNM_APP_CUSTOM_EXTFLD2    "/app/custom/extfld2"
#define XMLNM_APP_CUSTOM_EXTFLD3    "/app/custom/extfld3"
#define XMLNM_APP_CUSTOM_QYZT       "/app/custom/qyzt"

/* added 20090708 */
#define XMLNM_APP_CUSTOM_KHJG       "/app/custom/khjg"
#define XMLNM_APP_CUSTOM_YHMC       "/app/custom/yhmc"
#define XMLNM_APP_CUSTOM_YHLX       "/app/custom/yhlx"

#define XMLNM_APP_CUSTOM_DLZJLX     "/app/custom/dlzjlx"
#define XMLNM_APP_CUSTOM_DLZJHM     "/app/custom/dlzjhm"
#define XMLNM_APP_CUSTOM_YHYB       "/app/custom/yhyb"
#define XMLNM_APP_CUSTOM_YHDH       "/app/custom/yhdh"
#define XMLNM_APP_CUSTOM_YHDZ       "/app/custom/yhdz"
#define XMLNM_APP_CUSTOM_JYBZ       "/app/custom/jybz"
#define XMLNM_APP_CUSTOM_KKZDXE     "/app/custom/kkzdxe"
#define XMLNM_APP_CUSTOM_KKZQ       "/app/custom/kkzq"
#define XMLNM_APP_CUSTOM_YDKKRQ     "/app/custom/ydkkrq"
#define XMLNM_APP_CUSTOM_KKZT       "/app/custom/kkzt"
#define XMLNM_APP_CUSTOM_KKRQ       "/app/custom/kkrq"

#define XMLNM_APP_CUSTOM_EXTFLD4    "/app/custom/extfld4"
#define XMLNM_APP_CUSTOM_EXTFLD5    "/app/custom/extfld5"
#define XMLNM_APP_CUSTOM_EXTFLD6    "/app/custom/extfld6"


/* 签约模式 1 产品代码+银行帐号唯一 2 产品代码+用户编号唯一 3 产品代码+银行帐号+用户编号唯一[默认] */
#define XMLNM_APP_CUSTOM_QYMS       "/app/custom/qyms"
/* 修改类型  0 客户信息和签约信息[默认] 1 客户信息 2 签约信息 */
#define XMLNM_APP_CUSTOM_XGLX       "/app/custom/xglx" 
/* 签约查询 返回结果模式 */
#define XMLNM_APP_CUSTOM_JGFS       "/app/custom/jgfs" 
/* 签约查询返回最大记录数 */
#define XMLNM_APP_CUSTOM_QYCXXZ     "/app/custom/qycxxz" 
    
#define XMLNM_APP_CUSTOM_PKEY         "/app/custom/pkey"
#define XMLNM_APP_CUSTOM_XYXH         "/app/custom/xyxh"
#define XMLNM_APP_CUSTOM_COUNT         "/app/custom/count"

#define XMLNM_APP_SXF_CPDM                "/app/sxf/cpdm"
#define XMLNM_APP_SXF_YWBH                "/app/sxf/ywbh"
#define XMLNM_APP_SXF_KHBH                "/app/sxf/khbh"
#define XMLNM_APP_SXF_DWBH                "/app/sxf/dwbh"
#define XMLNM_APP_SXF_YHH                 "/app/sxf/yyh"
#define XMLNM_APP_SXF_QDBS                "/app/sxf/qdbs"
#define XMLNM_APP_SXF_JGBS                "/app/sxf/jgbs"
#define XMLNM_APP_SXF_KHLX                "/app/sxf/khlx"
#define XMLNM_APP_SXF_SHBS                "/app/sxf/shbs"
#define XMLNM_APP_SXF_FLBS                "/app/sxf/flbs"
#define XMLNM_APP_SXF_SQBZ                "/app/sxf/sqbz"
#define XMLNM_APP_SXF_QHBZ                "/app/sxf/qhbz"
#define XMLNM_APP_SXF_KKFS                "/app/sxf/kkfs"
#define XMLNM_APP_SXF_CLFS                "/app/sxf/clfs"
#define XMLNM_APP_SXF_QYRQ                "/app/sxf/qyrq"
#define XMLNM_APP_SXF_SXRQ                "/app/sxf/sxrq"
#define XMLNM_APP_SXF_WHRQ                "/app/sxf/whrq"
#define XMLNM_APP_SXF_WHSJ                "/app/sxf/whsj"
#define XMLNM_APP_SXF_WHGY                "/app/sxf/whgy"
#define XMLNM_APP_SXF_WHJG                "/app/sxf/whjg"
#define XMLNM_APP_SXF_SQGY                "/app/sxf/sqgy"
#define XMLNM_APP_SXF_SQJG                "/app/sxf/sqjg"
#define XMLNM_APP_SXF_FDBZ                "/app/sxf/fdbz"
#define XMLNM_APP_SXF_FDLX                "/app/sxf/fdlx"
#define XMLNM_APP_SXF_LJBZ                "/app/sxf/ljbz"
#define XMLNM_APP_SXF_JSLX                "/app/sxf/jslx"
#define XMLNM_APP_SXF_JSCS                "/app/sxf/jscs"
#define XMLNM_APP_SXF_SXXKZ               "/app/sxf/sxxkz"
#define XMLNM_APP_SXF_SXJE                "/app/sxf/sxje"
#define XMLNM_APP_SXF_XXJE                "/app/sxf/xxje"
#define XMLNM_APP_SXF_QSCS                "/app/sxf/qscs"
#define XMLNM_APP_SXF_JSCS                "/app/sxf/jscs"
#define XMLNM_APP_SXF_SXXBZ               "/app/sxf/sxxbz"
#define XMLNM_APP_SXF_MRBZ                "/app/sxf/mrbz"
#define XMLNM_APP_SXF_MRFL                "/app/sxf/mrfl"

/* 操作类型 1 增加，2删除 3 修改 */
#define XMLNM_APP_SXF_CZLX                "/app/sxf/czlx"
/* 渠道控制标志 */
#define XMLNM_APP_SXF_QDKZBZ               "/app/sxf/qdkzbz"
#define XMLNM_APP_SXF_JGKZBZ               "/app/sxf/jgkzbz"
#define XMLNM_APP_SXF_JGKZJB               "/app/sxf/jgkzjb"
#define XMLNM_APP_SXF_KHKZBZ               "/app/sxf/khkzbz"
#define XMLNM_APP_SXF_SHKZBZ               "/app/sxf/shkzbz"

#define XMLNM_APP_SXF_JYJG                 "/app/sxf/jyjg"
#define XMLNM_APP_SXF_JYGY                 "/app/sxf/jygy"
#define XMLNM_APP_SXF_JYJE                 "/app/sxf/jyje"
#define XMLNM_APP_SXF_JYBS                 "/app/sxf/jybs"
#define XMLNM_APP_SXF_JYRQ                 "/app/sxf/jyrq"
#define XMLNM_APP_SXF_JYSJ                 "/app/sxf/jysj"
/* 计算方式 0 查询费率标识再计算 1 传入费率标识，直接计算 */
#define XMLNM_APP_SXF_JSFS                 "/app/sxf/jsfs"
#define XMLNM_APP_SXF_DJLSBZ               "/app/sxf/djlsbz"
#define XMLNM_APP_SXF_SXF                  "/app/sxf/sxf"
#define XMLNM_APP_SXF_SFRQ                 "/app/sxf/sfrq"
#define XMLNM_APP_SXF_SFZT                 "/app/sxf/sfzt"
#define XMLNM_APP_SXF_SFLSH                "/app/sxf/sflsh"
#define XMLNM_APP_SXF_DFZH                 "/app/sxf/dfzh"
#define XMLNM_APP_SXF_JFZH                 "/app/sxf/jfzh"
#define XMLNM_APP_SXF_XTNWBZ               "/app/sxf/xtnwbz"
#define XMLNM_APP_SXF_SFJYGY               "/app/sxf/sfjygy"
#define XMLNM_APP_SXF_SFJYJG               "/app/sxf/sfjyjg"
#define XMLNM_APP_SXF_PTRQ                 "/app/sxf/ptrq"
#define XMLNM_APP_SXF_JYLX                 "/app/sxf/jylx"
#define XMLNM_APP_SXF_BBLX                 "/app/sxf/bblx"
/* 应用标识 */
#define XMLNM_APP_SXF_YYBS                 "/app/sxf/yybs"      
#define XMLNM_APP_SXF_EXTFLD1              "/app/req/extfld1"
#define XMLNM_APP_SXF_EXTFLD2              "/app/req/extfld2"
/* 通用控制条件*/
#define APP_SXF_COMMON_CONDITION           "ALL"

/*手续费流水插入*/
#define XMLNM_APP_SXF_PTLSOLD			  "/pub/zhqzlsh"
#define XMLNM_APP_SXF_JYLSH				  "/app/sxf/jylsh"
#define XMLNM_APP_SXF_PTLS				  "/app/sxf/ptls"
/* 手续费报表，查询 */
#define XMLNM_APP_SXF_QSRQ				  "/app/sxf/qsrq"
#define XMLNM_APP_SXF_JSRQ				  "/app/sxf/jsrq"
#define XMLNM_APP_SXF_BBWJMC		      "/app/sxf/bbwjmc"

/* app_cskz参数控制表，最小流水号*/
#define XMLNM_APP_CSKZ_ZXLSH		      "/app/zxlsh"

#define XMLNM_APP_RESP_RESPMSG		  "/app/resp/wjnr"
#define XMLNM_APP_RESP_WJMC		      "/app/resp/wjmc"

/* 重置流水号标志 0 重置 */
#define XMLNM_APP_LSH_RETURN           "/app/lshreturn"

#endif
