#ifndef __ICPS_XMLMACRO_H__
#define __ICPS_XMLMACRO_H__



#define XMLNM_APP_JYXX_LSJLBZ                   "/app/jyxx/lsjlbz"                         /*流水记录标志 0 记录 1 不记录*/


/* 当日流水 登记 XML节点宏定义 ---BEGIN */
#define XMLNM_ICPS_REQ_PLT_DATE                 "/icps/req/plt_date"                       /*平台日期*/
#define XMLNM_ICPS_REQ_PLT_TIME                 "/icps/req/plt_time"                       /*平台时间*/
#define XMLNM_ICPS_REQ_PLT_SERIAL               "/icps/req/plt_serial"                     /*平台流水号*/
#define XMLNM_ICPS_REQ_BUSI_DATE                "/icps/req/busi_date"                      /*业务日期*/
#define XMLNM_ICPS_REQ_BUSI_NO                  "/icps/req/busi_no"                        /*业务编号*/
#define XMLNM_ICPS_REQ_CHANNEL                  "/icps/req/channel"                        /*渠道代码*/
#define XMLNM_ICPS_REQ_LOCAL_ID                 "/icps/req/local_id"                       /*本行机构标识*/
#define XMLNM_ICPS_REQ_TRANS_CODE               "/icps/req/trans_code"                     /*平台交易代码*/
#define XMLNM_ICPS_REQ_SEND_RECV_FLAG           "/icps/req/send_recv_flag"                 /*往来账标志*/
#define XMLNM_ICPS_REQ_APPLY_NO                 "/icps/req/apply_no"                       /*申请单号*/
#define XMLNM_ICPS_REQ_VERSION                  "/icps/req/version"                        /*版本号*/
#define XMLNM_ICPS_REQ_SEND_TIME_ZONE           "/icps/req/send_time_zone"                 /*发送方所在时区*/
#define XMLNM_ICPS_REQ_SEND_DTTM                "/icps/req/send_dttm"                      /*报文发起时间*/
#define XMLNM_ICPS_REQ_MSG_ID                   "/icps/req/msg_id"                         /*请求报文标示号*/
#define XMLNM_ICPS_REQ_THIRD_ID                 "/icps/req/third_id"                       /*第三方机构标识*/
#define XMLNM_ICPS_REQ_THIRD_TRANS_CODE         "/icps/req/third_trans_code"               /*第三方交易代码*/
#define XMLNM_ICPS_REQ_THIRD_RESPCODE           "/icps/req/third_respcode"                 /*第三方响应码*/
#define XMLNM_ICPS_REQ_THIRD_RESPMSG            "/icps/req/third_respmsg"                  /*第三方响应信息*/
#define XMLNM_ICPS_REQ_THIRD_TRANS_STATUS       "/icps/req/third_trans_status"             /*第三方交易状态*/
#define XMLNM_ICPS_REQ_RETRY                    "/icps/req/retry"                          /*是否需要重试标记*/
#define XMLNM_ICPS_REQ_SEND_HOST_SERIAL         "/icps/req/send_host_serial"               /*上送主机流水号*/
#define XMLNM_ICPS_REQ_SEND_HOST_DATE           "/icps/req/send_host_date"                 /*上送主机日期*/
#define XMLNM_ICPS_REQ_HOST_SERIAL              "/icps/req/host_serial"                    /*主机流水号*/
#define XMLNM_ICPS_REQ_HOST_DATE                "/icps/req/host_date"                      /*主机日期*/
#define XMLNM_ICPS_REQ_HOST_TRANS_CODE          "/icps/req/host_trans_code"                /*主机交易代码*/
#define XMLNM_ICPS_REQ_HOST_RESPCODE            "/icps/req/host_respcode"                  /*主机响应码*/
#define XMLNM_ICPS_REQ_HOST_RESPMSG             "/icps/req/host_respmsg"                   /*主机响应信息*/
#define XMLNM_ICPS_REQ_HOST_STATUS              "/icps/req/host_status"                    /*主机交易状态*/
#define XMLNM_ICPS_REQ_IN_CHANNEL_DATE          "/icps/req/in_channel_date"                /*行内渠道日期*/
#define XMLNM_ICPS_REQ_IN_CHANNEL_SERIAL        "/icps/req/in_channel_serial"              /*行内渠道流水号*/
#define XMLNM_ICPS_REQ_RESPCODE                 "/icps/req/respcode"                       /*交易响应码*/
#define XMLNM_ICPS_REQ_RESPMSG                  "/icps/req/respmsg"                        /*交易响应信息*/
#define XMLNM_ICPS_REQ_TRANS_STATUS             "/icps/req/trans_status"                   /*交易状态*/
#define XMLNM_ICPS_REQ_BRANCH                   "/icps/req/branch"                         /*交易机构*/
#define XMLNM_ICPS_REQ_TELLER                   "/icps/req/teller"                         /*交易柜员*/
#define XMLNM_ICPS_REQ_GRANT_BRANCH             "/icps/req/grant_branch"                   /*授权机构*/
#define XMLNM_ICPS_REQ_GRANT_TELLER             "/icps/req/grant_teller"                   /*授权柜员*/
#define XMLNM_ICPS_REQ_EXTEND_PARAM1            "/icps/req/extend_param1"                  /*扩展1*/
#define XMLNM_ICPS_REQ_EXTEND_PARAM2            "/icps/req/extend_param2"                  /*扩展2*/
#define XMLNM_ICPS_REQ_EXTEND_PARAM3            "/icps/req/extend_param3"                  /*扩展3*/
#define XMLNM_ICPS_REQ_EXTEND_PARAM4            "/icps/req/extend_param4"                  /*扩展4*/
#define XMLNM_ICPS_REQ_EXTEND_PARAM5            "/icps/req/extend_param5"                  /*扩展5*/
/* 当日流水 登记 XML节点宏定义 ---END */

/* 当日流水 更新 XML节点宏定义 ---BEGIN */
#define XMLNM_ICPS_RESP_PLT_DATE                "/icps/resp/plt_date"                      /*平台日期*/
#define XMLNM_ICPS_RESP_PLT_TIME                "/icps/resp/plt_time"                      /*平台时间*/
#define XMLNM_ICPS_RESP_PLT_SERIAL              "/icps/resp/plt_serial"                    /*平台流水号*/
#define XMLNM_ICPS_RESP_BUSI_DATE               "/icps/resp/busi_date"                     /*业务日期*/
#define XMLNM_ICPS_RESP_BUSI_NO                 "/icps/resp/busi_no"                       /*业务编号*/
#define XMLNM_ICPS_RESP_CHANNEL                 "/icps/resp/channel"                       /*渠道代码*/
#define XMLNM_ICPS_RESP_LOCAL_ID                "/icps/resp/local_id"                      /*本行机构标识*/
#define XMLNM_ICPS_RESP_TRANS_CODE              "/icps/resp/trans_code"                    /*平台交易代码*/
#define XMLNM_ICPS_RESP_SEND_RECV_FLAG          "/icps/resp/send_recv_flag"                /*往来账标志*/
#define XMLNM_ICPS_RESP_APPLY_NO                "/icps/resp/apply_no"                      /*申请单号*/
#define XMLNM_ICPS_RESP_VERSION                 "/icps/resp/version"                       /*版本号*/
#define XMLNM_ICPS_RESP_SEND_TIME_ZONE          "/icps/resp/send_time_zone"                /*发送方所在时区*/
#define XMLNM_ICPS_RESP_SEND_DTTM               "/icps/resp/send_dttm"                     /*报文发起时间*/
#define XMLNM_ICPS_RESP_MSG_ID                  "/icps/resp/msg_id"                        /*请求报文标示号*/
#define XMLNM_ICPS_RESP_THIRD_ID                "/icps/resp/third_id"                      /*第三方机构标识*/
#define XMLNM_ICPS_RESP_THIRD_TRANS_CODE        "/icps/resp/third_trans_code"              /*第三方交易代码*/
#define XMLNM_ICPS_RESP_THIRD_RESPCODE          "/icps/resp/third_respcode"                /*第三方响应码*/
#define XMLNM_ICPS_RESP_THIRD_RESPMSG           "/icps/resp/third_respmsg"                 /*第三方响应信息*/
#define XMLNM_ICPS_RESP_THIRD_TRANS_STATUS      "/icps/resp/third_trans_status"            /*第三方交易状态*/
#define XMLNM_ICPS_RESP_RETRY                   "/icps/resp/retry"                         /*是否需要重试标记*/
#define XMLNM_ICPS_RESP_SEND_HOST_SERIAL        "/icps/resp/send_host_serial"              /*上送主机流水号*/
#define XMLNM_ICPS_RESP_SEND_HOST_DATE          "/icps/resp/send_host_date"                /*上送主机日期*/
#define XMLNM_ICPS_RESP_HOST_SERIAL             "/icps/resp/host_serial"                   /*主机流水号*/
#define XMLNM_ICPS_RESP_HOST_DATE               "/icps/resp/host_date"                     /*主机日期*/
#define XMLNM_ICPS_RESP_HOST_TRANS_CODE         "/icps/resp/host_trans_code"               /*主机交易代码*/
#define XMLNM_ICPS_RESP_HOST_RESPCODE           "/icps/resp/host_respcode"                 /*主机响应码*/
#define XMLNM_ICPS_RESP_HOST_RESPMSG            "/icps/resp/host_respmsg"                  /*主机响应信息*/
#define XMLNM_ICPS_RESP_HOST_STATUS             "/icps/resp/host_status"                   /*主机交易状态*/
#define XMLNM_ICPS_RESP_RESPCODE                "/icps/resp/respcode"                      /*交易响应码*/
#define XMLNM_ICPS_RESP_RESPMSG                 "/icps/resp/respmsg"                       /*交易响应信息*/
#define XMLNM_ICPS_RESP_TRANS_STATUS            "/icps/resp/trans_status"                  /*交易状态*/
#define XMLNM_ICPS_RESP_BRANCH                  "/icps/resp/branch"                        /*交易机构*/
#define XMLNM_ICPS_RESP_TELLER                  "/icps/resp/teller"                        /*交易柜员*/
#define XMLNM_ICPS_RESP_GRANT_BRANCH            "/icps/resp/grant_branch"                  /*授权机构*/
#define XMLNM_ICPS_RESP_GRANT_TELLER            "/icps/resp/grant_teller"                  /*授权柜员*/
#define XMLNM_ICPS_RESP_EXTEND_PARAM1           "/icps/resp/extend_param1"                 /*扩展1*/
#define XMLNM_ICPS_RESP_EXTEND_PARAM2           "/icps/resp/extend_param2"                 /*扩展2*/
#define XMLNM_ICPS_RESP_EXTEND_PARAM3           "/icps/resp/extend_param3"                 /*扩展3*/
#define XMLNM_ICPS_RESP_EXTEND_PARAM4           "/icps/resp/extend_param4"                 /*扩展4*/
#define XMLNM_ICPS_RESP_EXTEND_PARAM5           "/icps/resp/extend_param5"                 /*扩展5*/
/* 当日流水 更新 XML节点宏定义 ---END */

/* 授权申请流水 XML节点宏定义 ---BEGIN */
#define XMLNM_ICPS_APPLY_BUSI_NO                "/icps/apply/busi_no"                      /*业务编号*/
#define XMLNM_ICPS_APPLY_APPLY_NO               "/icps/apply/apply_no"                     /*申请单号*/
#define XMLNM_ICPS_APPLY_ID_TYPE                "/icps/apply/id_type"                      /*证件类型*/
#define XMLNM_ICPS_APPLY_ID_NUM                 "/icps/apply/id_num"                       /*证件号码*/
#define XMLNM_ICPS_APPLY_ID_VALID_END_DATE      "/icps/apply/id_valid_end_date"            /*证件有效期*/
#define XMLNM_ICPS_APPLY_NAME                   "/icps/apply/name"                         /*姓名*/
#define XMLNM_ICPS_APPLY_MOBILE_NO              "/icps/apply/mobile_no"                    /*手机号*/
#define XMLNM_ICPS_APPLY_AUTH_FLAG              "/icps/apply/auth_flag"                    /*芝麻授权成功标识*/
#define XMLNM_ICPS_APPLY_HAS_ADMIT_FLAG         "/icps/apply/has_admit_flag"               /*之前是否有额度*/
#define XMLNM_ICPS_APPLY_APPLY_PLT_DATE         "/icps/apply/apply_plt_date"               /*授信申请平台日期*/
#define XMLNM_ICPS_APPLY_APPLY_PLT_SERIAL       "/icps/apply/apply_plt_serial"             /*授信申请平台流水号*/
#define XMLNM_ICPS_APPLY_APPLY_STATUS           "/icps/apply/apply_status"                 /*授信申请状态*/
#define XMLNM_ICPS_APPLY_CREDIT_NO              "/icps/apply/credit_no"                    /*授信编号*/
#define XMLNM_ICPS_APPLY_INFO_ADMIT_FLAG        "/icps/apply/info_admit_flag"              /*银行是否推荐准入*/
#define XMLNM_ICPS_APPLY_CREDIT_AMT             "/icps/apply/credit_amt"                   /*推荐额度*/
#define XMLNM_ICPS_APPLY_CREDIT_RATE            "/icps/apply/credit_rate"                  /*推荐利率*/
#define XMLNM_ICPS_APPLY_REFUSE_CODE            "/icps/apply/refuse_code"                  /*拒绝码*/
#define XMLNM_ICPS_APPLY_REFUSE_REASON          "/icps/apply/refuse_reason"                /*拒绝原因*/
#define XMLNM_ICPS_APPLY_INFO_PLT_DATE          "/icps/apply/info_plt_date"                /*银行初审平台日期*/
#define XMLNM_ICPS_APPLY_INFO_PLT_SERIAL        "/icps/apply/info_plt_serial"              /*银行初审平台流水号*/
#define XMLNM_ICPS_APPLY_INFO_STATUS            "/icps/apply/info_status"                  /*初审状态*/
#define XMLNM_ICPS_APPLY_THIRD_ACCESS           "/icps/apply/third_access"                 /*是否通过审批*/
#define XMLNM_ICPS_APPLY_THIRD_REFUSE_REASON    "/icps/apply/third_refuse_reason"          /*审批不通过原因*/
#define XMLNM_ICPS_APPLY_THIRD_AMT              "/icps/apply/third_amt"                    /*审批额度*/
#define XMLNM_ICPS_APPLY_THIRD_RATE             "/icps/apply/third_rate"                   /*审批基础利率*/
#define XMLNM_ICPS_APPLY_RISK_RATING            "/icps/apply/risk_rating"                  /*风险评级*/
#define XMLNM_ICPS_APPLY_SOLVENCY_RATING        "/icps/apply/solvency_rating"              /*偿债能力评级*/
#define XMLNM_ICPS_APPLY_CHANGE_RESULT_REASON   "/icps/apply/change_result_reason"         /*额度定价变更原因*/
#define XMLNM_ICPS_APPLY_ACK_ADMIT_FLAG         "/icps/apply/ack_admit_flag"               /*终审银行是否准入*/
#define XMLNM_ICPS_APPLY_ACK_ADMIT_MSG          "/icps/apply/ack_admit_msg"                /*准入原因*/
#define XMLNM_ICPS_APPLY_ACK_PLT_DATE           "/icps/apply/ack_plt_date"                 /*终审平台日期*/
#define XMLNM_ICPS_APPLY_ACK_PLT_SERIAL         "/icps/apply/ack_plt_serial"               /*终审平台流水号*/
#define XMLNM_ICPS_APPLY_ACK_STATUS             "/icps/apply/ack_status"                   /*终审状态*/
#define XMLNM_ICPS_APPLY_EXTEND_PARAM1          "/icps/apply/extend_param1"                /*扩展1*/
#define XMLNM_ICPS_APPLY_EXTEND_PARAM2          "/icps/apply/extend_param2"                /*扩展2*/
#define XMLNM_ICPS_APPLY_EXTEND_PARAM3          "/icps/apply/extend_param3"                /*扩展3*/
/* 授权申请流水 XML节点宏定义 ---END */

/* 芝麻信用信息 XML节点宏定义 ---BEGIN */
#define XMLNM_ICPS_ZMINFO_APPLY_NO                    "/icps/zminfo/apply_no"                     /*申请单号*/
#define XMLNM_ICPS_ZMINFO_PLT_DATE                    "/icps/zminfo/plt_date"                     /*平台日期*/
#define XMLNM_ICPS_ZMINFO_PLT_SERIAL                  "/icps/zminfo/plt_serial"                   /*平台流水号*/
#define XMLNM_ICPS_ZMINFO_ID_TYPE                     "/icps/zminfo/id_type"                      /*证件类型*/
#define XMLNM_ICPS_ZMINFO_ID_NUM                      "/icps/zminfo/id_num"                       /*证件号码*/
#define XMLNM_ICPS_ZMINFO_COMPANY_NAME                "/icps/zminfo/company_name"                 /*所在公司*/
#define XMLNM_ICPS_ZMINFO_OCCUPATION                  "/icps/zminfo/occupation"                   /*职业类型*/
#define XMLNM_ICPS_ZMINFO_HAVE_CAR_FLAG               "/icps/zminfo/have_car_flag"                /*是否有车*/
#define XMLNM_ICPS_ZMINFO_HAVE_HOUSE_FLAG             "/icps/zminfo/have_house_flag"              /*是否有房*/
#define XMLNM_ICPS_ZMINFO_AUTH_FIN_LAST_1M_CNT        "/icps/zminfo/auth_fin_last_1m_cnt"         /*最近一个月主动查询金融机构数*/
#define XMLNM_ICPS_ZMINFO_AUTH_FIN_LAST_3M_CNT        "/icps/zminfo/auth_fin_last_3m_cnt"         /*最近三个月主动查询金融机构数*/
#define XMLNM_ICPS_ZMINFO_AUTH_FIN_LAST_6M_CNT        "/icps/zminfo/auth_fin_last_6m_cnt"         /*最近六个月主动查询金融机构数*/
#define XMLNM_ICPS_ZMINFO_OVD_ORDER_CNT_6M            "/icps/zminfo/ovd_order_cnt_6m"             /*最近六个月逾期总笔数*/
#define XMLNM_ICPS_ZMINFO_OVD_ORDER_AMT_6M            "/icps/zminfo/ovd_order_amt_6m"             /*最近六个月逾期总金额*/
#define XMLNM_ICPS_ZMINFO_MOBILE_FIXED_DAYS           "/icps/zminfo/mobile_fixed_days"            /*手机号稳定天数*/
#define XMLNM_ICPS_ZMINFO_ADR_STABILITY_DAYS          "/icps/zminfo/adr_stability_days"           /*地址稳定天数*/
#define XMLNM_ICPS_ZMINFO_LAST_6M_AVG_ASSET_TOTAL     "/icps/zminfo/last_6m_avg_asset_total"      /*最近六个月流动资产日均值*/
#define XMLNM_ICPS_ZMINFO_TOT_PAY_AMT_6M              "/icps/zminfo/tot_pay_amt_6m"               /*最近六个月支付总金额*/
#define XMLNM_ICPS_ZMINFO_XFDC_INDEX                  "/icps/zminfo/xfdc_index"                   /*消费档次*/
#define XMLNM_ICPS_ZMINFO_POSITIVE_BIZ_CNT_1Y         "/icps/zminfo/positive_biz_cnt_1y"          /*最近一年履约场景数*/
#define XMLNM_ICPS_ZMINFO_EXTEND_PARAM1               "/icps/zminfo/extend_param1"                /*扩展1*/
#define XMLNM_ICPS_ZMINFO_EXTEND_PARAM2               "/icps/zminfo/extend_param2"                /*扩展2*/
#define XMLNM_ICPS_ZMINFO_EXTEND_PARAM3               "/icps/zminfo/extend_param3"                /*扩展3*/
/* 芝麻信用信息 XML节点宏定义 ---END */

/* 人行征信信息 XML节点宏定义 ---BEGIN */
#define XMLNM_ICPS_PBOCINFO_APPLY_NO                          "/icps/pbocinfo/apply_no"                             /*申请单号*/
#define XMLNM_ICPS_PBOCINFO_PLT_DATE                          "/icps/pbocinfo/plt_date"                             /*平台日期*/
#define XMLNM_ICPS_PBOCINFO_PLT_SERIAL                        "/icps/pbocinfo/plt_serial"                           /*平台流水号*/
#define XMLNM_ICPS_PBOCINFO_ID_TYPE                           "/icps/pbocinfo/id_type"                              /*证件类型*/
#define XMLNM_ICPS_PBOCINFO_ID_NUM                            "/icps/pbocinfo/id_num"                               /*证件号码*/
#define XMLNM_ICPS_PBOCINFO_QUERY_NO                          "/icps/pbocinfo/query_no"                             /*查询编号*/
#define XMLNM_ICPS_PBOCINFO_QUERY_FLAG                        "/icps/pbocinfo/query_flag"                           /*查询标记*/
#define XMLNM_ICPS_PBOCINFO_MANAGE_LAST_12_QRY_CNT            "/icps/pbocinfo/manage_last_12_qry_cnt"               /*贷后管理最近12个月查询次数*/
#define XMLNM_ICPS_PBOCINFO_MANAGE_LAST_3_QRY_CNT             "/icps/pbocinfo/manage_last_3_qry_cnt"                /*贷后管理最近3个月查询次数*/
#define XMLNM_ICPS_PBOCINFO_MANAGE_LAST_6_QRY_CNT             "/icps/pbocinfo/manage_last_6_qry_cnt"                /*贷后管理最近6个月查询次数*/
#define XMLNM_ICPS_PBOCINFO_APPROVE_LAST_12_QRY_CNT           "/icps/pbocinfo/approve_last_12_qry_cnt"              /*贷款审批最近12个月查询次数*/
#define XMLNM_ICPS_PBOCINFO_APPROVE_LAST_3_QRY_CNT            "/icps/pbocinfo/approve_last_3_qry_cnt"               /*贷款审批最近3个月查询次数*/
#define XMLNM_ICPS_PBOCINFO_APPROVE_LAST_6_QRY_CNT            "/icps/pbocinfo/approve_last_6_qry_cnt"               /*贷款审批最近6个月查询次数*/
#define XMLNM_ICPS_PBOCINFO_APPROVE_LAST_30D_QRY_ORG_CNT      "/icps/pbocinfo/approve_last_30d_qry_org_cnt"         /*贷款审批最近1个月查询机构数*/
#define XMLNM_ICPS_PBOCINFO_APPROVE_LAST_12_QRY_ORG_CNT       "/icps/pbocinfo/approve_last_12_qry_org_cnt"          /*贷款审批最近12个月查询机构数*/
#define XMLNM_ICPS_PBOCINFO_APPROVE_LAST_3_QRY_ORG_CNT        "/icps/pbocinfo/approve_last_3_qry_org_cnt"           /*贷款审批最近3个月查询机构数*/
#define XMLNM_ICPS_PBOCINFO_APPROVE_LAST_6_QRY_ORG_CNT        "/icps/pbocinfo/approve_last_6_qry_org_cnt"           /*贷款审批最近6个月查询机构数*/
#define XMLNM_ICPS_PBOCINFO_CARD_LAST_12_QRY_CNT              "/icps/pbocinfo/card_last_12_qry_cnt"                 /*信用卡审批最近12个月查询次数*/
#define XMLNM_ICPS_PBOCINFO_CARD_LAST_3_QRY_CNT               "/icps/pbocinfo/card_last_3_qry_cnt"                  /*信用卡审批最近3个月查询次数*/
#define XMLNM_ICPS_PBOCINFO_CARD_LAST_6_QRY_CNT               "/icps/pbocinfo/card_last_6_qry_cnt"                  /*信用卡审批最近6个月查询次数*/
#define XMLNM_ICPS_PBOCINFO_CARD_LAST_30D_QRY_ORG_CNT         "/icps/pbocinfo/card_last_30d_qry_org_cnt"            /*信用卡审批最近1个月查询次数*/
#define XMLNM_ICPS_PBOCINFO_CARD_LAST_3_QRY_ORG_CNT           "/icps/pbocinfo/card_last_3_qry_org_cnt"              /*信用卡审批最近3个月查询机构数*/
#define XMLNM_ICPS_PBOCINFO_CARD_LAST_6_QRY_ORG_CNT           "/icps/pbocinfo/card_last_6_qry_org_cnt"              /*信用卡审批最近6个月查询机构数*/
#define XMLNM_ICPS_PBOCINFO_ALL_LOAN_NUM                      "/icps/pbocinfo/all_loan_num"                         /*总贷款笔数*/
#define XMLNM_ICPS_PBOCINFO_CAR_LOAN_NUM                      "/icps/pbocinfo/car_loan_num"                         /*车贷笔数*/
#define XMLNM_ICPS_PBOCINFO_BIZ_LOAN_NUM                      "/icps/pbocinfo/biz_loan_num"                         /*经营贷款笔数*/
#define XMLNM_ICPS_PBOCINFO_HOUSE_LOAN_NUM                    "/icps/pbocinfo/house_loan_num"                       /*房贷笔数*/
#define XMLNM_ICPS_PBOCINFO_OS_ALL_LOAN_NUM                   "/icps/pbocinfo/os_all_loan_num"                      /*未结清人民币帐户贷款总笔数*/
#define XMLNM_ICPS_PBOCINFO_OS_CAR_LOAN_NUM                   "/icps/pbocinfo/os_car_loan_num"                      /*未结清车贷笔数*/
#define XMLNM_ICPS_PBOCINFO_OS_HOUSE_LOAN_NUM                 "/icps/pbocinfo/os_house_loan_num"                    /*未结清房贷笔数*/
#define XMLNM_ICPS_PBOCINFO_OS_BIZ_LOAN_NUM                   "/icps/pbocinfo/os_biz_loan_num"                      /*未结清经营贷款笔数*/
#define XMLNM_ICPS_PBOCINFO_LN_NCA_CON13_CNT_SUM              "/icps/pbocinfo/ln_nca_con13_cnt_sum"                 /*未结清个人消费贷款笔数*/
#define XMLNM_ICPS_PBOCINFO_LN_NCA_CRD_CNT_SUM                "/icps/pbocinfo/ln_nca_crd_cnt_sum"                   /*未结清信用贷款笔数*/
#define XMLNM_ICPS_PBOCINFO_LOAN_MAX_AMOUNT                   "/icps/pbocinfo/loan_max_amount"                      /*贷款最高额度*/
#define XMLNM_ICPS_PBOCINFO_LOAN_OPER_MAX_AMOUNT              "/icps/pbocinfo/loan_oper_max_amount"                 /*经营性贷款最高额度*/
#define XMLNM_ICPS_PBOCINFO_BALANCE_SUM                       "/icps/pbocinfo/balance_sum"                          /*未结清贷款本金余额总和*/
#define XMLNM_ICPS_PBOCINFO_LOAN_SUM_AMOUNT                   "/icps/pbocinfo/loan_sum_amount"                      /*未结清贷款额度总和*/
#define XMLNM_ICPS_PBOCINFO_LN_NCA_AMT_AVG                    "/icps/pbocinfo/ln_nca_amt_avg"                       /*未结清贷款平均合同金额*/
#define XMLNM_ICPS_PBOCINFO_LOAN_HOUSE_AMT_SUM                "/icps/pbocinfo/loan_house_amt_sum"                   /*未结清房贷合同金额*/
#define XMLNM_ICPS_PBOCINFO_LOAN_HOUSE_BAL_SUM                "/icps/pbocinfo/loan_house_bal_sum"                   /*未结清房贷余额*/
#define XMLNM_ICPS_PBOCINFO_BUSINESS_LOAN_SUM_AMOUNT          "/icps/pbocinfo/business_loan_sum_amount"             /*未结清经营贷款合同金额*/
#define XMLNM_ICPS_PBOCINFO_BUSINESS_LOAN_SUM_BALANCE         "/icps/pbocinfo/business_loan_sum_balance"            /*未结清经营贷款余额*/
#define XMLNM_ICPS_PBOCINFO_LN_NCA_CON13_BAL_SUM              "/icps/pbocinfo/ln_nca_con13_bal_sum"                 /*未结清个人消费贷款余额*/
#define XMLNM_ICPS_PBOCINFO_LN_NCA_RMM_AVG                    "/icps/pbocinfo/ln_nca_rmm_avg"                       /*未结清贷款平均剩余还款月数*/
#define XMLNM_ICPS_PBOCINFO_LN_NCA_PMM_AVG                    "/icps/pbocinfo/ln_nca_pmm_avg"                       /*未结清贷款平均还款月数*/
#define XMLNM_ICPS_PBOCINFO_LN_NCA_PMO_AVG                    "/icps/pbocinfo/ln_nca_pmo_avg"                       /*当月未结清贷款平均应还款*/
#define XMLNM_ICPS_PBOCINFO_LN_NCA_PMT_SUM                    "/icps/pbocinfo/ln_nca_pmt_sum"                       /*未结清贷款当月总实还款*/
#define XMLNM_ICPS_PBOCINFO_REPAY_CAR_MON                     "/icps/pbocinfo/repay_car_mon"                        /*月度车贷按揭应还款*/
#define XMLNM_ICPS_PBOCINFO_REPAY_HOUSE_MON                   "/icps/pbocinfo/repay_house_mon"                      /*月度房贷按揭应还款*/
#define XMLNM_ICPS_PBOCINFO_LN_NCA_M1_MAX_3M                  "/icps/pbocinfo/ln_nca_m1_max_3m"                     /*未结清贷款近3个月最大逾期次数*/
#define XMLNM_ICPS_PBOCINFO_LOAN_OVD_MAX_BAL_CPT              "/icps/pbocinfo/loan_ovd_max_bal_cpt"                 /*贷款单月最大逾期金额*/
#define XMLNM_ICPS_PBOCINFO_LOAN_CUR_OVD_AMOUNT               "/icps/pbocinfo/loan_cur_ovd_amount"                  /*贷款当前逾期总金额*/
#define XMLNM_ICPS_PBOCINFO_LN_CD_MAX_24M                     "/icps/pbocinfo/ln_cd_max_24m"                        /*贷款近24个月最大逾期期数*/
#define XMLNM_ICPS_PBOCINFO_LN_CD_MAX                         "/icps/pbocinfo/ln_cd_max"                            /*当前贷款最大逾期期数*/
#define XMLNM_ICPS_PBOCINFO_LOAN_DELQ_12MTH_MAX               "/icps/pbocinfo/loan_delq_12mth_max"                  /*未结清贷款近12个月最大逾期期数*/
#define XMLNM_ICPS_PBOCINFO_LOAN_DELQ_3MTH_MAX                "/icps/pbocinfo/loan_delq_3mth_max"                   /*未结清贷款近3个月最大逾期期数*/
#define XMLNM_ICPS_PBOCINFO_LOAN_DELQ_6MTH_MAX                "/icps/pbocinfo/loan_delq_6mth_max"                   /*未结清贷款近6个月最大逾期期数*/
#define XMLNM_ICPS_PBOCINFO_CLASS_5_CREDIT_MORTGAGE           "/icps/pbocinfo/class_5_credit_mortgage"              /*按揭类贷款（房贷、车贷）五级分类*/
#define XMLNM_ICPS_PBOCINFO_CLASS_5_NOT_MORTGAGE              "/icps/pbocinfo/class_5_not_mortgage"                 /*非按揭类贷款（房贷、车贷）五级分类*/
#define XMLNM_ICPS_PBOCINFO_DULL_LOAN_NUM                     "/icps/pbocinfo/dull_loan_num"                        /*呆帐信用贷款笔数*/
#define XMLNM_ICPS_PBOCINFO_DULL_LOAN_SUM                     "/icps/pbocinfo/dull_loan_sum"                        /*呆账的贷款数*/
#define XMLNM_ICPS_PBOCINFO_ALL_ASSURE_LOAN_NUM               "/icps/pbocinfo/all_assure_loan_num"                  /*总担保笔数*/
#define XMLNM_ICPS_PBOCINFO_ALL_ASSURE_LOAN_SUM               "/icps/pbocinfo/all_assure_loan_sum"                  /*总担保金额*/
#define XMLNM_ICPS_PBOCINFO_CONT_UNDER_ATTENTION_ASSURE       "/icps/pbocinfo/cont_under_attention_assure"          /*对外担保五级分类关注及以上笔数*/
#define XMLNM_ICPS_PBOCINFO_CONT_UNDER_SECONDARY_ASSURE       "/icps/pbocinfo/cont_under_secondary_assure"          /*状态为次级及以上的担保贷款数*/
#define XMLNM_ICPS_PBOCINFO_ASSURE_UNDER_ATTENTION_AMT        "/icps/pbocinfo/assure_under_attention_amt"           /*状态为关注及以上的担保贷款金额*/
#define XMLNM_ICPS_PBOCINFO_AS_CV2_BAL_SUM                    "/icps/pbocinfo/as_cv2_bal_sum"                       /*对外担保五级分类关注及以上余额*/
#define XMLNM_ICPS_PBOCINFO_CARD_AMT_SUM                      "/icps/pbocinfo/card_amt_sum"                         /*对外担保五级分类关注及以上余额激活且未销户信用卡最大授信额度*/
#define XMLNM_ICPS_PBOCINFO_CC_ACT_LMT_MAX                    "/icps/pbocinfo/cc_act_lmt_max"                       /*激活且未销户信用卡最大授信额度*/
#define XMLNM_ICPS_PBOCINFO_AC_NML_LMT_AVG                    "/icps/pbocinfo/ac_nml_lmt_avg"                       /*正常状态卡平均额度*/
#define XMLNM_ICPS_PBOCINFO_AC_NML_LMT_SUM                    "/icps/pbocinfo/ac_nml_lmt_sum"                       /*正常状态卡总额度*/
#define XMLNM_ICPS_PBOCINFO_CARD_ISSUE_ORG_CNT                "/icps/pbocinfo/card_issue_org_cnt"                   /*正常状态发卡机构数*/
#define XMLNM_ICPS_PBOCINFO_CARD_RMB_CNT                      "/icps/pbocinfo/card_rmb_cnt"                         /*当前激活且未销户人民币贷记卡数*/
#define XMLNM_ICPS_PBOCINFO_CC_CNT_SUM                        "/icps/pbocinfo/cc_cnt_sum"                           /*激活未销户贷记卡数*/
#define XMLNM_ICPS_PBOCINFO_CC_NCA_CNT_SUM                    "/icps/pbocinfo/cc_nca_cnt_sum"                       /*未销户贷记卡数*/
#define XMLNM_ICPS_PBOCINFO_NORMAL_NUM                        "/icps/pbocinfo/normal_num"                           /*正常状态贷记卡数*/
#define XMLNM_ICPS_PBOCINFO_ALL_CARD_CNT                      "/icps/pbocinfo/all_card_cnt"                         /*总卡数*/
#define XMLNM_ICPS_PBOCINFO_CC_ACT_CU_O90_PCT                 "/icps/pbocinfo/cc_act_cu_o90_pct"                    /*激活且未销户贷记卡当前使用率大于等于90%占激活未销户贷记卡比例*/
#define XMLNM_ICPS_PBOCINFO_CC_NCA_CU_MIN                     "/icps/pbocinfo/cc_nca_cu_min"                        /*未销户贷记卡当前最小使用率*/
#define XMLNM_ICPS_PBOCINFO_CC_NCA_MU_MAX                     "/icps/pbocinfo/cc_nca_mu_max"                        /*未销户贷记卡最大6个月平均使用率*/
#define XMLNM_ICPS_PBOCINFO_CARD_NCA_HB_MAX                   "/icps/pbocinfo/card_nca_hb_max"                      /*未销户贷记卡最大使用额度*/
#define XMLNM_ICPS_PBOCINFO_AC_NCA_CU_AVG                     "/icps/pbocinfo/ac_nca_cu_avg"                        /*未销户卡当前平均使用率*/
#define XMLNM_ICPS_PBOCINFO_AC_NCA_HB_MAX                     "/icps/pbocinfo/ac_nca_hb_max"                        /*未销户卡最大使用额度*/
#define XMLNM_ICPS_PBOCINFO_CC_NML_MU_AVG                     "/icps/pbocinfo/cc_nml_mu_avg"                        /*正常状态贷记卡6个月平均使用率*/
#define XMLNM_ICPS_PBOCINFO_ALL_CARD_CUR_OVD_USED             "/icps/pbocinfo/all_card_cur_ovd_used"                /*正常状态卡当前平均使用率*/
#define XMLNM_ICPS_PBOCINFO_CARD_NCA_PMO_SUM                  "/icps/pbocinfo/card_nca_pmo_sum"                     /*所有未销户贷记卡的应还款总额*/
#define XMLNM_ICPS_PBOCINFO_CARD_DELQ_6MTH_MAX_CNT            "/icps/pbocinfo/card_delq_6mth_max_cnt"               /*未销户贷记卡近6个月最大逾期次数*/
#define XMLNM_ICPS_PBOCINFO_CARD_DELQ_12MTH_MAX_CNT           "/icps/pbocinfo/card_delq_12mth_max_cnt"              /*未销户贷记卡近12个月最大逾期次数*/
#define XMLNM_ICPS_PBOCINFO_CARD_DELQ_3MTH_MAX_CNT            "/icps/pbocinfo/card_delq_3mth_max_cnt"               /*未销户贷记卡近3个月最大逾期次数*/
#define XMLNM_ICPS_PBOCINFO_CARD_MAX_OVD_BAL                  "/icps/pbocinfo/card_max_ovd_bal"                     /*贷记卡单月最高逾期金额*/
#define XMLNM_ICPS_PBOCINFO_ALL_CARD_CUR_OVD_AMT_SUM          "/icps/pbocinfo/all_card_cur_ovd_amt_sum"             /*未销户卡当前总逾期金额*/
#define XMLNM_ICPS_PBOCINFO_CONT_DULL_CARD_CNT                "/icps/pbocinfo/cont_dull_card_cnt"                   /*呆账的贷记卡数*/
#define XMLNM_ICPS_PBOCINFO_DULL_SCARD_CNT                    "/icps/pbocinfo/dull_scard_cnt"                       /*呆账的准贷记卡数*/
#define XMLNM_ICPS_PBOCINFO_AC_ABN_CNT_SUM                    "/icps/pbocinfo/ac_abn_cnt_sum"                       /*贷记卡为呆帐冻结止付卡数*/
#define XMLNM_ICPS_PBOCINFO_CC_ACT_M1_CNT_3M                  "/icps/pbocinfo/cc_act_m1_cnt_3m"                     /*激活未销户贷记卡近3个月1期及以上逾期卡数*/
#define XMLNM_ICPS_PBOCINFO_CC_ACT_M1_CNT_PCT_3M              "/icps/pbocinfo/cc_act_m1_cnt_pct_3m"                 /*激活未销户贷记卡近3个月1期及以上逾期卡数占比*/
#define XMLNM_ICPS_PBOCINFO_CC_ACT_M1_CNT_PCT_6M              "/icps/pbocinfo/cc_act_m1_cnt_pct_6m"                 /*激活未销户贷记卡近6个月1期及以上逾期卡数占比*/
#define XMLNM_ICPS_PBOCINFO_AC_NCA_CD_MAX                     "/icps/pbocinfo/ac_nca_cd_max"                        /*未销户卡当前最大逾期期数*/
#define XMLNM_ICPS_PBOCINFO_CC_CD_MAX_24M                     "/icps/pbocinfo/cc_cd_max_24m"                        /*贷记卡近24个月最大逾期期数*/
#define XMLNM_ICPS_PBOCINFO_CARD_DELQ_12MTH_MAX               "/icps/pbocinfo/card_delq_12mth_max"                  /*贷记卡未销户账户中过去12个月最大逾期期数*/
#define XMLNM_ICPS_PBOCINFO_CARD_DELQ_3MTH_MAX                "/icps/pbocinfo/card_delq_3mth_max"                   /*贷记卡未销户账户中过去3个月最大逾期期数*/
#define XMLNM_ICPS_PBOCINFO_CARD_DELQ_6MTH_MAX                "/icps/pbocinfo/card_delq_6mth_max"                   /*贷记卡未销户账户中过去6个月最大逾期期数*/
#define XMLNM_ICPS_PBOCINFO_QC_ACT_CD_MAX_24M                 "/icps/pbocinfo/qc_act_cd_max_24m"                    /*准贷卡近24个月最大逾期期数*/
#define XMLNM_ICPS_PBOCINFO_SCARD_DELQ_12MTH_MAX              "/icps/pbocinfo/scard_delq_12mth_max"                 /*准贷卡未销户账户中过去12个月最大逾期期数*/
#define XMLNM_ICPS_PBOCINFO_SCARD_DELQ_3MTH_MAX               "/icps/pbocinfo/scard_delq_3mth_max"                  /*准贷卡未销户账户中过去3个月最大逾期期数*/
#define XMLNM_ICPS_PBOCINFO_SCARD_DELQ_6MTH_MAX               "/icps/pbocinfo/scard_delq_6mth_max"                  /*准贷卡未销户账户中过去6个月最大逾期期数*/
#define XMLNM_ICPS_PBOCINFO_CREDIT_OPM_MAX                    "/icps/pbocinfo/credit_opm_max"                       /*信用历史*/
#define XMLNM_ICPS_PBOCINFO_AC_OPM_MAX                        "/icps/pbocinfo/ac_opm_max"                           /*最大开卡月数*/
#define XMLNM_ICPS_PBOCINFO_EXTEND_PARAM1                     "/icps/pbocinfo/extend_param1"                        /*扩展1*/
#define XMLNM_ICPS_PBOCINFO_EXTEND_PARAM2                     "/icps/pbocinfo/extend_param2"                        /*扩展2*/
#define XMLNM_ICPS_PBOCINFO_EXTEND_PARAM3                     "/icps/pbocinfo/extend_param3"                        /*扩展3*/
/* 人行征信信息 XML节点宏定义 ---END */

/* 银行信用信息 XML节点宏定义 ---BEGIN */
#define XMLNM_ICPS_BANKINFO_APPLY_NO                          "/icps/bankinfo/apply_no"                             /*申请单号*/
#define XMLNM_ICPS_BANKINFO_PLT_DATE                          "/icps/bankinfo/plt_date"                             /*平台日期*/
#define XMLNM_ICPS_BANKINFO_PLT_SERIAL                        "/icps/bankinfo/plt_serial"                           /*平台流水号*/
#define XMLNM_ICPS_BANKINFO_ID_TYPE                           "/icps/bankinfo/id_type"                              /*证件类型*/
#define XMLNM_ICPS_BANKINFO_ID_NUM                            "/icps/bankinfo/id_num"                               /*证件号码*/
#define XMLNM_ICPS_BANKINFO_IS_EXIST_CUSTOMER                 "/icps/bankinfo/is_exist_customer"                    /*是否存量客户*/
#define XMLNM_ICPS_BANKINFO_IS_EXIST_DEBT_CUSTOMER            "/icps/bankinfo/is_exist_debt_customer"               /*是否存量借记卡客户*/
#define XMLNM_ICPS_BANKINFO_BALANCE                           "/icps/bankinfo/balance"                              /*卡内余额*/
#define XMLNM_ICPS_BANKINFO_AVG_BALANCE_LAST_3DAYS            "/icps/bankinfo/avg_balance_last_3days"               /*近3个月日均余额*/
#define XMLNM_ICPS_BANKINFO_AVG_BALANCE_LAST_6DAYS            "/icps/bankinfo/avg_balance_last_6days"               /*近6个月日均余额*/
#define XMLNM_ICPS_BANKINFO_INCOME_LAST_3M                    "/icps/bankinfo/income_last_3m"                       /*近3个月银行流水收入金额数*/
#define XMLNM_ICPS_BANKINFO_PAY_LAST_3M                       "/icps/bankinfo/pay_last_3m"                          /*近3个月银行流水支出金额数*/
#define XMLNM_ICPS_BANKINFO_INCOME_LAST_6M                    "/icps/bankinfo/income_last_6m"                       /*近6个月银行流水收入金额数*/
#define XMLNM_ICPS_BANKINFO_PAY_LAST_6M                       "/icps/bankinfo/pay_last_6m"                          /*近6个月银行流水支出金额数*/
#define XMLNM_ICPS_BANKINFO_IS_EXIST_CREDIT_CUSTOMER          "/icps/bankinfo/is_exist_credit_customer"             /*是否存量信用卡客户*/
#define XMLNM_ICPS_BANKINFO_CURR_CREDIT_CARD_AMT              "/icps/bankinfo/curr_credit_card_amt"                 /*本行信用卡授信额度*/
#define XMLNM_ICPS_BANKINFO_CURR_USE_CREDIT_CARD_AMT          "/icps/bankinfo/curr_use_credit_card_amt"             /*本行信用卡当前使用额度*/
#define XMLNM_ICPS_BANKINFO_IS_EXIST_FIN_CUSTOMER             "/icps/bankinfo/is_exist_fin_customer"                /*是否存量理财客户*/
#define XMLNM_ICPS_BANKINFO_FIN_BALANCE                       "/icps/bankinfo/fin_balance"                          /*理财余额*/
#define XMLNM_ICPS_BANKINFO_AVG_FIN_BAL_LAST_6M               "/icps/bankinfo/avg_fin_bal_last_6m"                  /*近6个月日均理余额*/
#define XMLNM_ICPS_BANKINFO_IS_EXIST_INSURANCE_CUSTOMER       "/icps/bankinfo/is_exist_insurance_customer"          /*是否存量保险客户*/
#define XMLNM_ICPS_BANKINFO_IS_EXIST_LOAN_CUSTOMER            "/icps/bankinfo/is_exist_loan_customer"               /*是否存量贷款客户*/
#define XMLNM_ICPS_BANKINFO_OPERATION_LOAN_BAL                "/icps/bankinfo/operation_loan_bal"                   /*经营类贷款总余额*/
#define XMLNM_ICPS_BANKINFO_PERSONAL_CREDIT_BAL               "/icps/bankinfo/personal_credit_bal"                  /*个人信用类贷总余额*/
#define XMLNM_ICPS_BANKINFO_CAR_LOAN_BAL                      "/icps/bankinfo/car_loan_bal"                         /*车贷余额*/
#define XMLNM_ICPS_BANKINFO_CAR_ASSET                         "/icps/bankinfo/car_asset"                            /*车产价值评估额*/
#define XMLNM_ICPS_BANKINFO_HOUSE_LOAN_BAL                    "/icps/bankinfo/house_loan_bal"                       /*房贷余额*/
#define XMLNM_ICPS_BANKINFO_HOUSE_ASSET                       "/icps/bankinfo/house_asset"                          /*房产价值评估额*/
#define XMLNM_ICPS_BANKINFO_IS_STOCK_CUSTOMER                 "/icps/bankinfo/is_stock_customer"                    /*是否证券客户*/
#define XMLNM_ICPS_BANKINFO_IS_THIRD_DEPOSITORY               "/icps/bankinfo/is_third_depository"                  /*是否第三方存管客户*/
#define XMLNM_ICPS_BANKINFO_IS_PAYROLL_CUSTOMER               "/icps/bankinfo/is_payroll_customer"                  /*是否工资代发客户*/
#define XMLNM_ICPS_BANKINFO_IS_SOCIAL_SECURITY_CUSTOMER       "/icps/bankinfo/is_social_security_customer"          /*是否社保代缴客户*/
#define XMLNM_ICPS_BANKINFO_IS_LIFE_PAYMENT_CUSTOMER          "/icps/bankinfo/is_life_payment_customer"             /*是否水电煤代缴客户*/
#define XMLNM_ICPS_BANKINFO_COMPANY_NAME                      "/icps/bankinfo/company_name"                         /*工作单位*/
#define XMLNM_ICPS_BANKINFO_COMPANY_ORIGIN                    "/icps/bankinfo/company_origin"                       /*工作单位数据来源*/
#define XMLNM_ICPS_BANKINFO_POSITION                          "/icps/bankinfo/position"                             /*职位*/
#define XMLNM_ICPS_BANKINFO_POSITION_ORIGIN                   "/icps/bankinfo/position_origin"                      /*职位信息来源*/
#define XMLNM_ICPS_BANKINFO_INDUSTRY                          "/icps/bankinfo/industry"                             /*行业*/
#define XMLNM_ICPS_BANKINFO_INDUSTRY_ORIGIN                   "/icps/bankinfo/industry_origin"                      /*行业信息来源*/
#define XMLNM_ICPS_BANKINFO_WORK_YEARS                        "/icps/bankinfo/work_years"                           /*工作年限*/
#define XMLNM_ICPS_BANKINFO_WORK_YEARS_ORIGIN                 "/icps/bankinfo/work_years_origin"                    /*工作年限信息来源*/
#define XMLNM_ICPS_BANKINFO_INCOME                            "/icps/bankinfo/income"                               /*月收入区间*/
#define XMLNM_ICPS_BANKINFO_INCOME_ORIGIN                     "/icps/bankinfo/income_origin"                        /*月收入信息来源*/
#define XMLNM_ICPS_BANKINFO_MARRIAGE_STATUS                   "/icps/bankinfo/marriage_status"                      /*婚姻状态*/
#define XMLNM_ICPS_BANKINFO_MARRIAGE_ORIGIN                   "/icps/bankinfo/marriage_origin"                      /*婚姻状态信息来源*/
#define XMLNM_ICPS_BANKINFO_IS_OPERATION                      "/icps/bankinfo/is_operation"                         /*是否经营者*/
#define XMLNM_ICPS_BANKINFO_OPERATION_ORIGIN                  "/icps/bankinfo/operation_origin"                     /*是否经营者信息来源*/
#define XMLNM_ICPS_BANKINFO_IS_INNER_BLACK_CUSTOMER           "/icps/bankinfo/is_inner_black_customer"              /*是否击中内部黑名单客户*/
#define XMLNM_ICPS_BANKINFO_IS_POLICE_CERTIFIED               "/icps/bankinfo/is_police_certified"                  /*是否公安网身份验证成功*/
#define XMLNM_ICPS_BANKINFO_IS_COURT_EXEC_CUSTOMER            "/icps/bankinfo/is_court_exec_customer"               /*是否击中被执行人等涉诉信息*/
#define XMLNM_ICPS_BANKINFO_IS_QUERY_HOUSE_FUND               "/icps/bankinfo/is_query_house_fund"                  /*是否有查询公积金信息*/
#define XMLNM_ICPS_BANKINFO_FUND_QUERY_DATE                   "/icps/bankinfo/fund_query_date"                      /*公积金查询时间*/
#define XMLNM_ICPS_BANKINFO_FUND_MONTH_AMT                    "/icps/bankinfo/fund_month_amt"                       /*公积金查询月缴纳额*/
#define XMLNM_ICPS_BANKINFO_FUND_ACCT_DATE                    "/icps/bankinfo/fund_acct_date"                       /*公积金开户日期*/
#define XMLNM_ICPS_BANKINFO_FUND_MONTHS_LAST_6M               "/icps/bankinfo/fund_months_last_6m"                  /*近6个月累计缴纳月数*/
#define XMLNM_ICPS_BANKINFO_FUND_AMT_LAST_6M                  "/icps/bankinfo/fund_amt_last_6m"                     /*近6个月累计缴纳金额*/
#define XMLNM_ICPS_BANKINFO_FUND_TOTAL_MONTHS                 "/icps/bankinfo/fund_total_months"                    /*总缴纳月数*/
#define XMLNM_ICPS_BANKINFO_FUND_TOTAL_AMT                    "/icps/bankinfo/fund_total_amt"                       /*总缴纳金额*/
#define XMLNM_ICPS_BANKINFO_FUND_MAX_AMT                      "/icps/bankinfo/fund_max_amt"                         /*公积金属地缴纳上限*/
#define XMLNM_ICPS_BANKINFO_IS_QUERY_SOCIAL_SECURITY          "/icps/bankinfo/is_query_social_security"             /*是否有查询社保信息*/
#define XMLNM_ICPS_BANKINFO_SOCIAL_QUERY_DATE                 "/icps/bankinfo/social_query_date"                    /*社保信息查询时间*/
#define XMLNM_ICPS_BANKINFO_PENSION_QUERY_MONTH_AMT           "/icps/bankinfo/pension_query_month_amt"              /*养老保险查询月缴纳额*/
#define XMLNM_ICPS_BANKINFO_PENSION_ACCT_DATE                 "/icps/bankinfo/pension_acct_date"                    /*养老保险开户日期*/
#define XMLNM_ICPS_BANKINFO_PENSION_MONTHS_LAST_6M            "/icps/bankinfo/pension_months_last_6m"               /*近6个月养老保险累计缴纳月数*/
#define XMLNM_ICPS_BANKINFO_PENSION_AMT_LAST_6M               "/icps/bankinfo/pension_amt_last_6m"                  /*近6个月养老保险累计缴纳金额*/
#define XMLNM_ICPS_BANKINFO_PENSION_TOTAL_MONTHS              "/icps/bankinfo/pension_total_months"                 /*养老保险总缴纳月数*/
#define XMLNM_ICPS_BANKINFO_PENSION_TOTAL_AMT                 "/icps/bankinfo/pension_total_amt"                    /*养老保险总缴纳金额*/
#define XMLNM_ICPS_BANKINFO_MEDICARE_MONTH_AMT                "/icps/bankinfo/medicare_month_amt"                   /*医疗保险查询月缴纳额*/
#define XMLNM_ICPS_BANKINFO_MEDICARE_ACCT_DATE                "/icps/bankinfo/medicare_acct_date"                   /*医疗保险开户日期*/
#define XMLNM_ICPS_BANKINFO_MEDICARE_MONTHS_LAST_6M           "/icps/bankinfo/medicare_months_last_6m"              /*近6个月医疗保险累计缴纳月数*/
#define XMLNM_ICPS_BANKINFO_MEDICARE_AMT_LAST_6M              "/icps/bankinfo/medicare_amt_last_6m"                 /*近6个月医疗保险累计缴纳金额*/
#define XMLNM_ICPS_BANKINFO_MEDICARE_TOTAL_MONTHS             "/icps/bankinfo/medicare_total_months"                /*医疗保险总缴纳月数*/
#define XMLNM_ICPS_BANKINFO_MEDICARE_TOTAL_AMT                "/icps/bankinfo/medicare_total_amt"                   /*医疗保险总缴纳金额*/
#define XMLNM_ICPS_BANKINFO_IS_QUERY_DEGREE                   "/icps/bankinfo/is_query_degree"                      /*是否有查询学历信息*/
#define XMLNM_ICPS_BANKINFO_SCHOOL_NAME                       "/icps/bankinfo/school_name"                          /*院校名称*/
#define XMLNM_ICPS_BANKINFO_DEGREE_LEVEL                      "/icps/bankinfo/degree_level"                         /*学历层次*/
#define XMLNM_ICPS_BANKINFO_DEGREE_TYPE                       "/icps/bankinfo/degree_type"                          /*学历类别*/
#define XMLNM_ICPS_BANKINFO_ENTRANCE_YEAR                     "/icps/bankinfo/entrance_year"                        /*入学年份*/
#define XMLNM_ICPS_BANKINFO_IS_QUERY_COMMUNICATION            "/icps/bankinfo/is_query_communication"               /*是否有查询运营商信息*/
#define XMLNM_ICPS_BANKINFO_COMMUNICATION                     "/icps/bankinfo/communication"                        /*运营商*/
#define XMLNM_ICPS_BANKINFO_ONLINE_DAYS                       "/icps/bankinfo/online_days"                          /*在网时长*/
#define XMLNM_ICPS_BANKINFO_TOTAL_TEL_FARE                    "/icps/bankinfo/total_tel_fare"                       /*总话费账单金额*/
#define XMLNM_ICPS_BANKINFO_TOTAL_CALL_HOURS                  "/icps/bankinfo/total_call_hours"                     /*半年内通话时长*/
#define XMLNM_ICPS_BANKINFO_IS_OUT_BLACK_CUSTOMER             "/icps/bankinfo/is_out_black_customer"                /*是否击中外部查询黑名单*/
#define XMLNM_ICPS_BANKINFO_EXTEND_PARAM1                     "/icps/bankinfo/extend_param1"                        /*扩展1*/
#define XMLNM_ICPS_BANKINFO_EXTEND_PARAM2                     "/icps/bankinfo/extend_param2"                        /*扩展2*/
#define XMLNM_ICPS_BANKINFO_EXTEND_PARAM3                     "/icps/bankinfo/extend_param3"                        /*扩展3*/
/* 银行信用信息 XML节点宏定义 ---END */

/* 日终状态 XML节点宏定义 ---BEGIN */
#define XMLNM_ICPS_DAILY_STATUS_BUSI_DATE                     "/icps/daily_status/busi_date"                        /*业务日期*/
#define XMLNM_ICPS_DAILY_STATUS_BUSI_NO                       "/icps/daily_status/busi_no"                          /*业务编号*/
#define XMLNM_ICPS_DAILY_STATUS_FILE_STEP                     "/icps/daily_status/file_step"                        /*文件步点*/
#define XMLNM_ICPS_DAILY_STATUS_THIRD_TOTAL_CHECK_STATUS      "/icps/daily_status/third_total_check_status"         /*第三方对总账状态*/
#define XMLNM_ICPS_DAILY_STATUS_THIRD_DETAIL_CHECK_STATUS     "/icps/daily_status/third_detail_check_status"        /*第三方明细对账状态*/
#define XMLNM_ICPS_DAILY_STATUS_HOST_TOTAL_CHECK_STATUS       "/icps/daily_status/host_total_check_status"          /*核心对总账状态*/
#define XMLNM_ICPS_DAILY_STATUS_HOST_DETAIL_CHECK_STATUS      "/icps/daily_status/host_detail_check_status"         /*核心明细对账状态*/
#define XMLNM_ICPS_DAILY_STATUS_THIRD_PRE_TOTAL_CHECK_STATUS  "/icps/daily_status/third_pre_total_check_status"     /*第三方预对总账状态*/
#define XMLNM_ICPS_DAILY_STATUS_THIRD_PRE_DETAIL_CHECK_STATUS "/icps/daily_status/third_pre_detail_check_status"    /*第三方预明细对账状态*/
#define XMLNM_ICPS_DAILY_STATUS_HOST_PRE_TOTAL_CHECK_STATUS   "/icps/daily_status/host_pre_total_check_status"      /*核心预对总账状态*/
#define XMLNM_ICPS_DAILY_STATUS_HOST_PRE_DETAIL_CHECK_STATUS  "/icps/daily_status/host_pre_detail_check_status"     /*核心预明细对账状态*/
#define XMLNM_ICPS_DAILY_STATUS_CLEAR_STATUS                  "/icps/daily_status/clear_status"                     /*清算状态*/
#define XMLNM_ICPS_DAILY_STATUS_PLT_DATE                      "/icps/daily_status/plt_date"                         /*平台日期*/
#define XMLNM_ICPS_DAILY_STATUS_PLT_SERIAL                    "/icps/daily_status/plt_serial"                       /*平台流水号*/
#define XMLNM_ICPS_DAILY_STATUS_SEND_HOST_DATE                "/icps/daily_status/send_host_date"                   /*上送主机日期*/
#define XMLNM_ICPS_DAILY_STATUS_HOST_SERIAL                   "/icps/daily_status/host_serial"                      /*主机流水号*/
#define XMLNM_ICPS_DAILY_STATUS_HOST_DATE                     "/icps/daily_status/host_date"                        /*主机日期*/
#define XMLNM_ICPS_DAILY_STATUS_RESPCODE                      "/icps/daily_status/respcode"                         /*交易响应码*/
#define XMLNM_ICPS_DAILY_STATUS_RESPMSG                       "/icps/daily_status/respmsg"                          /*交易响应信息*/
#define XMLNM_ICPS_DAILY_STATUS_TRANS_STATUS                  "/icps/daily_status/trans_status"                     /*交易状态*/
#define XMLNM_ICPS_DAILY_STATUS_BRANCH                        "/icps/daily_status/branch"                           /*交易机构*/
#define XMLNM_ICPS_DAILY_STATUS_TELLER                        "/icps/daily_status/teller"                           /*交易柜员*/
#define XMLNM_ICPS_DAILY_STATUS_EXTEND_PARAM1                 "/icps/daily_status/extend_param1"                    /*扩展1*/
#define XMLNM_ICPS_DAILY_STATUS_EXTEND_PARAM2                 "/icps/daily_status/extend_param2"                    /*扩展2*/
#define XMLNM_ICPS_DAILY_STATUS_EXTEND_PARAM3                 "/icps/daily_status/extend_param3"                    /*扩展3*/
/* 日终状态 XML节点宏定义 ---END */


#define XMLNM_ICPS_REQ_FILEINS_STATUS                         "/icps/req/fileins_status"                            /*文件入库状态 9-初始 0成功 1-部分成功 2-失败*/
#endif
